# Generated by Django 6.0.8 on 2026-10-05 02:19

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted at")),
                (
                    "filepath",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=common.core.models.upload_directory_path,
                        verbose_name="Filepath",
                    ),
                ),
                (
                    "file_url",
                    models.URLField(
                        blank=True,
                        help_text="Usually an address accessible to the outside Internet",
                        max_length=255,
                        null=True,
                        verbose_name="Internet URL",
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="Filename")),
                ("filesize", models.IntegerField(verbose_name="Filesize")),
                ("mime_type", models.CharField(max_length=255, verbose_name="Mime type")),
                ("md5sum", models.CharField(max_length=36, verbose_name="File md5sum")),
                (
                    "is_tmp",
                    models.BooleanField(
                        default=False,
                        help_text="Temporary files are automatically cleared by scheduled tasks",
                        verbose_name="Tmp file",
                    ),
                ),
                ("is_upload", models.BooleanField(default=False, verbose_name="Upload file")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Category options come from the data dictionary upload_category",
                        max_length=32,
                        null=True,
                        verbose_name="Category",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Upload file",
                "verbose_name_plural": "Upload file",
            },
            bases=(common.core.models.AutoCleanFileMixin, models.Model),
        ),
        migrations.CreateModel(
            name="FileAccessLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("filename", models.CharField(blank=True, default="", max_length=255, verbose_name="Filename")),
                ("user_display", models.CharField(blank=True, default="", max_length=128, verbose_name="User display")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("download", "Download"),
                            ("preview", "Preview"),
                            ("delete", "Delete"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="Action",
                    ),
                ),
                ("ipaddress", models.CharField(blank=True, default="", max_length=64, verbose_name="IP address")),
                ("result", models.BooleanField(default=True, verbose_name="Result")),
                ("detail", models.CharField(blank=True, default="", max_length=255, verbose_name="Detail")),
                ("created_time", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created time")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="file_access_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to="file.uploadfile",
                        verbose_name="File",
                    ),
                ),
            ],
            options={
                "verbose_name": "File access log",
                "verbose_name_plural": "File access log",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="UploadSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("filename", models.CharField(max_length=255, verbose_name="Filename")),
                ("filesize", models.BigIntegerField(verbose_name="Filesize")),
                ("total_chunks", models.IntegerField(verbose_name="Total chunks")),
                ("chunk_size", models.IntegerField(verbose_name="Chunk size")),
                ("md5sum", models.CharField(blank=True, default="", max_length=36, verbose_name="File md5sum")),
                ("mime_type", models.CharField(blank=True, default="", max_length=255, verbose_name="Mime type")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed"), ("aborted", "Aborted")],
                        default="pending",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upload_sessions",
                        to="file.uploadfile",
                        verbose_name="Upload file",
                    ),
                ),
            ],
            options={
                "verbose_name": "Upload session",
                "verbose_name_plural": "Upload session",
            },
        ),
        migrations.CreateModel(
            name="UploadSessionPart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("index", models.IntegerField(verbose_name="Chunk index")),
                ("size", models.IntegerField(verbose_name="Chunk size")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="file.uploadsession",
                        verbose_name="Upload session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Upload session part",
                "verbose_name_plural": "Upload session part",
            },
        ),
        migrations.AddIndex(
            model_name="uploadfile",
            index=models.Index(fields=["is_tmp", "created_time"], name="idx_uploadfile_tmp_created"),
        ),
        migrations.AddIndex(
            model_name="uploadfile",
            index=models.Index(fields=["md5sum"], name="idx_uploadfile_md5sum"),
        ),
        migrations.AddIndex(
            model_name="uploadfile",
            index=models.Index(fields=["creator", "created_time"], name="idx_uploadfile_creator_created"),
        ),
        migrations.AddIndex(
            model_name="uploadfile",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["filename"], name="idx_uploadfile_filename_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="fileaccesslog",
            index=models.Index(fields=["file", "created_time"], name="idx_file_log_file_created"),
        ),
        migrations.AddIndex(
            model_name="fileaccesslog",
            index=models.Index(fields=["user", "action"], name="idx_file_log_user_action"),
        ),
        migrations.AddIndex(
            model_name="uploadsession",
            index=models.Index(fields=["creator", "filename", "filesize", "status"], name="idx_upsess_resume"),
        ),
        migrations.AddIndex(
            model_name="uploadsession",
            index=models.Index(fields=["status", "created_time"], name="idx_upsess_status_created"),
        ),
        migrations.AddConstraint(
            model_name="uploadsessionpart",
            constraint=models.UniqueConstraint(fields=("session", "index"), name="uniq_uploadsession_part_index"),
        ),
    ]
