# Generated by Django 6.0.8 on 2026-09-15 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                (
                    "room_type",
                    models.CharField(
                        choices=[("public", "Public chat room"), ("private", "Private chat"), ("ai", "AI assistant")],
                        db_index=True,
                        default="public",
                        max_length=16,
                        verbose_name="Room type",
                    ),
                ),
                ("room_key", models.CharField(max_length=64, unique=True, verbose_name="Room key")),
                ("name", models.CharField(blank=True, default="", max_length=64, verbose_name="Display name")),
                ("last_message", models.CharField(blank=True, default="", max_length=200, verbose_name="Last message")),
                (
                    "last_message_time",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Last message time"),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Active")),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="AI room owner; empty for public/private rooms",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat room",
                "verbose_name_plural": "Chat rooms",
                "ordering": ("-last_message_time", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("sender_name", models.CharField(blank=True, default="", max_length=64, verbose_name="Sender name")),
                (
                    "message_type",
                    models.CharField(
                        choices=[("text", "Text"), ("ai", "AI reply"), ("system", "System message")],
                        db_index=True,
                        default="text",
                        max_length=16,
                        verbose_name="Message type",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "client_msg_id",
                    models.CharField(blank=True, default="", max_length=64, verbose_name="Client message id"),
                ),
                ("is_recalled", models.BooleanField(default=False, verbose_name="Recalled")),
                ("recalled_time", models.DateTimeField(blank=True, null=True, verbose_name="Recalled time")),
                ("extra", models.JSONField(blank=True, default=dict, verbose_name="Extra")),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empty for AI / system messages",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sender",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="message.chatroom",
                        verbose_name="Room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat message",
                "verbose_name_plural": "Chat messages",
                "ordering": ("-id",),
                "indexes": [models.Index(fields=["room", "-id"], name="chat_msg_room_id_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("client_msg_id", ""), _negated=True),
                        fields=("sender", "client_msg_id"),
                        name="uniq_chat_msg_sender_client_id",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChatRoomMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("last_read_id", models.BigIntegerField(default=0, verbose_name="Last read message id")),
                ("unread_count", models.IntegerField(default=0, verbose_name="Unread count")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="message.chatroom",
                        verbose_name="Room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat room member",
                "verbose_name_plural": "Chat room members",
                "indexes": [models.Index(fields=["user", "room"], name="chat_member_user_room_idx")],
                "constraints": [models.UniqueConstraint(fields=("room", "user"), name="uniq_chat_room_member")],
            },
        ),
    ]
