# Generated by Django 6.0.8 on 2026-10-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("sender_name", models.CharField(blank=True, default="", max_length=64, verbose_name="Sender name")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("ai", "AI reply"),
                            ("system", "System message"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("file", "File"),
                        ],
                        db_index=True,
                        default="text",
                        max_length=16,
                        verbose_name="Message type",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "client_msg_id",
                    models.CharField(blank=True, default="", max_length=64, verbose_name="Client message id"),
                ),
                ("is_recalled", models.BooleanField(default=False, verbose_name="Recalled")),
                ("recalled_time", models.DateTimeField(blank=True, null=True, verbose_name="Recalled time")),
                ("extra", models.JSONField(blank=True, default=dict, verbose_name="Extra")),
            ],
            options={
                "verbose_name": "Chat message",
                "verbose_name_plural": "Chat messages",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("public", "Public chat room"),
                            ("private", "Private chat"),
                            ("ai", "AI assistant"),
                            ("group", "Group chat"),
                        ],
                        db_index=True,
                        default="public",
                        max_length=16,
                        verbose_name="Room type",
                    ),
                ),
                ("room_key", models.CharField(max_length=64, unique=True, verbose_name="Room key")),
                ("name", models.CharField(blank=True, default="", max_length=64, verbose_name="Display name")),
                ("last_message", models.CharField(blank=True, default="", max_length=200, verbose_name="Last message")),
                (
                    "last_message_time",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Last message time"),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Chat room",
                "verbose_name_plural": "Chat rooms",
                "ordering": ("-last_message_time", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ChatRoomMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("last_read_id", models.BigIntegerField(default=0, verbose_name="Last read message id")),
                ("unread_count", models.IntegerField(default=0, verbose_name="Unread count")),
            ],
            options={
                "verbose_name": "Chat room member",
                "verbose_name_plural": "Chat room members",
            },
        ),
    ]
