# Generated by Django 6.0.8 on 2026-09-27 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0001_initial"),
        ("system", "0004_accountrisk_apiapplication_apiapplicationgrant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="system.uploadfile",
                verbose_name="Attachment",
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("ai", "AI reply"),
                    ("system", "System message"),
                    ("image", "Image"),
                    ("file", "File"),
                ],
                db_index=True,
                default="text",
                max_length=16,
                verbose_name="Message type",
            ),
        ),
    ]
