# Generated by Django 6.0.8 on 2026-09-17 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="AI room owner or group chat owner; empty for public/private rooms",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("public", "Public chat room"),
                    ("private", "Private chat"),
                    ("ai", "AI assistant"),
                    ("group", "Group chat"),
                ],
                db_index=True,
                default="public",
                max_length=16,
                verbose_name="Room type",
            ),
        ),
    ]
