# Generated by Django 6.0.8 on 2026-10-05 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("message", "0001_initial"),
        ("system", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="system.uploadfile",
                verbose_name="Attachment",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                help_text="Empty for AI / system messages",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Sender",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="AI room owner or group chat owner; empty for public/private rooms",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="message.chatroom",
                verbose_name="Room",
            ),
        ),
        migrations.AddField(
            model_name="chatroommember",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="message.chatroom",
                verbose_name="Room",
            ),
        ),
        migrations.AddField(
            model_name="chatroommember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["room", "-id"], name="chat_msg_room_id_idx"),
        ),
        migrations.AddConstraint(
            model_name="chatmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_msg_id", ""), _negated=True),
                fields=("sender", "client_msg_id"),
                name="uniq_chat_msg_sender_client_id",
            ),
        ),
        migrations.AddIndex(
            model_name="chatroommember",
            index=models.Index(fields=["user", "room"], name="chat_member_user_room_idx"),
        ),
        migrations.AddConstraint(
            model_name="chatroommember",
            constraint=models.UniqueConstraint(fields=("room", "user"), name="uniq_chat_room_member"),
        ),
    ]
