# Generated by Django 6.0.8 on 2026-10-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0002_chatmessage_attachment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("ai", "AI reply"),
                    ("system", "System message"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("file", "File"),
                ],
                db_index=True,
                default="text",
                max_length=16,
                verbose_name="Message type",
            ),
        ),
    ]
