# Generated by Django 6.0.8 on 2026-10-05 02:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("file", "0001_initial"),
        ("identity", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted at")),
                (
                    "menu_type",
                    models.SmallIntegerField(
                        choices=[(0, "Directory"), (1, "Menu"), (2, "Permission")], default=0, verbose_name="Menu type"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Component name or permission code")),
                ("rank", models.IntegerField(default=9999, verbose_name="Rank")),
                ("path", models.CharField(max_length=255, verbose_name="Route path or api path")),
                ("component", models.CharField(blank=True, max_length=255, null=True, verbose_name="Component path")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                            ("PATCH", "PATCH"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Method",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="system.menu",
                        verbose_name="Parent menu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menu",
                "ordering": ("-created_time",),
            },
        ),
        migrations.CreateModel(
            name="DataPermission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                (
                    "mode_type",
                    models.SmallIntegerField(
                        choices=[(0, "Or mode"), (1, "And mode")],
                        default=0,
                        help_text="Permission mode, and the mode indicates that the data needs to satisfy each rule in the rule list at the same time, or the mode satisfies any rule",
                        verbose_name="Data permission mode",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Name")),
                ("rules", models.JSONField(max_length=10240, verbose_name="Rules")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "menu",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If a menu exists, it only applies to the selected menu permission",
                        to="system.menu",
                        verbose_name="Menu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data permission",
                "verbose_name_plural": "Data permission",
                "ordering": ("-created_time",),
            },
        ),
        migrations.CreateModel(
            name="MenuMeta",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("title", models.CharField(blank=True, max_length=255, null=True, verbose_name="Menu title")),
                ("icon", models.CharField(blank=True, max_length=255, null=True, verbose_name="Left icon")),
                (
                    "r_svg_name",
                    models.CharField(
                        blank=True,
                        help_text="Additional icon to the right of menu name",
                        max_length=255,
                        null=True,
                        verbose_name="Right icon",
                    ),
                ),
                ("is_show_menu", models.BooleanField(default=True, verbose_name="Show menu")),
                ("is_show_parent", models.BooleanField(default=False, verbose_name="Show parent menu")),
                (
                    "is_keepalive",
                    models.BooleanField(
                        default=True,
                        help_text="When enabled, the entire state of the page is saved, and when refreshed, the state is cleared",
                        verbose_name="Keepalive",
                    ),
                ),
                (
                    "frame_url",
                    models.CharField(
                        blank=True,
                        help_text="The embedded iframe link address",
                        max_length=255,
                        null=True,
                        verbose_name="Iframe URL",
                    ),
                ),
                ("frame_loading", models.BooleanField(default=False, verbose_name="Iframe loading")),
                (
                    "watermark",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled, pages under this menu always show the site watermark, regardless of the basic-settings path list",
                        verbose_name="Page watermark",
                    ),
                ),
                (
                    "transition_enter",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Enter animation"),
                ),
                (
                    "transition_leave",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Leave animation"),
                ),
                (
                    "is_hidden_tag",
                    models.BooleanField(
                        default=False,
                        help_text="The current menu name or custom information is prohibited from being added to the TAB",
                        verbose_name="Hidden tag",
                    ),
                ),
                (
                    "fixed_tag",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the current menu name is fixed to the TAB and cannot be closed",
                        verbose_name="Fixed tag",
                    ),
                ),
                (
                    "dynamic_level",
                    models.IntegerField(
                        default=0,
                        help_text="Maximum number of dynamic routes that can be opened",
                        verbose_name="Dynamic level",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu meta",
                "verbose_name_plural": "Menu meta",
                "ordering": ("-created_time",),
            },
        ),
        migrations.AddField(
            model_name="menu",
            name="meta",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="system.menumeta", verbose_name="Menu meta"
            ),
        ),
        migrations.CreateModel(
            name="ModelLabelField",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                (
                    "field_type",
                    models.SmallIntegerField(
                        choices=[(0, "Role permission"), (1, "Data permission")], default=1, verbose_name="Field type"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Model/Field name")),
                ("label", models.CharField(max_length=128, verbose_name="Model/Field label")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system.modellabelfield",
                        verbose_name="Parent node",
                    ),
                ),
            ],
            options={
                "verbose_name": "Model label field",
                "verbose_name_plural": "Model label field",
                "ordering": ("-created_time",),
                "unique_together": {("name", "parent")},
            },
        ),
        migrations.AddField(
            model_name="menu",
            name="model",
            field=models.ManyToManyField(blank=True, to="system.modellabelfield", verbose_name="Model"),
        ),
        migrations.CreateModel(
            name="FieldPermission",
            fields=[
                ("id", models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="identity.userrole", verbose_name="Role"
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="system.menu", verbose_name="Menu"
                    ),
                ),
                ("field", models.ManyToManyField(blank=True, to="system.modellabelfield", verbose_name="Field")),
            ],
            options={
                "verbose_name": "Field permission",
                "verbose_name_plural": "Field permission",
                "ordering": ("-created_time",),
            },
        ),
        migrations.CreateModel(
            name="ModuleOverride",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                (
                    "key",
                    models.CharField(
                        default="module", editable=False, max_length=32, unique=True, verbose_name="Config name"
                    ),
                ),
                ("preset", models.CharField(max_length=16, verbose_name="Module preset")),
                ("enable", models.JSONField(blank=True, default=list, verbose_name="Enabled modules")),
                ("disable", models.JSONField(blank=True, default=list, verbose_name="Disabled modules")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module override",
                "verbose_name_plural": "Module override",
                "ordering": ["created_time"],
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("module", models.CharField(blank=True, max_length=64, null=True, verbose_name="Module")),
                ("path", models.CharField(blank=True, max_length=400, null=True, verbose_name="URL path")),
                ("object_pk", models.CharField(blank=True, max_length=64, null=True, verbose_name="Object pk")),
                ("body", models.TextField(blank=True, null=True, verbose_name="Request body")),
                ("method", models.CharField(blank=True, max_length=8, null=True, verbose_name="Request method")),
                ("ipaddress", models.GenericIPAddressField(blank=True, null=True, verbose_name="IpAddress")),
                ("browser", models.CharField(blank=True, max_length=64, null=True, verbose_name="Browser")),
                ("system", models.CharField(blank=True, max_length=64, null=True, verbose_name="System")),
                ("response_code", models.IntegerField(blank=True, null=True, verbose_name="Response code")),
                ("response_result", models.TextField(blank=True, null=True, verbose_name="Response result")),
                ("status_code", models.IntegerField(blank=True, null=True, verbose_name="Status code")),
                ("request_uuid", models.UUIDField(blank=True, null=True, verbose_name="Request ID")),
                ("exec_time", models.FloatField(blank=True, null=True, verbose_name="Execution time")),
                ("changes", models.TextField(blank=True, null=True, verbose_name="Changed fields")),
                (
                    "auth_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("jwt", "JWT"),
                            ("pat", "Personal access token"),
                            ("scim", "SCIM directory sync"),
                            ("ldap", "LDAP directory sync"),
                            ("ai", "AI assistant"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="Auth type",
                    ),
                ),
                ("token_pk", models.BigIntegerField(blank=True, null=True, verbose_name="Token pk")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation log",
                "verbose_name_plural": "Operation log",
                "ordering": ("-created_time",),
            },
        ),
        migrations.CreateModel(
            name="SavedListView",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("page_key", models.CharField(db_index=True, max_length=128, verbose_name="Page key")),
                ("name", models.CharField(max_length=64, verbose_name="View name")),
                ("conditions", models.JSONField(blank=True, default=dict, verbose_name="Conditions")),
                ("ordering", models.CharField(blank=True, default="", max_length=64, verbose_name="Ordering")),
                ("is_default", models.BooleanField(default=False, verbose_name="Is default")),
                ("is_shared", models.BooleanField(default=False, verbose_name="Is shared")),
                ("remark", models.CharField(blank=True, default="", max_length=255, verbose_name="Remark")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_list_views",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved list view",
                "verbose_name_plural": "Saved list view",
                "ordering": ["page_key", "-is_default", "created_time"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("value", models.JSONField(max_length=10240, verbose_name="Config value")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                (
                    "access",
                    models.BooleanField(
                        default=False,
                        help_text="Allows API interfaces to access this config",
                        verbose_name="API access",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True, verbose_name="Config name")),
                (
                    "inherit",
                    models.BooleanField(
                        default=False, help_text="Allows users to inherit this config", verbose_name="User inherit"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "System config",
                "verbose_name_plural": "System config",
                "ordering": ["created_time"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("name", models.CharField(max_length=64, unique=True, verbose_name="Tag name")),
                ("color", models.CharField(blank=True, default="", max_length=16, verbose_name="Color")),
                ("builtin", models.BooleanField(db_index=True, default=False, verbose_name="Builtin")),
                ("remark", models.CharField(blank=True, default="", max_length=255, verbose_name="Remark")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="TaggedItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("object_id", models.CharField(db_index=True, max_length=64, verbose_name="Object id")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content type",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="system.tag",
                        verbose_name="Tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tagged item",
                "verbose_name_plural": "Tagged items",
                "ordering": ("-created_time",),
            },
        ),
        migrations.CreateModel(
            name="TaskExecution",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=255, verbose_name="Task Name")),
                ("args", models.JSONField(blank=True, default=list, verbose_name="Positional Args")),
                ("kwargs", models.JSONField(blank=True, default=dict, verbose_name="Keyword Args")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Waiting"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("REVOKED", "Revoked"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("date_start", models.DateTimeField(blank=True, null=True, verbose_name="Start Time")),
                ("date_finished", models.DateTimeField(blank=True, null=True, verbose_name="Finish Time")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "periodic_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_celery_beat.periodictask",
                        verbose_name="Periodic Task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Execution",
                "verbose_name_plural": "Task Execution",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="UserLoginLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("status", models.BooleanField(default=True, verbose_name="Login status")),
                ("ipaddress", models.GenericIPAddressField(blank=True, null=True, verbose_name="IpAddress")),
                ("city", models.CharField(blank=True, max_length=254, null=True, verbose_name="Login city")),
                ("browser", models.CharField(blank=True, max_length=64, null=True, verbose_name="Browser")),
                ("system", models.CharField(blank=True, max_length=64, null=True, verbose_name="System")),
                ("agent", models.CharField(blank=True, max_length=128, null=True, verbose_name="Agent")),
                ("channel_name", models.CharField(blank=True, max_length=128, null=True, verbose_name="Channel name")),
                (
                    "login_type",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Username and password"),
                            (1, "SMS verification code"),
                            (2, "Email verification code"),
                            (4, "Wechat scan code"),
                            (5, "Third-party OAuth"),
                            (3, "LDAP directory account"),
                            (8, "Websocket"),
                            (9, "Unknown"),
                            (6, "Impersonation"),
                        ],
                        default=0,
                        verbose_name="Login type",
                    ),
                ),
                (
                    "policy_result",
                    models.CharField(blank=True, default="", max_length=128, verbose_name="Policy result"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "User login log",
                "verbose_name_plural": "User login log",
                "ordering": ("-created_time",),
            },
        ),
        migrations.CreateModel(
            name="UserPersonalConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("value", models.JSONField(max_length=10240, verbose_name="Config value")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                (
                    "access",
                    models.BooleanField(
                        default=False,
                        help_text="Allows API interfaces to access this config",
                        verbose_name="API access",
                    ),
                ),
                ("key", models.CharField(max_length=255, verbose_name="Config name")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="User"
                    ),
                ),
            ],
            options={
                "verbose_name": "User config",
                "verbose_name_plural": "User config",
            },
        ),
        migrations.CreateModel(
            name="WebhookSubscription",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("name", models.CharField(max_length=128, unique=True, verbose_name="Name")),
                ("url", models.CharField(max_length=512, verbose_name="URL")),
                ("secret", models.CharField(max_length=512, verbose_name="Secret")),
                (
                    "events",
                    models.JSONField(default=list, help_text="Event keys from EVENT_CATALOG", verbose_name="Events"),
                ),
                ("description", models.CharField(blank=True, default="", max_length=512, verbose_name="Description")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                ("last_failure", models.CharField(blank=True, default="", max_length=512, verbose_name="Last failure")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook subscription",
                "verbose_name_plural": "Webhook subscriptions",
                "ordering": ("-created_time",),
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("event", models.CharField(db_index=True, max_length=64, verbose_name="Event")),
                ("payload", models.JSONField(default=dict, verbose_name="Payload")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed (retrying)"),
                            ("exhausted", "Exhausted"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("attempt", models.IntegerField(default=0, verbose_name="Attempt")),
                ("response_code", models.IntegerField(blank=True, null=True, verbose_name="Response code")),
                (
                    "response_body",
                    models.CharField(blank=True, default="", max_length=500, verbose_name="Response body"),
                ),
                ("duration", models.FloatField(blank=True, help_text="Seconds", null=True, verbose_name="Duration")),
                ("next_retry_at", models.DateTimeField(blank=True, null=True, verbose_name="Next retry at")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="system.webhooksubscription",
                        verbose_name="Subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook delivery",
                "verbose_name_plural": "Webhook deliveries",
                "ordering": ("-created_time",),
            },
        ),
        migrations.CreateModel(
            name="DataDict",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("code", models.CharField(db_index=True, max_length=64, verbose_name="Dict code")),
                ("label", models.CharField(max_length=128, verbose_name="Dict label")),
                ("label_en", models.CharField(blank=True, default="", max_length=128, verbose_name="Dict label (EN)")),
                ("value", models.CharField(blank=True, max_length=255, null=True, verbose_name="Dict value")),
                ("sort", models.IntegerField(default=0, verbose_name="Sort")),
                ("color", models.CharField(blank=True, max_length=32, null=True, verbose_name="Tag color")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                ("is_locked", models.BooleanField(default=False, verbose_name="Is locked")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="system.datadict",
                        verbose_name="Parent dict",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data dict",
                "verbose_name_plural": "Data dict",
                "ordering": ("sort", "created_time"),
                "indexes": [models.Index(fields=["code", "is_active"], name="idx_datadict_code_active")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("parent__isnull", False)),
                        fields=("parent", "code"),
                        name="uniq_datadict_parent_code",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("parent__isnull", True)), fields=("code",), name="uniq_datadict_type_code"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataMaskRule",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                (
                    "model",
                    models.CharField(
                        help_text="Model label like system.userinfo", max_length=128, verbose_name="Model"
                    ),
                ),
                ("field", models.CharField(max_length=64, verbose_name="Field")),
                (
                    "mask_type",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("idcard", "ID card"),
                            ("email", "Email"),
                            ("name", "Name"),
                            ("bankcard", "Bank card"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=16,
                        verbose_name="Mask type",
                    ),
                ),
                ("keep_head", models.PositiveSmallIntegerField(default=3, verbose_name="Keep head")),
                ("keep_tail", models.PositiveSmallIntegerField(default=2, verbose_name="Keep tail")),
                ("mask_char", models.CharField(default="*", max_length=4, verbose_name="Mask char")),
                ("pattern", models.CharField(blank=True, max_length=255, null=True, verbose_name="Custom pattern")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                ("sort", models.IntegerField(default=0, verbose_name="Sort")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True, help_text="Empty = all non-superuser", to="identity.userrole", verbose_name="Roles"
                    ),
                ),
            ],
            options={
                "verbose_name": "Data mask rule",
                "ordering": ("sort", "created_time"),
                "indexes": [models.Index(fields=["model", "field"], name="idx_datamask_model_field")],
            },
        ),
        migrations.CreateModel(
            name="ExportRecord",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="File name")),
                ("module", models.CharField(blank=True, max_length=128, null=True, verbose_name="Source module")),
                ("path", models.CharField(blank=True, max_length=255, null=True, verbose_name="Source path")),
                (
                    "file_format",
                    models.CharField(db_index=True, default="xlsx", max_length=16, verbose_name="File format"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Waiting"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("REVOKED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("rows", models.IntegerField(blank=True, null=True, verbose_name="Row count")),
                ("progress", models.PositiveSmallIntegerField(default=0, verbose_name="Progress")),
                ("stage", models.CharField(blank=True, default="", max_length=64, verbose_name="Progress stage")),
                ("error", models.TextField(blank=True, null=True, verbose_name="Error message")),
                ("params", models.JSONField(blank=True, default=dict, verbose_name="Export params")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="file.uploadfile",
                        verbose_name="Export file",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export record",
                "ordering": ["-created_time"],
                "indexes": [models.Index(fields=["status", "created_time"], name="idx_export_status_created")],
            },
        ),
        migrations.CreateModel(
            name="ImportRecord",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="File name")),
                ("module", models.CharField(blank=True, max_length=128, null=True, verbose_name="Target module")),
                ("path", models.CharField(blank=True, max_length=255, null=True, verbose_name="Source path")),
                (
                    "action",
                    models.CharField(
                        choices=[("create", "Create"), ("update", "Update")],
                        db_index=True,
                        default="create",
                        max_length=16,
                        verbose_name="Import action",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Waiting"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("REVOKED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("total", models.IntegerField(blank=True, null=True, verbose_name="Total rows")),
                ("success_rows", models.IntegerField(default=0, verbose_name="Success rows")),
                ("failed_rows", models.IntegerField(default=0, verbose_name="Failed rows")),
                ("progress", models.PositiveSmallIntegerField(default=0, verbose_name="Progress")),
                ("stage", models.CharField(blank=True, default="", max_length=64, verbose_name="Progress stage")),
                ("error", models.TextField(blank=True, null=True, verbose_name="Error message")),
                ("params", models.JSONField(blank=True, default=dict, verbose_name="Import params")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "error_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_error_reports",
                        to="file.uploadfile",
                        verbose_name="Error report",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_sources",
                        to="file.uploadfile",
                        verbose_name="Source file",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import record",
                "ordering": ["-created_time"],
                "indexes": [models.Index(fields=["status", "created_time"], name="idx_import_status_created")],
            },
        ),
        migrations.CreateModel(
            name="ImportTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                (
                    "model",
                    models.CharField(
                        db_index=True,
                        help_text="Model label like system.userinfo",
                        max_length=128,
                        verbose_name="Target model",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Template name")),
                ("mapping", models.JSONField(blank=True, default=dict, verbose_name="Column mapping")),
                ("options", models.JSONField(blank=True, default=dict, verbose_name="Import options")),
                ("is_shared", models.BooleanField(db_index=True, default=False, verbose_name="Shared")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import template",
                "ordering": ["-created_time"],
                "indexes": [models.Index(fields=["model", "is_shared"], name="idx_import_tpl_model_shared")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("model", "name", "creator"), name="uniq_import_template_model_name_creator"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="menu",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("name",), name="uniq_menu_name_active"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fieldpermission",
            unique_together={("role", "menu")},
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["created_time"], name="idx_oplog_created"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["module", "created_time"], name="idx_oplog_module_created"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["request_uuid"], name="idx_oplog_request_uuid"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["exec_time"], name="idx_oplog_exec_time"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["module", "object_pk"], name="idx_oplog_module_objectpk"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["path"], name="idx_oplog_path"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["token_pk", "created_time"], name="idx_oplog_token_created"),
        ),
        migrations.AddConstraint(
            model_name="savedlistview",
            constraint=models.UniqueConstraint(
                fields=("owner", "page_key", "name"), name="uniq_saved_view_owner_page_name"
            ),
        ),
        migrations.AddIndex(
            model_name="taggeditem",
            index=models.Index(fields=["content_type", "object_id"], name="tagged_item_target_idx"),
        ),
        migrations.AddConstraint(
            model_name="taggeditem",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id", "tag"), name="uniq_tagged_item_content_object_tag"
            ),
        ),
        migrations.AddIndex(
            model_name="userloginlog",
            index=models.Index(fields=["created_time"], name="idx_loginlog_created"),
        ),
        migrations.AlterUniqueTogether(
            name="userpersonalconfig",
            unique_together={("owner", "key")},
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(fields=["subscription", "created_time"], name="idx_webhook_sub_created"),
        ),
    ]
