# Generated by Django 5.0.8 on 2024-09-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userloginlog',
            options={'ordering': ('-created_time',), 'verbose_name': 'User login log', 'verbose_name_plural': 'User login log'},
        ),
        migrations.AddField(
            model_name='userloginlog',
            name='city',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Login city'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='value',
            field=models.JSONField(max_length=10240, verbose_name='Config value'),
        ),
        migrations.AlterField(
            model_name='userpersonalconfig',
            name='value',
            field=models.JSONField(max_length=10240, verbose_name='Config value'),
        ),
    ]
