# Generated by Django 4.2.5 on 2023-09-16 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import system.models


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述信息')),
                ('level', models.CharField(
                    choices=[('', 'default'), ('success', 'success'), ('primary', 'primary'), ('warning', 'warning'),
                             ('danger', 'danger')], default='', max_length=20, verbose_name='消息级别')),
                ('notice_type',
                 models.SmallIntegerField(choices=[(0, '系统通知'), (1, '消息通知'), (2, '系统公告')], default=1,
                                          verbose_name='消息类型')),
                ('title', models.CharField(max_length=255, verbose_name='消息标题')),
                ('message', models.TextField(blank=True, null=True, verbose_name='具体信息内容')),
                ('extra_json', models.JSONField(blank=True, null=True, verbose_name='额外的json数据')),
                ('publish', models.BooleanField(default=True, verbose_name='是否发布')),
            ],
            options={
                'verbose_name': '消息通知',
                'verbose_name_plural': '消息通知',
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述信息')),
                ('filepath', models.FileField(blank=True, null=True, upload_to=system.models.upload_directory_path,
                                              verbose_name='文件存储')),
                ('filename', models.CharField(max_length=150, verbose_name='文件原始名称')),
                ('filesize', models.IntegerField(verbose_name='文件大小')),
                ('is_tmp', models.BooleanField(default=True, verbose_name='是否临时文件')),
                ('owner',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='file_query',
                                   to=settings.AUTH_USER_MODEL, verbose_name='所属人')),
            ],
            options={
                'verbose_name': '上传的文件',
                'verbose_name_plural': '上传的文件',
            },
        ),
        migrations.CreateModel(
            name='NoticeUserRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述信息')),
                ('unread', models.BooleanField(db_index=True, default=True, verbose_name='是否未读')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.noticemessage')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户已读消息',
                'verbose_name_plural': '用户已读消息',
                'ordering': ('-created_time',),
                'unique_together': {('owner', 'notice')},
                'index_together': {('owner', 'unread')},
            },
        ),
        migrations.AddField(
            model_name='noticemessage',
            name='file',
            field=models.ManyToManyField(to='system.uploadfile', verbose_name='上传的资源'),
        ),
        migrations.AddField(
            model_name='noticemessage',
            name='owner',
            field=models.ManyToManyField(blank=True, null=True, through='system.NoticeUserRead',
                                         to=settings.AUTH_USER_MODEL),
        ),
    ]
