# Generated by Django 5.0.8 on 2024-08-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginlog',
            name='city',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Login city'),
        ),
    ]
