# Generated by Django 5.1.7 on 2025-03-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0002_operationlog_exec_time_operationlog_request_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginlog',
            name='channel_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Channel name'),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='login_type',
            field=models.SmallIntegerField(
                choices=[(0, 'Username and password'), (1, 'SMS verification code'), (2, 'Email verification code'),
                         (4, 'Wechat scan code'), (8, 'Websocket'), (9, 'Unknown')], default=0,
                verbose_name='Login type'),
        ),
    ]
