# Generated by Django 5.2.9 on 2026-09-04 23:42
#
# PERF-04：为高增长表（OperationLog / UserLoginLog / UploadFile）补建过滤与排序索引。
# 部署提示：
# - Django 的 AddIndex 在 MySQL 上默认 ALGORITHM=INPLACE, LOCK=NONE，但索引构建仍消耗 IO，
#   建议在低峰期执行本迁移；
# - PostgreSQL 上如需完全不加锁（CREATE INDEX CONCURRENTLY），可改用 RunSQL 裸 SQL
#   （atomic = False）并在低峰期单独执行。

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_userloginlog_channel_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['created_time'], name='idx_oplog_created'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['module', 'created_time'], name='idx_oplog_module_created'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['request_uuid'], name='idx_oplog_request_uuid'),
        ),
        migrations.AddIndex(
            model_name='uploadfile',
            index=models.Index(fields=['is_tmp', 'created_time'], name='idx_uploadfile_tmp_created'),
        ),
        migrations.AddIndex(
            model_name='uploadfile',
            index=models.Index(fields=['md5sum'], name='idx_uploadfile_md5sum'),
        ),
        migrations.AddIndex(
            model_name='userloginlog',
            index=models.Index(fields=['created_time'], name='idx_loginlog_created'),
        ),
    ]
