# Generated by Django 6.0.8 on 2026-10-08 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0003_codegenplan"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userpersonalconfig",
            options={"ordering": ["created_time"], "verbose_name": "User config", "verbose_name_plural": "User config"},
        ),
    ]
