# Generated by Django 6.0.8 on 2026-09-10 13:20

import django.db.models.deletion
import django.utils.timezone
import system.models.user
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("system", "0003_userloginlog_channel_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("module", models.CharField(blank=True, max_length=64, null=True, verbose_name="Module")),
                ("method", models.CharField(max_length=8, verbose_name="Method")),
                ("path", models.CharField(max_length=400, verbose_name="URL path")),
                ("object_pk", models.CharField(blank=True, max_length=64, null=True, verbose_name="Object pk")),
                ("params", models.JSONField(blank=True, default=dict, verbose_name="Request params")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True, verbose_name="Approved at")),
                ("expired_at", models.DateTimeField(blank=True, null=True, verbose_name="Token expired at")),
                ("consume_time", models.DateTimeField(blank=True, null=True, verbose_name="Consume time")),
                ("reason", models.CharField(blank=True, max_length=255, null=True, verbose_name="Reason")),
            ],
            options={
                "verbose_name": "Approval request",
                "verbose_name_plural": "Approval request",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="DataDict",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("code", models.CharField(db_index=True, max_length=64, verbose_name="Dict code")),
                ("label", models.CharField(max_length=128, verbose_name="Dict label")),
                ("label_en", models.CharField(blank=True, default="", max_length=128, verbose_name="Dict label (EN)")),
                ("value", models.CharField(blank=True, max_length=255, null=True, verbose_name="Dict value")),
                ("sort", models.IntegerField(default=0, verbose_name="Sort")),
                ("color", models.CharField(blank=True, max_length=32, null=True, verbose_name="Tag color")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                ("is_locked", models.BooleanField(default=False, verbose_name="Is locked")),
            ],
            options={
                "verbose_name": "Data dict",
                "verbose_name_plural": "Data dict",
                "ordering": ("sort", "created_time"),
            },
        ),
        migrations.CreateModel(
            name="DataMaskRule",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                (
                    "model",
                    models.CharField(
                        help_text="Model label like system.userinfo", max_length=128, verbose_name="Model"
                    ),
                ),
                ("field", models.CharField(max_length=64, verbose_name="Field")),
                (
                    "mask_type",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("idcard", "ID card"),
                            ("email", "Email"),
                            ("name", "Name"),
                            ("bankcard", "Bank card"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=16,
                        verbose_name="Mask type",
                    ),
                ),
                ("keep_head", models.PositiveSmallIntegerField(default=3, verbose_name="Keep head")),
                ("keep_tail", models.PositiveSmallIntegerField(default=2, verbose_name="Keep tail")),
                ("mask_char", models.CharField(default="*", max_length=4, verbose_name="Mask char")),
                ("pattern", models.CharField(blank=True, max_length=255, null=True, verbose_name="Custom pattern")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                ("sort", models.IntegerField(default=0, verbose_name="Sort")),
            ],
            options={
                "verbose_name": "Data mask rule",
                "ordering": ("sort", "created_time"),
            },
        ),
        migrations.CreateModel(
            name="ExportRecord",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="File name")),
                ("module", models.CharField(blank=True, max_length=128, null=True, verbose_name="Source module")),
                ("path", models.CharField(blank=True, max_length=255, null=True, verbose_name="Source path")),
                (
                    "file_format",
                    models.CharField(db_index=True, default="xlsx", max_length=16, verbose_name="File format"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Waiting"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("rows", models.IntegerField(blank=True, null=True, verbose_name="Row count")),
                ("progress", models.PositiveSmallIntegerField(default=0, verbose_name="Progress")),
                ("error", models.TextField(blank=True, null=True, verbose_name="Error message")),
                ("params", models.JSONField(blank=True, default=dict, verbose_name="Export params")),
            ],
            options={
                "verbose_name": "Export record",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="ImportRecord",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="File name")),
                ("module", models.CharField(blank=True, max_length=128, null=True, verbose_name="Target module")),
                ("path", models.CharField(blank=True, max_length=255, null=True, verbose_name="Source path")),
                (
                    "action",
                    models.CharField(
                        choices=[("create", "Create"), ("update", "Update")],
                        db_index=True,
                        default="create",
                        max_length=16,
                        verbose_name="Import action",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Waiting"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("total", models.IntegerField(blank=True, null=True, verbose_name="Total rows")),
                ("success_rows", models.IntegerField(default=0, verbose_name="Success rows")),
                ("failed_rows", models.IntegerField(default=0, verbose_name="Failed rows")),
                ("progress", models.PositiveSmallIntegerField(default=0, verbose_name="Progress")),
                ("error", models.TextField(blank=True, null=True, verbose_name="Error message")),
                ("params", models.JSONField(blank=True, default=dict, verbose_name="Import params")),
            ],
            options={
                "verbose_name": "Import record",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="PersonalAccessToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("name", models.CharField(max_length=128, verbose_name="Token name")),
                ("token_hash", models.CharField(max_length=64, unique=True, verbose_name="Token hash")),
                ("token_prefix", models.CharField(max_length=16, verbose_name="Token prefix")),
                ("scopes", models.JSONField(blank=True, default=list, verbose_name="Scopes")),
                ("ip_allowlist", models.JSONField(blank=True, default=list, verbose_name="Ip allowlist")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                ("expired_at", models.DateTimeField(blank=True, null=True, verbose_name="Expired at")),
                ("last_used_time", models.DateTimeField(blank=True, null=True, verbose_name="Last used time")),
            ],
            options={
                "verbose_name": "Personal access token",
                "verbose_name_plural": "Personal access token",
                "ordering": ("-created_time",),
            },
        ),
        migrations.CreateModel(
            name="TaskExecution",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=255, verbose_name="Task Name")),
                ("args", models.JSONField(blank=True, default=list, verbose_name="Positional Args")),
                ("kwargs", models.JSONField(blank=True, default=dict, verbose_name="Keyword Args")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Waiting"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("REVOKED", "Revoked"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("date_start", models.DateTimeField(blank=True, null=True, verbose_name="Start Time")),
                ("date_finished", models.DateTimeField(blank=True, null=True, verbose_name="Finish Time")),
            ],
            options={
                "verbose_name": "Task Execution",
                "verbose_name_plural": "Task Execution",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("ONLINE", "Online"), ("OFFLINE", "Offline")],
                        db_index=True,
                        default="ONLINE",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("channel_name", models.CharField(blank=True, default="", max_length=128, verbose_name="WS channel")),
                ("ipaddress", models.CharField(blank=True, default="", max_length=128, verbose_name="Login IP")),
                ("city", models.CharField(blank=True, default="", max_length=128, verbose_name="Login city")),
                ("browser", models.CharField(blank=True, default="", max_length=128, verbose_name="Browser")),
                ("system", models.CharField(blank=True, default="", max_length=128, verbose_name="System")),
                ("agent", models.CharField(blank=True, default="", max_length=512, verbose_name="User agent")),
                (
                    "login_type",
                    models.IntegerField(
                        choices=[
                            (0, "Username and password"),
                            (1, "SMS verification code"),
                            (2, "Email verification code"),
                            (4, "Wechat scan code"),
                            (8, "Websocket"),
                            (9, "Unknown"),
                        ],
                        default=9,
                        verbose_name="Login type",
                    ),
                ),
                (
                    "last_active",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="Last active"),
                ),
            ],
            options={
                "verbose_name": "User session",
                "ordering": ["-last_active"],
            },
        ),
        migrations.AlterModelOptions(
            name="systemconfig",
            options={
                "ordering": ["created_time"],
                "verbose_name": "System config",
                "verbose_name_plural": "System config",
            },
        ),
        migrations.AlterModelManagers(
            name="userinfo",
            managers=[
                ("objects", system.models.user.SoftDeleteUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="deptinfo",
            name="mode_type",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="mode_type",
        ),
        migrations.AddField(
            model_name="deptinfo",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                help_text="Department leader, who can be granted data permissions of the led departments",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leader_depts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Leader",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted at"),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="auth_type",
            field=models.CharField(
                blank=True,
                choices=[("jwt", "JWT"), ("pat", "Personal access token")],
                max_length=16,
                null=True,
                verbose_name="Auth type",
            ),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="changes",
            field=models.TextField(blank=True, null=True, verbose_name="Changed fields"),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="object_pk",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="Object pk"),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="token_pk",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="Token pk"),
        ),
        migrations.AddField(
            model_name="uploadfile",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Category options come from the data dictionary upload_category",
                max_length=32,
                null=True,
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="uploadfile",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted at"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted at"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="mfa_level",
            field=models.IntegerField(choices=[(0, "Disabled"), (1, "Enabled")], default=0, verbose_name="MFA level"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="otp_secret_key",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="OTP secret key"),
        ),
        migrations.AddField(
            model_name="userrole",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted at"),
        ),
        migrations.AlterField(
            model_name="menu",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Component name or permission code"),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="code",
            field=models.CharField(max_length=128, verbose_name="Role code"),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Role name"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["created_time"], name="idx_oplog_created"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["module", "created_time"], name="idx_oplog_module_created"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["request_uuid"], name="idx_oplog_request_uuid"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["exec_time"], name="idx_oplog_exec_time"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["module", "object_pk"], name="idx_oplog_module_objectpk"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["path"], name="idx_oplog_path"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["token_pk", "created_time"], name="idx_oplog_token_created"),
        ),
        migrations.AddIndex(
            model_name="uploadfile",
            index=models.Index(fields=["is_tmp", "created_time"], name="idx_uploadfile_tmp_created"),
        ),
        migrations.AddIndex(
            model_name="uploadfile",
            index=models.Index(fields=["md5sum"], name="idx_uploadfile_md5sum"),
        ),
        migrations.AddIndex(
            model_name="uploadfile",
            index=models.Index(fields=["creator", "created_time"], name="idx_uploadfile_creator_created"),
        ),
        migrations.AddIndex(
            model_name="userloginlog",
            index=models.Index(fields=["created_time"], name="idx_loginlog_created"),
        ),
        migrations.AddConstraint(
            model_name="menu",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("name",), name="uniq_menu_name_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("name",), name="uniq_userrole_name_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("code",), name="uniq_userrole_code_active"
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approver",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddField(
            model_name="datadict",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="datadict",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="datadict",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddField(
            model_name="datadict",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="system.datadict",
                verbose_name="Parent dict",
            ),
        ),
        migrations.AddField(
            model_name="datamaskrule",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="datamaskrule",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="datamaskrule",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddField(
            model_name="datamaskrule",
            name="roles",
            field=models.ManyToManyField(
                blank=True, help_text="Empty = all non-superuser", to="system.userrole", verbose_name="Roles"
            ),
        ),
        migrations.AddField(
            model_name="exportrecord",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="exportrecord",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="exportrecord",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="system.uploadfile",
                verbose_name="Export file",
            ),
        ),
        migrations.AddField(
            model_name="exportrecord",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddField(
            model_name="importrecord",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="importrecord",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="importrecord",
            name="error_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="import_error_reports",
                to="system.uploadfile",
                verbose_name="Error report",
            ),
        ),
        migrations.AddField(
            model_name="importrecord",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddField(
            model_name="importrecord",
            name="source_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="import_sources",
                to="system.uploadfile",
                verbose_name="Source file",
            ),
        ),
        migrations.AddField(
            model_name="personalaccesstoken",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="personalaccesstoken",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="personalaccesstoken",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="periodic_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_celery_beat.periodictask",
                verbose_name="Periodic Task",
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(fields=["status", "created_time"], name="idx_approval_status_created"),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(fields=["creator", "created_time"], name="idx_approval_creator_created"),
        ),
        migrations.AddIndex(
            model_name="datadict",
            index=models.Index(fields=["code", "is_active"], name="idx_datadict_code_active"),
        ),
        migrations.AddConstraint(
            model_name="datadict",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=("parent", "code"),
                name="uniq_datadict_parent_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="datadict",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)), fields=("code",), name="uniq_datadict_type_code"
            ),
        ),
        migrations.AddIndex(
            model_name="datamaskrule",
            index=models.Index(fields=["model", "field"], name="idx_datamask_model_field"),
        ),
        migrations.AddIndex(
            model_name="exportrecord",
            index=models.Index(fields=["status", "created_time"], name="idx_export_status_created"),
        ),
        migrations.AddIndex(
            model_name="importrecord",
            index=models.Index(fields=["status", "created_time"], name="idx_import_status_created"),
        ),
        migrations.AddIndex(
            model_name="personalaccesstoken",
            index=models.Index(fields=["creator", "created_time"], name="idx_pat_creator_created"),
        ),
        migrations.AddIndex(
            model_name="personalaccesstoken",
            index=models.Index(fields=["expired_at"], name="idx_pat_expired_at"),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(fields=["status", "last_active"], name="idx_session_status_active"),
        ),
    ]
