# Generated by Django 5.2.17 on 2026-09-07 22:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import system.models.user


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("system", "0003_userloginlog_channel_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskExecution",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=255, verbose_name="Task Name")),
                ("args", models.JSONField(blank=True, default=list, verbose_name="Positional Args")),
                ("kwargs", models.JSONField(blank=True, default=dict, verbose_name="Keyword Args")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Waiting"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("REVOKED", "Revoked"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("date_start", models.DateTimeField(blank=True, null=True, verbose_name="Start Time")),
                ("date_finished", models.DateTimeField(blank=True, null=True, verbose_name="Finish Time")),
            ],
            options={
                "verbose_name": "Task Execution",
                "verbose_name_plural": "Task Execution",
                "ordering": ["-created_time"],
            },
        ),
        migrations.AlterModelManagers(
            name="userinfo",
            managers=[
                ("objects", system.models.user.SoftDeleteUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="menu",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted at"),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="changes",
            field=models.TextField(blank=True, null=True, verbose_name="Changed fields"),
        ),
        migrations.AddField(
            model_name="uploadfile",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted at"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted at"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="mfa_level",
            field=models.IntegerField(choices=[(0, "Disabled"), (1, "Enabled")], default=0, verbose_name="MFA level"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="otp_secret_key",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="OTP secret key"),
        ),
        migrations.AddField(
            model_name="userrole",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted at"),
        ),
        migrations.AlterField(
            model_name="menu",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Component name or permission code"),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="code",
            field=models.CharField(max_length=128, verbose_name="Role code"),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Role name"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["created_time"], name="idx_oplog_created"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["module", "created_time"], name="idx_oplog_module_created"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["request_uuid"], name="idx_oplog_request_uuid"),
        ),
        migrations.AddIndex(
            model_name="uploadfile",
            index=models.Index(fields=["is_tmp", "created_time"], name="idx_uploadfile_tmp_created"),
        ),
        migrations.AddIndex(
            model_name="uploadfile",
            index=models.Index(fields=["md5sum"], name="idx_uploadfile_md5sum"),
        ),
        migrations.AddIndex(
            model_name="userloginlog",
            index=models.Index(fields=["created_time"], name="idx_loginlog_created"),
        ),
        migrations.AddConstraint(
            model_name="menu",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("name",), name="uniq_menu_name_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("name",), name="uniq_userrole_name_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("code",), name="uniq_userrole_code_active"
            ),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="periodic_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_celery_beat.periodictask",
                verbose_name="Periodic Task",
            ),
        ),
    ]
