# Generated by Django 6.0.8 on 2026-09-09 05:58

import django.db.models.deletion
import django.utils.timezone
import system.models.user
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("system", "0003_userloginlog_channel_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataDict",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("code", models.CharField(db_index=True, max_length=64, verbose_name="Dict code")),
                ("label", models.CharField(max_length=128, verbose_name="Dict label")),
                ("label_en", models.CharField(blank=True, default="", max_length=128, verbose_name="Dict label (EN)")),
                ("value", models.CharField(blank=True, max_length=255, null=True, verbose_name="Dict value")),
                ("sort", models.IntegerField(default=0, verbose_name="Sort")),
                ("color", models.CharField(blank=True, max_length=32, null=True, verbose_name="Tag color")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
            ],
            options={
                "verbose_name": "Data dict",
                "verbose_name_plural": "Data dict",
                "ordering": ("sort", "created_time"),
            },
        ),
        migrations.CreateModel(
            name="ExportRecord",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="File name")),
                ("module", models.CharField(blank=True, max_length=128, null=True, verbose_name="Source module")),
                ("path", models.CharField(blank=True, max_length=255, null=True, verbose_name="Source path")),
                (
                    "file_format",
                    models.CharField(db_index=True, default="xlsx", max_length=16, verbose_name="File format"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Waiting"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("rows", models.IntegerField(blank=True, null=True, verbose_name="Row count")),
                ("error", models.TextField(blank=True, null=True, verbose_name="Error message")),
                ("params", models.JSONField(blank=True, default=dict, verbose_name="Export params")),
            ],
            options={
                "verbose_name": "Export record",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="TaskExecution",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=255, verbose_name="Task Name")),
                ("args", models.JSONField(blank=True, default=list, verbose_name="Positional Args")),
                ("kwargs", models.JSONField(blank=True, default=dict, verbose_name="Keyword Args")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Waiting"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("REVOKED", "Revoked"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("date_start", models.DateTimeField(blank=True, null=True, verbose_name="Start Time")),
                ("date_finished", models.DateTimeField(blank=True, null=True, verbose_name="Finish Time")),
            ],
            options={
                "verbose_name": "Task Execution",
                "verbose_name_plural": "Task Execution",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("ONLINE", "Online"), ("OFFLINE", "Offline")],
                        db_index=True,
                        default="ONLINE",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("channel_name", models.CharField(blank=True, default="", max_length=128, verbose_name="WS channel")),
                ("ipaddress", models.CharField(blank=True, default="", max_length=128, verbose_name="Login IP")),
                ("city", models.CharField(blank=True, default="", max_length=128, verbose_name="Login city")),
                ("browser", models.CharField(blank=True, default="", max_length=128, verbose_name="Browser")),
                ("system", models.CharField(blank=True, default="", max_length=128, verbose_name="System")),
                ("agent", models.CharField(blank=True, default="", max_length=512, verbose_name="User agent")),
                (
                    "login_type",
                    models.IntegerField(
                        choices=[
                            (0, "Username and password"),
                            (1, "SMS verification code"),
                            (2, "Email verification code"),
                            (4, "Wechat scan code"),
                            (8, "Websocket"),
                            (9, "Unknown"),
                        ],
                        default=9,
                        verbose_name="Login type",
                    ),
                ),
                (
                    "last_active",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="Last active"),
                ),
            ],
            options={
                "verbose_name": "User session",
                "ordering": ["-last_active"],
            },
        ),
        migrations.AlterModelManagers(
            name="userinfo",
            managers=[
                ("objects", system.models.user.SoftDeleteUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="menu",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted at"),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="changes",
            field=models.TextField(blank=True, null=True, verbose_name="Changed fields"),
        ),
        migrations.AddField(
            model_name="uploadfile",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted at"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted at"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="mfa_level",
            field=models.IntegerField(choices=[(0, "Disabled"), (1, "Enabled")], default=0, verbose_name="MFA level"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="otp_secret_key",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="OTP secret key"),
        ),
        migrations.AddField(
            model_name="userrole",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted at"),
        ),
        migrations.AlterField(
            model_name="menu",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Component name or permission code"),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="code",
            field=models.CharField(max_length=128, verbose_name="Role code"),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Role name"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["created_time"], name="idx_oplog_created"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["module", "created_time"], name="idx_oplog_module_created"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["request_uuid"], name="idx_oplog_request_uuid"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["exec_time"], name="idx_oplog_exec_time"),
        ),
        migrations.AddIndex(
            model_name="uploadfile",
            index=models.Index(fields=["is_tmp", "created_time"], name="idx_uploadfile_tmp_created"),
        ),
        migrations.AddIndex(
            model_name="uploadfile",
            index=models.Index(fields=["md5sum"], name="idx_uploadfile_md5sum"),
        ),
        migrations.AddIndex(
            model_name="userloginlog",
            index=models.Index(fields=["created_time"], name="idx_loginlog_created"),
        ),
        migrations.AddConstraint(
            model_name="menu",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("name",), name="uniq_menu_name_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("name",), name="uniq_userrole_name_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("code",), name="uniq_userrole_code_active"
            ),
        ),
        migrations.AddField(
            model_name="datadict",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="datadict",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="datadict",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddField(
            model_name="datadict",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="system.datadict",
                verbose_name="Parent dict",
            ),
        ),
        migrations.AddField(
            model_name="exportrecord",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="exportrecord",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="exportrecord",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="system.uploadfile",
                verbose_name="Export file",
            ),
        ),
        migrations.AddField(
            model_name="exportrecord",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="periodic_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_celery_beat.periodictask",
                verbose_name="Periodic Task",
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddIndex(
            model_name="datadict",
            index=models.Index(fields=["code", "is_active"], name="idx_datadict_code_active"),
        ),
        migrations.AddConstraint(
            model_name="datadict",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=("parent", "code"),
                name="uniq_datadict_parent_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="datadict",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)), fields=("code",), name="uniq_datadict_type_code"
            ),
        ),
        migrations.AddIndex(
            model_name="exportrecord",
            index=models.Index(fields=["status", "created_time"], name="idx_export_status_created"),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(fields=["status", "last_active"], name="idx_session_status_active"),
        ),
    ]
