# Generated by Django 5.2.17 on 2026-09-07 01:52

import system.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_userloginlog_channel_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userinfo',
            managers=[
                ('objects', system.models.user.SoftDeleteUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='changes',
            field=models.TextField(blank=True, null=True, verbose_name='Changed fields'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='mfa_level',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=0, verbose_name='MFA level'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='otp_secret_key',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='OTP secret key'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Component name or permission code'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='code',
            field=models.CharField(max_length=128, verbose_name='Role code'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Role name'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['created_time'], name='idx_oplog_created'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['module', 'created_time'], name='idx_oplog_module_created'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['request_uuid'], name='idx_oplog_request_uuid'),
        ),
        migrations.AddIndex(
            model_name='uploadfile',
            index=models.Index(fields=['is_tmp', 'created_time'], name='idx_uploadfile_tmp_created'),
        ),
        migrations.AddIndex(
            model_name='uploadfile',
            index=models.Index(fields=['md5sum'], name='idx_uploadfile_md5sum'),
        ),
        migrations.AddIndex(
            model_name='userloginlog',
            index=models.Index(fields=['created_time'], name='idx_loginlog_created'),
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='uniq_menu_name_active'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='uniq_userrole_name_active'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='uniq_userrole_code_active'),
        ),
    ]
