# Generated by Django 6.0.8 on 2026-09-22 04:06

from django.db import migrations, models


def backfill_display(apps, schema_editor):
    """历史审批行回填「处理人显示名快照」（U-1）：用户删除/改名后轨迹仍可读。

    快照口径 = 昵称优先、缺失回落用户名（与 system.utils.approval.display 一致）。
    """
    UserInfo = apps.get_model("system", "UserInfo")
    name_map = {
        pk: (nickname or username)
        for pk, username, nickname in UserInfo.objects.values_list("pk", "username", "nickname").iterator()
    }

    def fill(model, fields):
        rows = list(model.objects.all())
        changed = []
        for row in rows:
            touched = False
            for field, source in fields:
                user_id = getattr(row, source)
                if user_id and not getattr(row, field):
                    setattr(row, field, name_map.get(user_id, "") or "")
                    touched = touched or bool(getattr(row, field))
            if touched:
                changed.append(row)
        if changed:
            model.objects.bulk_update(changed, [field for field, _source in fields], batch_size=500)

    fill(
        apps.get_model("system", "ApprovalNodeTask"),
        (("assignee_display", "assignee_id"), ("actor_display", "actor_id")),
    )
    fill(apps.get_model("system", "ApprovalRequest"), (("approver_display", "approver_id"),))
    fill(apps.get_model("system", "ApprovalRequestStep"), (("approver_display", "approver_id"),))
    fill(apps.get_model("system", "ApprovalRequestStepAction"), (("approver_display", "approver_id"),))


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0004_aiknowledgechunk_aiknowledgedocument_aiprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalnodetask",
            name="actor_display",
            field=models.CharField(blank=True, default="", max_length=128, verbose_name="Actor display"),
        ),
        migrations.AddField(
            model_name="approvalnodetask",
            name="assignee_display",
            field=models.CharField(blank=True, default="", max_length=128, verbose_name="Assignee display"),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="approver_display",
            field=models.CharField(blank=True, default="", max_length=128, verbose_name="Approver display"),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="target_snapshot",
            field=models.JSONField(blank=True, default=dict, verbose_name="Target snapshot"),
        ),
        migrations.AddField(
            model_name="approvalrequeststep",
            name="approver_display",
            field=models.CharField(blank=True, default="", max_length=128, verbose_name="Approver display"),
        ),
        migrations.AddField(
            model_name="approvalrequeststepaction",
            name="approver_display",
            field=models.CharField(blank=True, default="", max_length=128, verbose_name="Approver display"),
        ),
        migrations.RunPython(backfill_display, migrations.RunPython.noop),
    ]
