# Generated by Django 6.0.8 on 2026-09-18 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0004_aiknowledgechunk_aiknowledgedocument_aiprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalnodetask",
            name="delegate_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approval_node_delegated_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Delegate from",
            ),
        ),
        migrations.AddField(
            model_name="dynamicform",
            name="is_template",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Is template"),
        ),
        migrations.AlterField(
            model_name="dynamicformsubmission",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="",
                max_length=16,
                verbose_name="Status",
            ),
        ),
    ]
