# Generated by Django 6.0.8 on 2026-09-14 01:51

import django.db.models.deletion
import json
import uuid
from django.conf import settings
from django.db import migrations, models

from common.base.utils import signer


def _clean_setting_value(setting):
    """historical model 不含 cleaned_value property，手动复刻解密 + json 解析。"""
    value = setting.value
    if setting.encrypted and value is not None:
        try:
            value = signer.decrypt(value)
        except Exception:
            return None
    if not value:
        return None
    try:
        return json.loads(value)
    except json.JSONDecodeError:
        return None


def _num(rows, key):
    value = rows.get(key)
    if value in (None, ""):
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _int(rows, key, default=None):
    value = rows.get(key)
    if value in (None, ""):
        return default
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def migrate_setting_to_profile(apps, schema_editor):
    """Setting（category=ai）历史配置齐全且档案表为空 → 搬迁为一条激活档案。

    配置不齐全（仅开开关未配凭据）时不搬迁，保持「无档案 = Setting 回落」语义。
    """
    AiProfile = apps.get_model("system", "AiProfile")
    Setting = apps.get_model("settings", "Setting")
    if AiProfile.objects.exists():
        return
    rows = {}
    for setting in Setting.objects.filter(category="ai"):
        rows[setting.name] = _clean_setting_value(setting)
    base_url = str(rows.get("AI_BASE_URL") or "").strip()
    api_key = str(rows.get("AI_API_KEY") or "").strip()
    model = str(rows.get("AI_MODEL") or "").strip()
    if not (base_url and api_key and model):
        return
    AiProfile.objects.create(
        name="默认配置",
        base_url=base_url[:256],
        api_key=signer.encrypt(api_key.encode("utf-8")).decode("utf-8"),
        model=model[:128],
        temperature=_num(rows, "AI_TEMPERATURE"),
        max_tokens=_int(rows, "AI_MAX_TOKENS"),
        top_p=_num(rows, "AI_TOP_P"),
        frequency_penalty=_num(rows, "AI_FREQUENCY_PENALTY"),
        presence_penalty=_num(rows, "AI_PRESENCE_PENALTY"),
        stop=str(rows.get("AI_STOP") or "")[:255],
        seed=_int(rows, "AI_SEED"),
        timeout=_int(rows, "AI_TIMEOUT", 60) or 60,
        max_retries=_int(rows, "AI_MAX_RETRIES", 0) or 0,
        context_limit=_int(rows, "AI_CONTEXT_LIMIT", 20) or 20,
        persona=str(rows.get("AI_PERSONA") or ""),
        is_active=True,
        remark="由历史 AI 配置自动迁移",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0004_aiknowledgechunk_aiknowledgedocument_apiapplication_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("name", models.CharField(max_length=64, unique=True, verbose_name="Profile name")),
                ("base_url", models.CharField(max_length=256, verbose_name="Base URL")),
                ("api_key", models.TextField(blank=True, default="", verbose_name="API Key")),
                ("model", models.CharField(max_length=128, verbose_name="Model")),
                ("temperature", models.FloatField(blank=True, null=True, verbose_name="Temperature")),
                ("max_tokens", models.IntegerField(blank=True, null=True, verbose_name="Max tokens")),
                ("top_p", models.FloatField(blank=True, null=True, verbose_name="Top P")),
                ("frequency_penalty", models.FloatField(blank=True, null=True, verbose_name="Frequency penalty")),
                ("presence_penalty", models.FloatField(blank=True, null=True, verbose_name="Presence penalty")),
                ("stop", models.CharField(blank=True, default="", max_length=255, verbose_name="Stop sequences")),
                ("seed", models.IntegerField(blank=True, null=True, verbose_name="Seed")),
                ("timeout", models.IntegerField(default=60, verbose_name="Timeout (seconds)")),
                ("max_retries", models.IntegerField(default=0, verbose_name="Max retries")),
                ("context_limit", models.IntegerField(default=20, verbose_name="Context messages")),
                ("persona", models.TextField(blank=True, default="", verbose_name="Persona")),
                ("is_active", models.BooleanField(db_index=True, default=False, verbose_name="Is active")),
                ("remark", models.CharField(blank=True, default="", max_length=255, verbose_name="Remark")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI profile",
                "verbose_name_plural": "AI profiles",
                "ordering": ("-is_active", "name"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)), fields=("is_active",), name="uniq_ai_profile_active"
                    )
                ],
            },
        ),
        migrations.RunPython(migrate_setting_to_profile, migrations.RunPython.noop),
    ]
