# Generated by Django 6.0.8 on 2026-09-13 20:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0004_aiknowledgechunk_apiapplication_approvalflow_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leave",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual leave"),
                            ("sick", "Sick leave"),
                            ("personal", "Personal leave"),
                            ("comp_time", "Compensatory leave"),
                            ("marriage", "Marriage leave"),
                            ("other", "Other"),
                        ],
                        default="annual",
                        max_length=32,
                        verbose_name="Leave type",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start date")),
                ("end_date", models.DateField(verbose_name="End date")),
                ("days", models.DecimalField(decimal_places=1, max_digits=5, verbose_name="Days")),
                ("reason", models.CharField(max_length=500, verbose_name="Reason")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave request",
                "verbose_name_plural": "Leave request",
                "ordering": ["-created_time"],
            },
        ),
        migrations.AddField(
            model_name="approvalinstance",
            name="biz_id",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="Business id"),
        ),
        migrations.AddField(
            model_name="approvalinstance",
            name="biz_type",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64, verbose_name="Business type"),
        ),
        migrations.AddIndex(
            model_name="approvalinstance",
            index=models.Index(fields=["biz_type", "biz_id"], name="idx_appr_inst_biz"),
        ),
        migrations.AddField(
            model_name="leave",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leaves",
                to="system.approvalinstance",
                verbose_name="Approval instance",
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddIndex(
            model_name="leave",
            index=models.Index(fields=["status", "created_time"], name="idx_leave_status_created"),
        ),
        migrations.AddIndex(
            model_name="leave",
            index=models.Index(fields=["creator", "start_date"], name="idx_leave_creator_start"),
        ),
    ]
