# Generated by Django 6.0.8 on 2026-09-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0004_datadict_exportrecord_taskexecution_usersession_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datadict",
            name="is_locked",
            field=models.BooleanField(default=False, verbose_name="Is locked"),
        ),
    ]
