# Generated by Django 6.0.8 on 2026-09-20 13:46

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0004_aiknowledgechunk_aiknowledgedocument_aiprofile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                (
                    "feature",
                    models.CharField(
                        choices=[("docs", "Document Q&A"), ("nl", "NL query"), ("action", "Action execution")],
                        db_index=True,
                        max_length=16,
                        verbose_name="Feature",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant"), ("system", "System")],
                        max_length=16,
                        verbose_name="Role",
                    ),
                ),
                ("content", models.TextField(blank=True, default="", verbose_name="Content")),
                ("reasoning", models.TextField(blank=True, default="", verbose_name="Reasoning")),
                (
                    "extra",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        verbose_name="Extra",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI chat message",
                "verbose_name_plural": "AI chat messages",
                "ordering": ("-id",),
                "indexes": [models.Index(fields=["creator", "feature", "-id"], name="ai_chat_msg_user_feat_idx")],
            },
        ),
    ]
