# Generated by Django 6.0.8 on 2026-09-10 13:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0004_approvalrequest_datadict_datamaskrule_exportrecord_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                (
                    "model",
                    models.CharField(
                        db_index=True,
                        help_text="Model label like system.userinfo",
                        max_length=128,
                        verbose_name="Target model",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Template name")),
                ("mapping", models.JSONField(blank=True, default=dict, verbose_name="Column mapping")),
                ("options", models.JSONField(blank=True, default=dict, verbose_name="Import options")),
                ("is_shared", models.BooleanField(db_index=True, default=False, verbose_name="Shared")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import template",
                "ordering": ["-created_time"],
                "indexes": [models.Index(fields=["model", "is_shared"], name="idx_import_tpl_model_shared")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("model", "name", "creator"), name="uniq_import_template_model_name_creator"
                    )
                ],
            },
        ),
    ]
