# Generated by Django 6.0.8 on 2026-09-23 15:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_display(apps, schema_editor):
    """历史审批行回填「处理人显示名快照」：用户删除/改名后轨迹仍可读。

    快照口径 = 昵称优先、缺失回落用户名（与 system.utils.approval.display 一致）。
    """
    UserInfo = apps.get_model("system", "UserInfo")
    name_map = {
        pk: (nickname or username)
        for pk, username, nickname in UserInfo.objects.values_list("pk", "username", "nickname").iterator()
    }

    def fill(model, fields):
        rows = list(model.objects.all())
        changed = []
        for row in rows:
            touched = False
            for field, source in fields:
                user_id = getattr(row, source)
                if user_id and not getattr(row, field):
                    setattr(row, field, name_map.get(user_id, "") or "")
                    touched = touched or bool(getattr(row, field))
            if touched:
                changed.append(row)
        if changed:
            model.objects.bulk_update(changed, [field for field, _source in fields], batch_size=500)

    fill(
        apps.get_model("system", "ApprovalNodeTask"),
        (("assignee_display", "assignee_id"), ("actor_display", "actor_id")),
    )
    fill(apps.get_model("system", "ApprovalRequest"), (("approver_display", "approver_id"),))
    fill(apps.get_model("system", "ApprovalRequestStep"), (("approver_display", "approver_id"),))
    fill(apps.get_model("system", "ApprovalRequestStepAction"), (("approver_display", "approver_id"),))


class Migration(migrations.Migration):
    replaces = [
        ("system", "0005_u1_approval_display_snapshot"),
        ("system", "0006_ai_profile_capabilities_and_usage"),
        ("system", "0007_task_center_revoked_status"),
        ("system", "0008_tag_center"),
        ("system", "0009_approvalflownode_cc_users_approvalinstance_cc_users_and_more"),
        ("system", "0010_savedlistview"),
        ("system", "0011_userinfo_date_expired_userinfo_invite_status_and_more"),
        ("system", "0012_task_progress_stage"),
        ("system", "0013_ai_usage_track"),
    ]

    dependencies = [
        ("system", "0004_aiknowledgechunk_aiknowledgedocument_aiprofile_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalnodetask",
            name="actor_display",
            field=models.CharField(blank=True, default="", max_length=128, verbose_name="Actor display"),
        ),
        migrations.AddField(
            model_name="approvalnodetask",
            name="assignee_display",
            field=models.CharField(blank=True, default="", max_length=128, verbose_name="Assignee display"),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="approver_display",
            field=models.CharField(blank=True, default="", max_length=128, verbose_name="Approver display"),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="target_snapshot",
            field=models.JSONField(blank=True, default=dict, verbose_name="Target snapshot"),
        ),
        migrations.AddField(
            model_name="approvalrequeststep",
            name="approver_display",
            field=models.CharField(blank=True, default="", max_length=128, verbose_name="Approver display"),
        ),
        migrations.AddField(
            model_name="approvalrequeststepaction",
            name="approver_display",
            field=models.CharField(blank=True, default="", max_length=128, verbose_name="Approver display"),
        ),
        migrations.RunPython(backfill_display, migrations.RunPython.noop),
        migrations.CreateModel(
            name="AiUsageRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("docs", "Document Q&A"),
                            ("chat", "Chat"),
                            ("nl", "NL query"),
                            ("action", "Action execution"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="Feature",
                    ),
                ),
                ("profile_name", models.CharField(blank=True, default="", max_length=64, verbose_name="Profile")),
                ("model", models.CharField(blank=True, default="", max_length=128, verbose_name="Model")),
                ("tokens_in", models.IntegerField(default=0, verbose_name="Tokens in")),
                ("tokens_out", models.IntegerField(default=0, verbose_name="Tokens out")),
                ("tokens_total", models.IntegerField(default=0, verbose_name="Tokens total")),
                ("duration_ms", models.IntegerField(default=0, verbose_name="Duration (ms)")),
                ("ok", models.BooleanField(db_index=True, default=True, verbose_name="Success")),
                ("detail", models.CharField(blank=True, default="", max_length=255, verbose_name="Detail")),
            ],
            options={
                "verbose_name": "AI usage record",
                "verbose_name_plural": "AI usage records",
                "ordering": ("-created_time",),
            },
        ),
        migrations.RemoveConstraint(
            model_name="aiprofile",
            name="uniq_ai_profile_active",
        ),
        migrations.AddField(
            model_name="aiprofile",
            name="capabilities",
            field=models.JSONField(blank=True, default=dict, verbose_name="Capabilities"),
        ),
        migrations.AddField(
            model_name="aiprofile",
            name="probed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Probed at"),
        ),
        migrations.AddField(
            model_name="aiprofile",
            name="purpose",
            field=models.CharField(
                choices=[("chat", "Chat / Q&A"), ("structured", "Structured output")],
                db_index=True,
                default="chat",
                max_length=16,
                verbose_name="Purpose",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("purpose", "is_active"),
                name="uniq_ai_profile_purpose_active",
            ),
        ),
        migrations.AddField(
            model_name="aiusagerecord",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="aiusagerecord",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="aiusagerecord",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagerecord",
            index=models.Index(fields=["creator", "-created_time"], name="ai_usage_user_time_idx"),
        ),
        migrations.AddIndex(
            model_name="aiusagerecord",
            index=models.Index(fields=["feature", "-created_time"], name="ai_usage_feat_time_idx"),
        ),
        migrations.AlterField(
            model_name="exportrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Waiting"),
                    ("RUNNING", "Running"),
                    ("SUCCESS", "Success"),
                    ("FAILURE", "Failure"),
                    ("REVOKED", "Cancelled"),
                ],
                db_index=True,
                default="PENDING",
                max_length=16,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="importrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Waiting"),
                    ("RUNNING", "Running"),
                    ("SUCCESS", "Success"),
                    ("FAILURE", "Failure"),
                    ("REVOKED", "Cancelled"),
                ],
                db_index=True,
                default="PENDING",
                max_length=16,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("name", models.CharField(max_length=64, unique=True, verbose_name="Tag name")),
                ("color", models.CharField(blank=True, default="", max_length=16, verbose_name="Color")),
                ("builtin", models.BooleanField(db_index=True, default=False, verbose_name="Builtin")),
                ("remark", models.CharField(blank=True, default="", max_length=255, verbose_name="Remark")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="TaggedItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("object_id", models.CharField(db_index=True, max_length=64, verbose_name="Object id")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content type",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="system.tag",
                        verbose_name="Tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tagged item",
                "verbose_name_plural": "Tagged items",
                "ordering": ("-created_time",),
                "indexes": [models.Index(fields=["content_type", "object_id"], name="tagged_item_target_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id", "tag"), name="uniq_tagged_item_content_object_tag"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="approvalflownode",
            name="cc_users",
            field=models.JSONField(blank=True, default=list, verbose_name="CC users"),
        ),
        migrations.AddField(
            model_name="approvalinstance",
            name="cc_users",
            field=models.ManyToManyField(
                blank=True, related_name="approval_cc_instances", to=settings.AUTH_USER_MODEL, verbose_name="CC users"
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="allowed_mfa_types",
            field=models.JSONField(blank=True, default=list, verbose_name="Allowed MFA types"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="must_change_password",
            field=models.BooleanField(default=False, verbose_name="Must change password"),
        ),
        migrations.AddField(
            model_name="userloginlog",
            name="policy_result",
            field=models.CharField(blank=True, default="", max_length=128, verbose_name="Policy result"),
        ),
        migrations.AddField(
            model_name="userrole",
            name="allowed_mfa_types",
            field=models.JSONField(blank=True, default=list, verbose_name="Allowed MFA types"),
        ),
        migrations.AddField(
            model_name="userrole",
            name="mfa_required",
            field=models.BooleanField(default=False, verbose_name="MFA required"),
        ),
        migrations.CreateModel(
            name="LoginAccessPolicy",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64, verbose_name="Policy name")),
                ("priority", models.IntegerField(db_index=True, default=100, verbose_name="Priority")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Is active")),
                (
                    "target_type",
                    models.CharField(
                        choices=[("all", "All users"), ("user", "Specified users"), ("role", "Specified roles")],
                        default="all",
                        max_length=8,
                        verbose_name="Target type",
                    ),
                ),
                ("target_value", models.CharField(blank=True, default="", max_length=512, verbose_name="Target value")),
                ("weekdays", models.JSONField(blank=True, default=list, verbose_name="Weekdays")),
                ("start_time", models.TimeField(blank=True, null=True, verbose_name="Start time")),
                ("end_time", models.TimeField(blank=True, null=True, verbose_name="End time")),
                ("ip_ranges", models.TextField(blank=True, default="", verbose_name="IP ranges")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("accept", "Accept"),
                            ("reject", "Reject"),
                            ("require_mfa", "Require MFA"),
                            ("record", "Record only"),
                        ],
                        default="reject",
                        max_length=16,
                        verbose_name="Action",
                    ),
                ),
                ("remark", models.CharField(blank=True, default="", max_length=255, verbose_name="Remark")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Login access policy",
                "verbose_name_plural": "Login access policy",
                "ordering": ["priority", "created_time"],
            },
        ),
        migrations.CreateModel(
            name="UserPasskey",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("credential_id", models.CharField(max_length=512, unique=True, verbose_name="Credential id")),
                ("public_key", models.BinaryField(verbose_name="Public key")),
                ("sign_count", models.IntegerField(default=0, verbose_name="Sign count")),
                ("name", models.CharField(blank=True, default="", max_length=64, verbose_name="Device name")),
                ("aaguid", models.CharField(blank=True, default="", max_length=64, verbose_name="AAGUID")),
                ("backed_up", models.BooleanField(default=False, verbose_name="Backed up")),
                ("last_used_at", models.DateTimeField(blank=True, null=True, verbose_name="Last used at")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkeys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User passkey",
                "verbose_name_plural": "User passkey",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="AccountRisk",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_display", models.CharField(blank=True, default="", max_length=128, verbose_name="User display")),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            ("password_expired", "Password expired"),
                            ("password_stale", "Password not changed for a long time"),
                            ("login_stale", "No login for a long time"),
                            ("never_logged_in", "Never logged in"),
                            ("superuser_no_mfa", "Admin without MFA"),
                            ("superuser_count", "Abnormal superuser count"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Risk type",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        default="medium",
                        max_length=8,
                        verbose_name="Level",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("resolved", "Resolved"), ("ignored", "Ignored")],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("detail", models.JSONField(blank=True, default=dict, verbose_name="Detail")),
                ("handled_at", models.DateTimeField(blank=True, null=True, verbose_name="Handled at")),
                ("remark", models.CharField(blank=True, default="", max_length=255, verbose_name="Remark")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_account_risks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Handled by",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_risks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account risk",
                "verbose_name_plural": "Account risk",
                "ordering": ["-created_time"],
                "indexes": [
                    models.Index(fields=["status", "level"], name="idx_account_risk_status_level"),
                    models.Index(fields=["risk_type", "created_time"], name="idx_account_risk_type_created"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "risk_type"), name="uniq_account_risk_user_type")
                ],
            },
        ),
        migrations.CreateModel(
            name="ApprovalInstanceComment",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("content", models.TextField(max_length=2000, verbose_name="Content")),
                (
                    "author_display",
                    models.CharField(blank=True, default="", max_length=128, verbose_name="Author display"),
                ),
                ("mentions", models.JSONField(blank=True, default=list, verbose_name="Mentions")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="system.approvalinstance",
                        verbose_name="Instance",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval instance comment",
                "verbose_name_plural": "Approval instance comment",
                "ordering": ["created_time"],
                "indexes": [models.Index(fields=["instance", "created_time"], name="idx_appr_comment_inst_created")],
            },
        ),
        migrations.CreateModel(
            name="FileAccessLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("filename", models.CharField(blank=True, default="", max_length=255, verbose_name="Filename")),
                ("user_display", models.CharField(blank=True, default="", max_length=128, verbose_name="User display")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("download", "Download"),
                            ("preview", "Preview"),
                            ("delete", "Delete"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="Action",
                    ),
                ),
                ("ipaddress", models.CharField(blank=True, default="", max_length=64, verbose_name="IP address")),
                ("result", models.BooleanField(default=True, verbose_name="Result")),
                ("detail", models.CharField(blank=True, default="", max_length=255, verbose_name="Detail")),
                ("created_time", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created time")),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to="system.uploadfile",
                        verbose_name="File",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="file_access_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "File access log",
                "verbose_name_plural": "File access log",
                "ordering": ["-created_time"],
                "indexes": [
                    models.Index(fields=["file", "created_time"], name="idx_file_log_file_created"),
                    models.Index(fields=["user", "action"], name="idx_file_log_user_action"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SavedListView",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("page_key", models.CharField(db_index=True, max_length=128, verbose_name="Page key")),
                ("name", models.CharField(max_length=64, verbose_name="View name")),
                ("conditions", models.JSONField(blank=True, default=dict, verbose_name="Conditions")),
                ("ordering", models.CharField(blank=True, default="", max_length=64, verbose_name="Ordering")),
                ("is_default", models.BooleanField(default=False, verbose_name="Is default")),
                ("is_shared", models.BooleanField(default=False, verbose_name="Is shared")),
                ("remark", models.CharField(blank=True, default="", max_length=255, verbose_name="Remark")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_list_views",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved list view",
                "verbose_name_plural": "Saved list view",
                "ordering": ["page_key", "-is_default", "created_time"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "page_key", "name"), name="uniq_saved_view_owner_page_name"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="userinfo",
            name="date_expired",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Account expiry"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="invite_status",
            field=models.CharField(
                blank=True,
                choices=[("pending", "Pending acceptance"), ("accepted", "Accepted")],
                default="",
                max_length=16,
                verbose_name="Invite status",
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="invited_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Invited at"),
        ),
        migrations.AddField(
            model_name="exportrecord",
            name="stage",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="Progress stage"),
        ),
        migrations.AddField(
            model_name="importrecord",
            name="stage",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="Progress stage"),
        ),
        migrations.AddField(
            model_name="aiusagerecord",
            name="track",
            field=models.CharField(blank=True, default="", max_length=16, verbose_name="Track"),
        ),
    ]
