# Generated by Django 6.0.8 on 2026-09-15 13:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0004_aiknowledgechunk_aiknowledgedocument_aiprofile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalDelegation",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField(verbose_name="Start time")),
                ("end_time", models.DateTimeField(verbose_name="End time")),
                ("flow_codes", models.JSONField(blank=True, default=list, verbose_name="Flow codes")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                ("remark", models.CharField(blank=True, max_length=255, null=True, verbose_name="Remark")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "delegate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_delegations_as_delegate",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Delegate",
                    ),
                ),
                (
                    "delegator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_delegations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Delegator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval delegation",
                "verbose_name_plural": "Approval delegation",
                "ordering": ["-created_time"],
                "indexes": [
                    models.Index(fields=["delegator", "is_active"], name="idx_appr_deleg_delegator"),
                    models.Index(fields=["delegate", "is_active"], name="idx_appr_deleg_delegate"),
                ],
            },
        ),
    ]
