# Generated by Django 6.0.8 on 2026-09-11 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0005_import_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userloginlog",
            name="login_type",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Username and password"),
                    (1, "SMS verification code"),
                    (2, "Email verification code"),
                    (4, "Wechat scan code"),
                    (5, "Third-party OAuth"),
                    (8, "Websocket"),
                    (9, "Unknown"),
                ],
                default=0,
                verbose_name="Login type",
            ),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="login_type",
            field=models.IntegerField(
                choices=[
                    (0, "Username and password"),
                    (1, "SMS verification code"),
                    (2, "Email verification code"),
                    (4, "Wechat scan code"),
                    (5, "Third-party OAuth"),
                    (8, "Websocket"),
                    (9, "Unknown"),
                ],
                default=9,
                verbose_name="Login type",
            ),
        ),
        migrations.CreateModel(
            name="UserOAuthBinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("provider", models.CharField(db_index=True, max_length=64, verbose_name="Provider")),
                (
                    "subject",
                    models.CharField(help_text="IdP 侧唯一标识（sub）", max_length=255, verbose_name="Subject"),
                ),
                (
                    "profile",
                    models.JSONField(
                        blank=True, default=dict, help_text="IdP 返回的头像/昵称/邮箱等只读快照", verbose_name="Profile"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_bindings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth binding",
                "verbose_name_plural": "OAuth bindings",
                "ordering": ["-created_time"],
                "constraints": [
                    models.UniqueConstraint(fields=("provider", "subject"), name="uniq_oauth_provider_subject")
                ],
            },
        ),
    ]
