# Generated by Django 6.0.8 on 2026-09-22 10:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0005_u1_approval_display_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiUsageRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("docs", "Document Q&A"),
                            ("chat", "Chat"),
                            ("nl", "NL query"),
                            ("action", "Action execution"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="Feature",
                    ),
                ),
                ("profile_name", models.CharField(blank=True, default="", max_length=64, verbose_name="Profile")),
                ("model", models.CharField(blank=True, default="", max_length=128, verbose_name="Model")),
                ("tokens_in", models.IntegerField(default=0, verbose_name="Tokens in")),
                ("tokens_out", models.IntegerField(default=0, verbose_name="Tokens out")),
                ("tokens_total", models.IntegerField(default=0, verbose_name="Tokens total")),
                ("duration_ms", models.IntegerField(default=0, verbose_name="Duration (ms)")),
                ("ok", models.BooleanField(db_index=True, default=True, verbose_name="Success")),
                ("detail", models.CharField(blank=True, default="", max_length=255, verbose_name="Detail")),
            ],
            options={
                "verbose_name": "AI usage record",
                "verbose_name_plural": "AI usage records",
                "ordering": ("-created_time",),
            },
        ),
        migrations.RemoveConstraint(
            model_name="aiprofile",
            name="uniq_ai_profile_active",
        ),
        migrations.AddField(
            model_name="aiprofile",
            name="capabilities",
            field=models.JSONField(blank=True, default=dict, verbose_name="Capabilities"),
        ),
        migrations.AddField(
            model_name="aiprofile",
            name="probed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Probed at"),
        ),
        migrations.AddField(
            model_name="aiprofile",
            name="purpose",
            field=models.CharField(
                choices=[("chat", "Chat / Q&A"), ("structured", "Structured output")],
                db_index=True,
                default="chat",
                max_length=16,
                verbose_name="Purpose",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("purpose", "is_active"),
                name="uniq_ai_profile_purpose_active",
            ),
        ),
        migrations.AddField(
            model_name="aiusagerecord",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="aiusagerecord",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="aiusagerecord",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagerecord",
            index=models.Index(fields=["creator", "-created_time"], name="ai_usage_user_time_idx"),
        ),
        migrations.AddIndex(
            model_name="aiusagerecord",
            index=models.Index(fields=["feature", "-created_time"], name="ai_usage_feat_time_idx"),
        ),
    ]
