# Generated by Django 6.0.8 on 2026-09-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0005_approval_delegation"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="cron_expression",
            field=models.CharField(
                blank=True,
                default="",
                help_text="5-field cron, takes precedence",
                max_length=64,
                verbose_name="Cron expression",
            ),
        ),
    ]
