# Generated by Django 6.0.8 on 2026-09-09 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0005_datadict_is_locked"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportRecord",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="File name")),
                ("module", models.CharField(blank=True, max_length=128, null=True, verbose_name="Target module")),
                ("path", models.CharField(blank=True, max_length=255, null=True, verbose_name="Source path")),
                (
                    "action",
                    models.CharField(
                        choices=[("create", "Create"), ("update", "Update")],
                        db_index=True,
                        default="create",
                        max_length=16,
                        verbose_name="Import action",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Waiting"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("total", models.IntegerField(blank=True, null=True, verbose_name="Total rows")),
                ("success_rows", models.IntegerField(default=0, verbose_name="Success rows")),
                ("failed_rows", models.IntegerField(default=0, verbose_name="Failed rows")),
                ("error", models.TextField(blank=True, null=True, verbose_name="Error message")),
                ("params", models.JSONField(blank=True, default=dict, verbose_name="Import params")),
            ],
            options={
                "verbose_name": "Import record",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="PersonalAccessToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("name", models.CharField(max_length=128, verbose_name="Token name")),
                ("token_hash", models.CharField(max_length=64, unique=True, verbose_name="Token hash")),
                ("token_prefix", models.CharField(max_length=16, verbose_name="Token prefix")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                ("expired_at", models.DateTimeField(blank=True, null=True, verbose_name="Expired at")),
                ("last_used_time", models.DateTimeField(blank=True, null=True, verbose_name="Last used time")),
            ],
            options={
                "verbose_name": "Personal access token",
                "verbose_name_plural": "Personal access token",
                "ordering": ("-created_time",),
            },
        ),
        migrations.AddField(
            model_name="operationlog",
            name="object_pk",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="Object pk"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["module", "object_pk"], name="idx_oplog_module_objectpk"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["path"], name="idx_oplog_path"),
        ),
        migrations.AddField(
            model_name="importrecord",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="importrecord",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="importrecord",
            name="error_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="import_error_reports",
                to="system.uploadfile",
                verbose_name="Error report",
            ),
        ),
        migrations.AddField(
            model_name="importrecord",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddField(
            model_name="importrecord",
            name="source_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="import_sources",
                to="system.uploadfile",
                verbose_name="Source file",
            ),
        ),
        migrations.AddField(
            model_name="personalaccesstoken",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="personalaccesstoken",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="personalaccesstoken",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddIndex(
            model_name="importrecord",
            index=models.Index(fields=["status", "created_time"], name="idx_import_status_created"),
        ),
        migrations.AddIndex(
            model_name="personalaccesstoken",
            index=models.Index(fields=["creator", "created_time"], name="idx_pat_creator_created"),
        ),
        migrations.AddIndex(
            model_name="personalaccesstoken",
            index=models.Index(fields=["expired_at"], name="idx_pat_expired_at"),
        ),
    ]
