# Generated by Django 6.0.8 on 2026-09-13 20:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0005_leave_approvalinstance_biz_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiKnowledgeDocument",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                (
                    "source_type",
                    models.CharField(
                        choices=[("repo", "Repository docs"), ("upload", "Uploaded document")],
                        db_index=True,
                        default="repo",
                        max_length=16,
                        verbose_name="Source type",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True, verbose_name="Storage path")),
                ("title", models.CharField(blank=True, default="", max_length=255, verbose_name="Title")),
                ("content", models.TextField(blank=True, default="", verbose_name="Content")),
                ("content_hash", models.CharField(blank=True, default="", max_length=64, verbose_name="Content hash")),
                ("chunk_count", models.IntegerField(default=0, verbose_name="Chunk count")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Active")),
                ("synced_at", models.DateTimeField(auto_now=True, verbose_name="Synced at")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI knowledge document",
                "verbose_name_plural": "AI knowledge documents",
                "ordering": ("-synced_at",),
            },
        ),
    ]
