# Generated by Django 6.0.8 on 2026-09-16 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0006_report_cron_expression"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrequest",
            name="auto_completed",
            field=models.BooleanField(default=False, verbose_name="Auto completed"),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="payload",
            field=models.JSONField(blank=True, default=dict, verbose_name="Request payload"),
        ),
        migrations.AddField(
            model_name="dynamicform",
            name="approval_flow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bound_forms",
                to="system.approvalflow",
                verbose_name="Approval flow",
            ),
        ),
        migrations.AddField(
            model_name="dynamicformsubmission",
            name="instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dform_submissions",
                to="system.approvalinstance",
                verbose_name="Approval instance",
            ),
        ),
        migrations.AddField(
            model_name="dynamicformsubmission",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="",
                max_length=16,
                verbose_name="Status",
            ),
        ),
    ]
