# Generated by Django 6.0.8 on 2026-09-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0006_ai_profile_capabilities_and_usage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Waiting"),
                    ("RUNNING", "Running"),
                    ("SUCCESS", "Success"),
                    ("FAILURE", "Failure"),
                    ("REVOKED", "Cancelled"),
                ],
                db_index=True,
                default="PENDING",
                max_length=16,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="importrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Waiting"),
                    ("RUNNING", "Running"),
                    ("SUCCESS", "Success"),
                    ("FAILURE", "Failure"),
                    ("REVOKED", "Cancelled"),
                ],
                db_index=True,
                default="PENDING",
                max_length=16,
                verbose_name="Status",
            ),
        ),
    ]
