# Generated by Django 6.0.8 on 2026-09-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0006_retire_operation_log_delete_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiapplication",
            name="daily_quota_hard",
            field=models.BooleanField(
                default=False,
                help_text="Reject requests with 429 once the daily quota is exceeded (off = warn only)",
                verbose_name="Enforce daily quota",
            ),
        ),
    ]
