# Generated by Django 6.0.8 on 2026-09-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0006_importrecord_personalaccesstoken_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportrecord",
            name="progress",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Progress"),
        ),
        migrations.AddField(
            model_name="importrecord",
            name="progress",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Progress"),
        ),
    ]
