# Generated by Django 6.0.8 on 2026-09-11 10:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0006_alter_userloginlog_login_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalFlow",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64, verbose_name="Flow name")),
                ("code", models.CharField(max_length=64, unique=True, verbose_name="Flow code")),
                ("form_schema", models.JSONField(blank=True, default=list, verbose_name="Form schema")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Is active")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval flow",
                "verbose_name_plural": "Approval flow",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalFlowNode",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64, verbose_name="Node name")),
                ("order", models.IntegerField(default=1, verbose_name="Node order")),
                (
                    "approve_type",
                    models.CharField(
                        choices=[("OR", "Any approver"), ("AND", "All approvers")],
                        default="OR",
                        max_length=4,
                        verbose_name="Approve type",
                    ),
                ),
                (
                    "assignee_type",
                    models.CharField(
                        choices=[("role", "Role"), ("user", "User"), ("leader", "Leader"), ("field", "Form field")],
                        default="role",
                        max_length=8,
                        verbose_name="Assignee type",
                    ),
                ),
                (
                    "assignee_value",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Assignee value"),
                ),
                ("condition", models.JSONField(blank=True, default=dict, verbose_name="Condition")),
                ("timeout_hours", models.IntegerField(default=0, verbose_name="Timeout hours")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="system.approvalflow",
                        verbose_name="Flow",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval flow node",
                "verbose_name_plural": "Approval flow node",
                "ordering": ["order", "created_time"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalInstance",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("flow_name", models.CharField(max_length=64, verbose_name="Flow name")),
                ("title", models.CharField(max_length=128, verbose_name="Title")),
                ("form_data", models.JSONField(blank=True, default=dict, verbose_name="Form data")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="Finished at")),
                ("reason", models.CharField(blank=True, max_length=255, null=True, verbose_name="Reason")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "current_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="system.approvalflownode",
                        verbose_name="Current node",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="system.approvalflow",
                        verbose_name="Flow",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval instance",
                "verbose_name_plural": "Approval instance",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalNodeTask",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("node_name", models.CharField(max_length=64, verbose_name="Node name")),
                ("node_order", models.IntegerField(default=1, verbose_name="Node order")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=255, null=True, verbose_name="Comment")),
                ("acted_at", models.DateTimeField(blank=True, null=True, verbose_name="Acted at")),
                ("is_added", models.BooleanField(default=False, verbose_name="Added by counter-sign")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_node_acted_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_node_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assignee",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="system.approvalinstance",
                        verbose_name="Instance",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="system.approvalflownode",
                        verbose_name="Node",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval node task",
                "verbose_name_plural": "Approval node task",
                "ordering": ["node_order", "created_time"],
            },
        ),
        migrations.AddConstraint(
            model_name="approvalflownode",
            constraint=models.UniqueConstraint(fields=("flow", "order"), name="uniq_approval_flow_node_order"),
        ),
        migrations.AddIndex(
            model_name="approvalinstance",
            index=models.Index(fields=["status", "created_time"], name="idx_appr_inst_status_created"),
        ),
        migrations.AddIndex(
            model_name="approvalinstance",
            index=models.Index(fields=["creator", "created_time"], name="idx_appr_inst_creator_created"),
        ),
        migrations.AddIndex(
            model_name="approvalnodetask",
            index=models.Index(fields=["assignee", "status"], name="idx_appr_task_assignee_status"),
        ),
        migrations.AddIndex(
            model_name="approvalnodetask",
            index=models.Index(fields=["instance", "node_order"], name="idx_appr_task_inst_order"),
        ),
    ]
