# Generated by Django 6.0.8 on 2026-09-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0007_approvalrequest_auto_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menumeta",
            name="watermark",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, pages under this menu always show the site watermark, regardless of the basic-settings path list",
                verbose_name="Page watermark",
            ),
        ),
    ]
