# Generated by Django 6.0.8 on 2026-09-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0007_approvalflow_approvalflownode_approvalinstance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationlog",
            name="auth_type",
            field=models.CharField(
                blank=True,
                choices=[("jwt", "JWT"), ("pat", "Personal access token"), ("scim", "SCIM directory sync")],
                max_length=16,
                null=True,
                verbose_name="Auth type",
            ),
        ),
    ]
