# Generated by Django 6.0.8 on 2026-09-09 23:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0007_exportrecord_progress_importrecord_progress"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataMaskRule",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                (
                    "model",
                    models.CharField(
                        help_text="Model label like system.userinfo", max_length=128, verbose_name="Model"
                    ),
                ),
                ("field", models.CharField(max_length=64, verbose_name="Field")),
                (
                    "mask_type",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("idcard", "ID card"),
                            ("email", "Email"),
                            ("name", "Name"),
                            ("bankcard", "Bank card"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=16,
                        verbose_name="Mask type",
                    ),
                ),
                ("keep_head", models.PositiveSmallIntegerField(default=3, verbose_name="Keep head")),
                ("keep_tail", models.PositiveSmallIntegerField(default=2, verbose_name="Keep tail")),
                ("mask_char", models.CharField(default="*", max_length=4, verbose_name="Mask char")),
                ("pattern", models.CharField(blank=True, max_length=255, null=True, verbose_name="Custom pattern")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                ("sort", models.IntegerField(default=0, verbose_name="Sort")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True, help_text="Empty = all non-superuser", to="system.userrole", verbose_name="Roles"
                    ),
                ),
            ],
            options={
                "verbose_name": "Data mask rule",
                "ordering": ("sort", "created_time"),
                "indexes": [models.Index(fields=["model", "field"], name="idx_datamask_model_field")],
            },
        ),
    ]
