# Generated by Django 6.0.8 on 2026-09-29 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0007_apiapplication_daily_quota_hard"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("filename", models.CharField(max_length=255, verbose_name="Filename")),
                ("filesize", models.BigIntegerField(verbose_name="Filesize")),
                ("total_chunks", models.IntegerField(verbose_name="Total chunks")),
                ("chunk_size", models.IntegerField(verbose_name="Chunk size")),
                ("md5sum", models.CharField(blank=True, default="", max_length=36, verbose_name="File md5sum")),
                ("mime_type", models.CharField(blank=True, default="", max_length=255, verbose_name="Mime type")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed"), ("aborted", "Aborted")],
                        default="pending",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upload_sessions",
                        to="system.uploadfile",
                        verbose_name="Upload file",
                    ),
                ),
            ],
            options={
                "verbose_name": "Upload session",
                "verbose_name_plural": "Upload session",
            },
        ),
        migrations.CreateModel(
            name="UploadSessionPart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("index", models.IntegerField(verbose_name="Chunk index")),
                ("size", models.IntegerField(verbose_name="Chunk size")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="system.uploadsession",
                        verbose_name="Upload session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Upload session part",
                "verbose_name_plural": "Upload session part",
            },
        ),
        migrations.AddIndex(
            model_name="uploadsession",
            index=models.Index(fields=["creator", "filename", "filesize", "status"], name="idx_upsess_resume"),
        ),
        migrations.AddIndex(
            model_name="uploadsession",
            index=models.Index(fields=["status", "created_time"], name="idx_upsess_status_created"),
        ),
        migrations.AddConstraint(
            model_name="uploadsessionpart",
            constraint=models.UniqueConstraint(fields=("session", "index"), name="uniq_uploadsession_part_index"),
        ),
    ]
