# Generated by Django 6.0.8 on 2026-09-30 16:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0008_upload_chunk_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeptManagerAssignment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, verbose_name="Created time")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned by",
                    ),
                ),
                (
                    "dept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager_assignments",
                        to="system.deptinfo",
                        verbose_name="Department",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Manager",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department manager assignment",
                "verbose_name_plural": "Department manager assignment",
                "ordering": ("-created_time",),
                "unique_together": {("dept", "user")},
            },
        ),
        migrations.AddField(
            model_name="deptinfo",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users appointed to manage this department and its descendants",
                related_name="managed_depts",
                through="system.DeptManagerAssignment",
                through_fields=("dept", "user"),
                to=settings.AUTH_USER_MODEL,
                verbose_name="Department managers",
            ),
        ),
    ]
