# Generated by Django 6.0.8 on 2026-09-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0008_menu_meta_watermark"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="im_recipients",
            field=models.JSONField(
                blank=True, default=list, help_text="User pks receiving IM messages", verbose_name="IM recipients"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="notify_channels",
            field=models.JSONField(
                blank=True, default=list, help_text="Delivery channels", verbose_name="Notify channels"
            ),
        ),
    ]
