# Generated by Django 6.0.8 on 2026-09-10 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0008_datamaskrule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="systemconfig",
            options={
                "ordering": ["created_time"],
                "verbose_name": "System config",
                "verbose_name_plural": "System config",
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("module", models.CharField(blank=True, max_length=64, null=True, verbose_name="Module")),
                ("method", models.CharField(max_length=8, verbose_name="Method")),
                ("path", models.CharField(max_length=400, verbose_name="URL path")),
                ("object_pk", models.CharField(blank=True, max_length=64, null=True, verbose_name="Object pk")),
                ("params", models.JSONField(blank=True, default=dict, verbose_name="Request params")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True, verbose_name="Approved at")),
                ("expired_at", models.DateTimeField(blank=True, null=True, verbose_name="Token expired at")),
                ("consume_time", models.DateTimeField(blank=True, null=True, verbose_name="Consume time")),
                ("reason", models.CharField(blank=True, max_length=255, null=True, verbose_name="Reason")),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approver",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval request",
                "verbose_name_plural": "Approval request",
                "ordering": ["-created_time"],
                "indexes": [
                    models.Index(fields=["status", "created_time"], name="idx_approval_status_created"),
                    models.Index(fields=["creator", "created_time"], name="idx_approval_creator_created"),
                ],
            },
        ),
    ]
