# Generated by Django 6.0.8 on 2026-09-22 12:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0008_tag_center"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalflownode",
            name="cc_users",
            field=models.JSONField(blank=True, default=list, verbose_name="CC users"),
        ),
        migrations.AddField(
            model_name="approvalinstance",
            name="cc_users",
            field=models.ManyToManyField(
                blank=True, related_name="approval_cc_instances", to=settings.AUTH_USER_MODEL, verbose_name="CC users"
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="allowed_mfa_types",
            field=models.JSONField(blank=True, default=list, verbose_name="Allowed MFA types"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="must_change_password",
            field=models.BooleanField(default=False, verbose_name="Must change password"),
        ),
        migrations.AddField(
            model_name="userloginlog",
            name="policy_result",
            field=models.CharField(blank=True, default="", max_length=128, verbose_name="Policy result"),
        ),
        migrations.AddField(
            model_name="userrole",
            name="allowed_mfa_types",
            field=models.JSONField(blank=True, default=list, verbose_name="Allowed MFA types"),
        ),
        migrations.AddField(
            model_name="userrole",
            name="mfa_required",
            field=models.BooleanField(default=False, verbose_name="MFA required"),
        ),
        migrations.CreateModel(
            name="LoginAccessPolicy",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64, verbose_name="Policy name")),
                ("priority", models.IntegerField(db_index=True, default=100, verbose_name="Priority")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Is active")),
                (
                    "target_type",
                    models.CharField(
                        choices=[("all", "All users"), ("user", "Specified users"), ("role", "Specified roles")],
                        default="all",
                        max_length=8,
                        verbose_name="Target type",
                    ),
                ),
                ("target_value", models.CharField(blank=True, default="", max_length=512, verbose_name="Target value")),
                ("weekdays", models.JSONField(blank=True, default=list, verbose_name="Weekdays")),
                ("start_time", models.TimeField(blank=True, null=True, verbose_name="Start time")),
                ("end_time", models.TimeField(blank=True, null=True, verbose_name="End time")),
                ("ip_ranges", models.TextField(blank=True, default="", verbose_name="IP ranges")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("accept", "Accept"),
                            ("reject", "Reject"),
                            ("require_mfa", "Require MFA"),
                            ("record", "Record only"),
                        ],
                        default="reject",
                        max_length=16,
                        verbose_name="Action",
                    ),
                ),
                ("remark", models.CharField(blank=True, default="", max_length=255, verbose_name="Remark")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Login access policy",
                "verbose_name_plural": "Login access policy",
                "ordering": ["priority", "created_time"],
            },
        ),
        migrations.CreateModel(
            name="UserPasskey",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("credential_id", models.CharField(max_length=512, unique=True, verbose_name="Credential id")),
                ("public_key", models.BinaryField(verbose_name="Public key")),
                ("sign_count", models.IntegerField(default=0, verbose_name="Sign count")),
                ("name", models.CharField(blank=True, default="", max_length=64, verbose_name="Device name")),
                ("aaguid", models.CharField(blank=True, default="", max_length=64, verbose_name="AAGUID")),
                ("backed_up", models.BooleanField(default=False, verbose_name="Backed up")),
                ("last_used_at", models.DateTimeField(blank=True, null=True, verbose_name="Last used at")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkeys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User passkey",
                "verbose_name_plural": "User passkey",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="AccountRisk",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_display", models.CharField(blank=True, default="", max_length=128, verbose_name="User display")),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            ("password_expired", "Password expired"),
                            ("password_stale", "Password not changed for a long time"),
                            ("login_stale", "No login for a long time"),
                            ("never_logged_in", "Never logged in"),
                            ("superuser_no_mfa", "Admin without MFA"),
                            ("superuser_count", "Abnormal superuser count"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Risk type",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        default="medium",
                        max_length=8,
                        verbose_name="Level",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("resolved", "Resolved"), ("ignored", "Ignored")],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("detail", models.JSONField(blank=True, default=dict, verbose_name="Detail")),
                ("handled_at", models.DateTimeField(blank=True, null=True, verbose_name="Handled at")),
                ("remark", models.CharField(blank=True, default="", max_length=255, verbose_name="Remark")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_account_risks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Handled by",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_risks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account risk",
                "verbose_name_plural": "Account risk",
                "ordering": ["-created_time"],
                "indexes": [
                    models.Index(fields=["status", "level"], name="idx_account_risk_status_level"),
                    models.Index(fields=["risk_type", "created_time"], name="idx_account_risk_type_created"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "risk_type"), name="uniq_account_risk_user_type")
                ],
            },
        ),
        migrations.CreateModel(
            name="ApprovalInstanceComment",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("content", models.TextField(max_length=2000, verbose_name="Content")),
                (
                    "author_display",
                    models.CharField(blank=True, default="", max_length=128, verbose_name="Author display"),
                ),
                ("mentions", models.JSONField(blank=True, default=list, verbose_name="Mentions")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="system.approvalinstance",
                        verbose_name="Instance",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval instance comment",
                "verbose_name_plural": "Approval instance comment",
                "ordering": ["created_time"],
                "indexes": [models.Index(fields=["instance", "created_time"], name="idx_appr_comment_inst_created")],
            },
        ),
        migrations.CreateModel(
            name="FileAccessLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("filename", models.CharField(blank=True, default="", max_length=255, verbose_name="Filename")),
                ("user_display", models.CharField(blank=True, default="", max_length=128, verbose_name="User display")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("download", "Download"),
                            ("preview", "Preview"),
                            ("delete", "Delete"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="Action",
                    ),
                ),
                ("ipaddress", models.CharField(blank=True, default="", max_length=64, verbose_name="IP address")),
                ("result", models.BooleanField(default=True, verbose_name="Result")),
                ("detail", models.CharField(blank=True, default="", max_length=255, verbose_name="Detail")),
                ("created_time", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created time")),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to="system.uploadfile",
                        verbose_name="File",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="file_access_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "File access log",
                "verbose_name_plural": "File access log",
                "ordering": ["-created_time"],
                "indexes": [
                    models.Index(fields=["file", "created_time"], name="idx_file_log_file_created"),
                    models.Index(fields=["user", "action"], name="idx_file_log_user_action"),
                ],
            },
        ),
    ]
