# Generated by Django 6.0.8 on 2026-09-22 12:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0009_approvalflownode_cc_users_approvalinstance_cc_users_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedListView",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("page_key", models.CharField(db_index=True, max_length=128, verbose_name="Page key")),
                ("name", models.CharField(max_length=64, verbose_name="View name")),
                ("conditions", models.JSONField(blank=True, default=dict, verbose_name="Conditions")),
                ("ordering", models.CharField(blank=True, default="", max_length=64, verbose_name="Ordering")),
                ("is_default", models.BooleanField(default=False, verbose_name="Is default")),
                ("is_shared", models.BooleanField(default=False, verbose_name="Is shared")),
                ("remark", models.CharField(blank=True, default="", max_length=255, verbose_name="Remark")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_list_views",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved list view",
                "verbose_name_plural": "Saved list view",
                "ordering": ["page_key", "-is_default", "created_time"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "page_key", "name"), name="uniq_saved_view_owner_page_name"
                    )
                ],
            },
        ),
    ]
