# Generated by Django 6.0.8 on 2026-10-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0009_dept_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userloginlog",
            name="login_type",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Username and password"),
                    (1, "SMS verification code"),
                    (2, "Email verification code"),
                    (4, "Wechat scan code"),
                    (5, "Third-party OAuth"),
                    (3, "LDAP directory account"),
                    (8, "Websocket"),
                    (9, "Unknown"),
                    (6, "Impersonation"),
                ],
                default=0,
                verbose_name="Login type",
            ),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="login_type",
            field=models.IntegerField(
                choices=[
                    (0, "Username and password"),
                    (1, "SMS verification code"),
                    (2, "Email verification code"),
                    (4, "Wechat scan code"),
                    (5, "Third-party OAuth"),
                    (3, "LDAP directory account"),
                    (8, "Websocket"),
                    (9, "Unknown"),
                    (6, "Impersonation"),
                ],
                default=9,
                verbose_name="Login type",
            ),
        ),
    ]
