# Generated by Django 6.0.8 on 2026-09-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0009_alter_systemconfig_options_approvalrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalaccesstoken",
            name="scopes",
            field=models.JSONField(blank=True, default=list, verbose_name="Scopes"),
        ),
    ]
