# Generated by Django 6.0.8 on 2026-09-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0009_userinfo_date_password_updated_passwordhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrole",
            name="builtin",
            field=models.BooleanField(default=False, verbose_name="Is builtin"),
        ),
    ]
