# Generated by Django 6.0.8 on 2026-09-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0010_savedlistview"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="date_expired",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Account expiry"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="invite_status",
            field=models.CharField(
                blank=True,
                choices=[("pending", "Pending acceptance"), ("accepted", "Accepted")],
                default="",
                max_length=16,
                verbose_name="Invite status",
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="invited_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Invited at"),
        ),
    ]
