# Generated by Django 6.0.8 on 2026-09-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0010_personalaccesstoken_scopes"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadfile",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Category options come from the data dictionary upload_category",
                max_length=32,
                null=True,
                verbose_name="Category",
            ),
        ),
        migrations.AddIndex(
            model_name="uploadfile",
            index=models.Index(fields=["creator", "created_time"], name="idx_uploadfile_creator_created"),
        ),
    ]
