# Generated by Django 6.0.8 on 2026-09-12 01:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0010_userrole_builtin"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalflow",
            name="version",
            field=models.IntegerField(default=0, verbose_name="Definition version"),
        ),
        migrations.AddField(
            model_name="approvalflownode",
            name="approve_ratio",
            field=models.SmallIntegerField(default=100, verbose_name="Approve ratio"),
        ),
        migrations.AddField(
            model_name="approvalflownode",
            name="layout",
            field=models.JSONField(blank=True, default=dict, verbose_name="Canvas layout"),
        ),
        migrations.AddField(
            model_name="approvalflownode",
            name="routes",
            field=models.JSONField(blank=True, default=list, verbose_name="Branch routes"),
        ),
        migrations.AddField(
            model_name="approvalinstance",
            name="flow_version",
            field=models.IntegerField(blank=True, null=True, verbose_name="Flow version"),
        ),
        migrations.AlterField(
            model_name="approvalflownode",
            name="approve_type",
            field=models.CharField(
                choices=[("OR", "Any approver"), ("AND", "All approvers"), ("RATIO", "Ratio approvers")],
                default="OR",
                max_length=5,
                verbose_name="Approve type",
            ),
        ),
        migrations.CreateModel(
            name="ApprovalFlowVersion",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.IntegerField(verbose_name="Version")),
                ("snapshot", models.JSONField(default=dict, verbose_name="Snapshot")),
                ("remark", models.CharField(blank=True, default="", max_length=128, verbose_name="Remark")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="system.approvalflow",
                        verbose_name="Flow",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval flow version",
                "verbose_name_plural": "Approval flow version",
                "ordering": ["-version"],
                "constraints": [models.UniqueConstraint(fields=("flow", "version"), name="uniq_approval_flow_version")],
            },
        ),
    ]
