# Generated by Django 6.0.8 on 2026-09-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0011_userinfo_date_expired_userinfo_invite_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportrecord",
            name="stage",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="Progress stage"),
        ),
        migrations.AddField(
            model_name="importrecord",
            name="stage",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="Progress stage"),
        ),
    ]
