# Generated by Django 6.0.8 on 2026-09-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0011_uploadfile_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationlog",
            name="auth_type",
            field=models.CharField(
                blank=True,
                choices=[("jwt", "JWT"), ("pat", "Personal access token")],
                max_length=16,
                null=True,
                verbose_name="Auth type",
            ),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="token_pk",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="Token pk"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["token_pk", "created_time"], name="idx_oplog_token_created"),
        ),
    ]
