# Generated by Django 6.0.8 on 2026-09-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0012_task_progress_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiusagerecord",
            name="track",
            field=models.CharField(blank=True, default="", max_length=16, verbose_name="Track"),
        ),
    ]
