# Generated by Django 6.0.8 on 2026-09-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0012_operationlog_auth_type_operationlog_token_pk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalaccesstoken",
            name="ip_allowlist",
            field=models.JSONField(blank=True, default=list, verbose_name="Ip allowlist"),
        ),
    ]
