import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0014_approvals_split_data"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # 3.1 拆分批次2：模型自 system 迁出 approval。表、索引、约束在库里
            # 原样保留（模型侧显式 db_table 指回 system_* 表名），以下全部是
            # 纯状态操作（删除 system 侧模型状态 + 外键串改指 approval.*），无 DDL
            state_operations=[
                migrations.RemoveIndex(
                    model_name="approvaldelegation",
                    name="idx_appr_deleg_delegator",
                ),
                migrations.RemoveIndex(
                    model_name="approvaldelegation",
                    name="idx_appr_deleg_delegate",
                ),
                migrations.RemoveField(
                    model_name="approvalflow",
                    name="creator",
                ),
                migrations.RemoveField(
                    model_name="approvalflow",
                    name="dept_belong",
                ),
                migrations.RemoveField(
                    model_name="approvalflow",
                    name="modifier",
                ),
                migrations.AlterField(
                    model_name="dynamicform",
                    name="approval_flow",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bound_forms",
                        to="approval.approvalflow",
                        verbose_name="Approval flow",
                    ),
                ),
                migrations.RemoveConstraint(
                    model_name="approvalflownode",
                    name="uniq_approval_flow_node_order",
                ),
                migrations.RemoveConstraint(
                    model_name="approvalflowversion",
                    name="uniq_approval_flow_version",
                ),
                migrations.RemoveIndex(
                    model_name="approvalinstance",
                    name="idx_appr_inst_status_created",
                ),
                migrations.RemoveIndex(
                    model_name="approvalinstance",
                    name="idx_appr_inst_creator_created",
                ),
                migrations.RemoveIndex(
                    model_name="approvalinstance",
                    name="idx_appr_inst_biz",
                ),
                migrations.AlterField(
                    model_name="dynamicformsubmission",
                    name="instance",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dform_submissions",
                        to="approval.approvalinstance",
                        verbose_name="Approval instance",
                    ),
                ),
                migrations.RemoveIndex(
                    model_name="approvalinstancecomment",
                    name="idx_appr_comment_inst_created",
                ),
                migrations.RemoveIndex(
                    model_name="approvalnodetask",
                    name="idx_appr_task_assignee_status",
                ),
                migrations.RemoveIndex(
                    model_name="approvalnodetask",
                    name="idx_appr_task_inst_order",
                ),
                migrations.RemoveIndex(
                    model_name="approvalrequest",
                    name="idx_approvalrequest_path_trgm",
                ),
                migrations.RemoveIndex(
                    model_name="approvalrequest",
                    name="idx_approval_module_trgm",
                ),
                migrations.RemoveIndex(
                    model_name="approvalrequest",
                    name="idx_approval_object_pk_trgm",
                ),
                migrations.RemoveIndex(
                    model_name="approvalrequest",
                    name="idx_approval_status_created",
                ),
                migrations.RemoveIndex(
                    model_name="approvalrequest",
                    name="idx_approval_creator_created",
                ),
                migrations.RemoveIndex(
                    model_name="approvalrequeststep",
                    name="idx_appr_step_req_status",
                ),
                migrations.RemoveConstraint(
                    model_name="approvalrequeststep",
                    name="uniq_approval_request_step_order",
                ),
                migrations.RemoveConstraint(
                    model_name="approvalrequeststepaction",
                    name="uniq_approval_step_action_user",
                ),
                migrations.RemoveField(
                    model_name="approvalrule",
                    name="creator",
                ),
                migrations.RemoveField(
                    model_name="approvalrule",
                    name="dept_belong",
                ),
                migrations.RemoveField(
                    model_name="approvalrule",
                    name="modifier",
                ),
                migrations.RemoveConstraint(
                    model_name="approvalrulelevel",
                    name="uniq_approval_rule_level_order",
                ),
                migrations.RemoveIndex(
                    model_name="leave",
                    name="idx_leave_reason_trgm",
                ),
                migrations.RemoveIndex(
                    model_name="leave",
                    name="idx_leave_status_created",
                ),
                migrations.RemoveIndex(
                    model_name="leave",
                    name="idx_leave_creator_start",
                ),
                migrations.RemoveField(
                    model_name="approvalflownode",
                    name="creator",
                ),
                migrations.RemoveField(
                    model_name="approvalflownode",
                    name="dept_belong",
                ),
                migrations.RemoveField(
                    model_name="approvalflownode",
                    name="flow",
                ),
                migrations.RemoveField(
                    model_name="approvalflownode",
                    name="modifier",
                ),
                migrations.RemoveField(
                    model_name="approvalflowversion",
                    name="creator",
                ),
                migrations.RemoveField(
                    model_name="approvalflowversion",
                    name="dept_belong",
                ),
                migrations.RemoveField(
                    model_name="approvalflowversion",
                    name="flow",
                ),
                migrations.RemoveField(
                    model_name="approvalflowversion",
                    name="modifier",
                ),
                migrations.RemoveField(
                    model_name="approvalinstance",
                    name="cc_users",
                ),
                migrations.RemoveField(
                    model_name="approvalinstance",
                    name="creator",
                ),
                migrations.RemoveField(
                    model_name="approvalinstance",
                    name="current_node",
                ),
                migrations.RemoveField(
                    model_name="approvalinstance",
                    name="dept_belong",
                ),
                migrations.RemoveField(
                    model_name="approvalinstance",
                    name="flow",
                ),
                migrations.RemoveField(
                    model_name="approvalinstance",
                    name="modifier",
                ),
                migrations.RemoveField(
                    model_name="approvalinstancecomment",
                    name="creator",
                ),
                migrations.RemoveField(
                    model_name="approvalinstancecomment",
                    name="dept_belong",
                ),
                migrations.RemoveField(
                    model_name="approvalinstancecomment",
                    name="instance",
                ),
                migrations.RemoveField(
                    model_name="approvalinstancecomment",
                    name="modifier",
                ),
                migrations.RemoveField(
                    model_name="approvalnodetask",
                    name="actor",
                ),
                migrations.RemoveField(
                    model_name="approvalnodetask",
                    name="assignee",
                ),
                migrations.RemoveField(
                    model_name="approvalnodetask",
                    name="creator",
                ),
                migrations.RemoveField(
                    model_name="approvalnodetask",
                    name="delegate_from",
                ),
                migrations.RemoveField(
                    model_name="approvalnodetask",
                    name="dept_belong",
                ),
                migrations.RemoveField(
                    model_name="approvalnodetask",
                    name="instance",
                ),
                migrations.RemoveField(
                    model_name="approvalnodetask",
                    name="modifier",
                ),
                migrations.RemoveField(
                    model_name="approvalnodetask",
                    name="node",
                ),
                migrations.RemoveField(
                    model_name="approvalrequest",
                    name="approver",
                ),
                migrations.RemoveField(
                    model_name="approvalrequest",
                    name="creator",
                ),
                migrations.RemoveField(
                    model_name="approvalrequest",
                    name="current_assignees",
                ),
                migrations.RemoveField(
                    model_name="approvalrequest",
                    name="dept_belong",
                ),
                migrations.RemoveField(
                    model_name="approvalrequest",
                    name="modifier",
                ),
                migrations.RemoveField(
                    model_name="approvalrequeststep",
                    name="approver",
                ),
                migrations.RemoveField(
                    model_name="approvalrequeststep",
                    name="assignees",
                ),
                migrations.RemoveField(
                    model_name="approvalrequeststep",
                    name="creator",
                ),
                migrations.RemoveField(
                    model_name="approvalrequeststep",
                    name="dept_belong",
                ),
                migrations.RemoveField(
                    model_name="approvalrequeststep",
                    name="modifier",
                ),
                migrations.RemoveField(
                    model_name="approvalrequeststep",
                    name="request",
                ),
                migrations.RemoveField(
                    model_name="approvalrequeststepaction",
                    name="approver",
                ),
                migrations.RemoveField(
                    model_name="approvalrequeststepaction",
                    name="creator",
                ),
                migrations.RemoveField(
                    model_name="approvalrequeststepaction",
                    name="dept_belong",
                ),
                migrations.RemoveField(
                    model_name="approvalrequeststepaction",
                    name="modifier",
                ),
                migrations.RemoveField(
                    model_name="approvalrequeststepaction",
                    name="step",
                ),
                migrations.RemoveField(
                    model_name="approvalrulelevel",
                    name="creator",
                ),
                migrations.RemoveField(
                    model_name="approvalrulelevel",
                    name="dept_belong",
                ),
                migrations.RemoveField(
                    model_name="approvalrulelevel",
                    name="modifier",
                ),
                migrations.RemoveField(
                    model_name="approvalrulelevel",
                    name="rule",
                ),
                migrations.RemoveField(
                    model_name="leave",
                    name="creator",
                ),
                migrations.RemoveField(
                    model_name="leave",
                    name="dept_belong",
                ),
                migrations.RemoveField(
                    model_name="leave",
                    name="instance",
                ),
                migrations.RemoveField(
                    model_name="leave",
                    name="modifier",
                ),
                migrations.DeleteModel(
                    name="ApprovalDelegation",
                ),
                migrations.DeleteModel(
                    name="ApprovalFlowVersion",
                ),
                migrations.DeleteModel(
                    name="ApprovalFlow",
                ),
                migrations.DeleteModel(
                    name="ApprovalInstanceComment",
                ),
                migrations.DeleteModel(
                    name="ApprovalFlowNode",
                ),
                migrations.DeleteModel(
                    name="ApprovalNodeTask",
                ),
                migrations.DeleteModel(
                    name="ApprovalRequest",
                ),
                migrations.DeleteModel(
                    name="ApprovalRequestStep",
                ),
                migrations.DeleteModel(
                    name="ApprovalRequestStepAction",
                ),
                migrations.DeleteModel(
                    name="ApprovalRule",
                ),
                migrations.DeleteModel(
                    name="ApprovalRuleLevel",
                ),
                migrations.DeleteModel(
                    name="ApprovalInstance",
                ),
                migrations.DeleteModel(
                    name="Leave",
                ),
            ],
        ),
    ]
