# Generated by Django 6.0.8 on 2026-09-26 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0016_ai_split_data"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # 3.1 拆分批次3：模型自 system 迁出 ai。表、索引、约束在库里原样
            # 保留（模型侧显式 db_table 指回 system_* 表名），以下全部是纯状态
            # 操作，无 DDL
            state_operations=[
                migrations.RemoveIndex(
                    model_name="aichatmessage",
                    name="ai_chat_msg_user_feat_idx",
                ),
                migrations.RemoveConstraint(
                    model_name="aiknowledgechunk",
                    name="uniq_ai_chunk_path_index",
                ),
                migrations.RemoveField(
                    model_name="aiknowledgedocument",
                    name="creator",
                ),
                migrations.RemoveField(
                    model_name="aiknowledgedocument",
                    name="dept_belong",
                ),
                migrations.RemoveField(
                    model_name="aiknowledgedocument",
                    name="modifier",
                ),
                migrations.RemoveConstraint(
                    model_name="aiprofile",
                    name="uniq_ai_profile_purpose_active",
                ),
                migrations.RemoveIndex(
                    model_name="aiusagerecord",
                    name="ai_usage_user_time_idx",
                ),
                migrations.RemoveIndex(
                    model_name="aiusagerecord",
                    name="ai_usage_feat_time_idx",
                ),
                migrations.RemoveField(
                    model_name="aichatmessage",
                    name="creator",
                ),
                migrations.RemoveField(
                    model_name="aichatmessage",
                    name="dept_belong",
                ),
                migrations.RemoveField(
                    model_name="aichatmessage",
                    name="modifier",
                ),
                migrations.RemoveField(
                    model_name="aiknowledgechunk",
                    name="creator",
                ),
                migrations.RemoveField(
                    model_name="aiknowledgechunk",
                    name="dept_belong",
                ),
                migrations.RemoveField(
                    model_name="aiknowledgechunk",
                    name="modifier",
                ),
                migrations.DeleteModel(
                    name="AiKnowledgeDocument",
                ),
                migrations.RemoveField(
                    model_name="aiprofile",
                    name="creator",
                ),
                migrations.RemoveField(
                    model_name="aiprofile",
                    name="dept_belong",
                ),
                migrations.RemoveField(
                    model_name="aiprofile",
                    name="modifier",
                ),
                migrations.RemoveField(
                    model_name="aiusagerecord",
                    name="creator",
                ),
                migrations.RemoveField(
                    model_name="aiusagerecord",
                    name="dept_belong",
                ),
                migrations.RemoveField(
                    model_name="aiusagerecord",
                    name="modifier",
                ),
                migrations.DeleteModel(
                    name="AiChatMessage",
                ),
                migrations.DeleteModel(
                    name="AiKnowledgeChunk",
                ),
                migrations.DeleteModel(
                    name="AiProfile",
                ),
                migrations.DeleteModel(
                    name="AiUsageRecord",
                ),
            ],
        ),
    ]
