[pytest]
DJANGO_SETTINGS_MODULE = tests.settings_test
testpaths = tests
python_files = test_*.py
addopts = --tb=short -q
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning