# Generated by Django 6.0.8 on 2026-10-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0001_initial"),
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deptinfo",
            name="rules",
            field=models.ManyToManyField(blank=True, to="system.datapermission", verbose_name="Data permission"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="rules",
            field=models.ManyToManyField(blank=True, to="system.datapermission", verbose_name="Data permission"),
        ),
        migrations.AddField(
            model_name="userrole",
            name="menu",
            field=models.ManyToManyField(blank=True, to="system.menu", verbose_name="Menu"),
        ),
    ]
