# Generated by Django 5.1.1 on 2024-09-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_load', models.FloatField(default=0, verbose_name='CPU Load')),
                ('cpu_percent', models.FloatField(default=0, verbose_name='CPU Percent')),
                ('memory_used', models.FloatField(verbose_name='Memory Used')),
                ('disk_used', models.FloatField(default=0, verbose_name='Disk Used')),
                ('boot_time', models.FloatField(default=0, verbose_name='Boot Time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitor',
            },
        ),
    ]
