# Generated by Django 6.0.8 on 2026-09-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="net_recv_mb",
            field=models.FloatField(default=0, verbose_name="Net received (MB)"),
        ),
        migrations.AddField(
            model_name="monitor",
            name="net_sent_mb",
            field=models.FloatField(default=0, verbose_name="Net sent (MB)"),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created time"),
        ),
        migrations.CreateModel(
            name="MonitorAlert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "item",
                    models.CharField(
                        choices=[
                            ("cpu_percent", "CPU percent"),
                            ("cpu_load", "CPU load"),
                            ("memory_used", "Memory used"),
                            ("disk_used", "Disk used"),
                        ],
                        max_length=32,
                        verbose_name="Alert item",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("firing", "Firing"), ("resolved", "Resolved")],
                        default="firing",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("value", models.FloatField(verbose_name="Trigger value")),
                ("threshold", models.FloatField(verbose_name="Threshold")),
                ("message", models.TextField(blank=True, default="", verbose_name="Message")),
                ("count", models.PositiveIntegerField(default=1, verbose_name="Hit count")),
                ("first_time", models.DateTimeField(verbose_name="First time")),
                ("last_time", models.DateTimeField(verbose_name="Last time")),
                ("resolved_time", models.DateTimeField(blank=True, null=True, verbose_name="Resolved time")),
                ("created_time", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created time")),
            ],
            options={
                "verbose_name": "Monitor alert",
                "verbose_name_plural": "Monitor alert",
                "ordering": ("-last_time",),
                "indexes": [
                    models.Index(fields=["status", "last_time"], name="idx_monitoralert_status_time"),
                    models.Index(fields=["item", "status"], name="idx_monitoralert_item_status"),
                ],
            },
        ),
    ]
