# Generated by Django 6.0.8 on 2026-09-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitor",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created time"),
        ),
    ]
