# Generated by Django 6.0.8 on 2026-10-05 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MfaRecoveryCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code_hash", models.CharField(max_length=64, verbose_name="Code hash")),
                ("created_time", models.DateTimeField(auto_now_add=True, verbose_name="Created time")),
                ("used_time", models.DateTimeField(blank=True, null=True, verbose_name="Used time")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_recovery_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "MFA recovery code",
                "verbose_name_plural": "MFA recovery code",
                "indexes": [models.Index(fields=["user", "used_time"], name="idx_mfarecovery_user_used")],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "code_hash"), name="uniq_mfarecoverycode_user_hash")
                ],
            },
        ),
    ]
