# Generated by Django 6.0.8 on 2026-09-26 12:15

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("system", "0005_squashed_0013_ai_usage_track"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # 3.1 拆分批次2：模型自 system 迁入，表已在库中（system_* 表名保持），
            # 全部为纯状态操作，不做任何 DDL
            state_operations=[
                migrations.CreateModel(
                    name="ApprovalFlow",
                    fields=[
                        (
                            "created_time",
                            models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time"),
                        ),
                        ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                        (
                            "description",
                            models.CharField(blank=True, max_length=256, null=True, verbose_name="Description"),
                        ),
                        ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ("name", models.CharField(max_length=64, verbose_name="Flow name")),
                        ("code", models.CharField(max_length=64, unique=True, verbose_name="Flow code")),
                        ("form_schema", models.JSONField(blank=True, default=list, verbose_name="Form schema")),
                        ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Is active")),
                        ("version", models.IntegerField(default=0, verbose_name="Definition version")),
                        (
                            "creator",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="creator_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Creator",
                            ),
                        ),
                        (
                            "dept_belong",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="dept_belong_query",
                                to="system.deptinfo",
                                verbose_name="Data ownership department",
                            ),
                        ),
                        (
                            "modifier",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="modifier_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Modifier",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Approval flow",
                        "verbose_name_plural": "Approval flow",
                        "db_table": "system_approvalflow",
                        "ordering": ["-created_time"],
                    },
                ),
                migrations.CreateModel(
                    name="ApprovalFlowNode",
                    fields=[
                        (
                            "created_time",
                            models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time"),
                        ),
                        ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                        (
                            "description",
                            models.CharField(blank=True, max_length=256, null=True, verbose_name="Description"),
                        ),
                        ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ("name", models.CharField(max_length=64, verbose_name="Node name")),
                        ("order", models.IntegerField(default=1, verbose_name="Node order")),
                        (
                            "approve_type",
                            models.CharField(
                                choices=[
                                    ("OR", "Any approver"),
                                    ("AND", "All approvers"),
                                    ("RATIO", "Ratio approvers"),
                                ],
                                default="OR",
                                max_length=5,
                                verbose_name="Approve type",
                            ),
                        ),
                        ("approve_ratio", models.SmallIntegerField(default=100, verbose_name="Approve ratio")),
                        (
                            "assignee_type",
                            models.CharField(
                                choices=[
                                    ("role", "Role"),
                                    ("user", "User"),
                                    ("leader", "Leader"),
                                    ("field", "Form field"),
                                ],
                                default="role",
                                max_length=8,
                                verbose_name="Assignee type",
                            ),
                        ),
                        (
                            "assignee_value",
                            models.CharField(blank=True, default="", max_length=255, verbose_name="Assignee value"),
                        ),
                        ("condition", models.JSONField(blank=True, default=dict, verbose_name="Condition")),
                        ("routes", models.JSONField(blank=True, default=list, verbose_name="Branch routes")),
                        ("layout", models.JSONField(blank=True, default=dict, verbose_name="Canvas layout")),
                        ("timeout_hours", models.IntegerField(default=0, verbose_name="Timeout hours")),
                        ("cc_users", models.JSONField(blank=True, default=list, verbose_name="CC users")),
                        (
                            "creator",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="creator_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Creator",
                            ),
                        ),
                        (
                            "dept_belong",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="dept_belong_query",
                                to="system.deptinfo",
                                verbose_name="Data ownership department",
                            ),
                        ),
                        (
                            "flow",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="nodes",
                                to="approval.approvalflow",
                                verbose_name="Flow",
                            ),
                        ),
                        (
                            "modifier",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="modifier_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Modifier",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Approval flow node",
                        "verbose_name_plural": "Approval flow node",
                        "db_table": "system_approvalflownode",
                        "ordering": ["order", "created_time"],
                    },
                ),
                migrations.CreateModel(
                    name="ApprovalFlowVersion",
                    fields=[
                        (
                            "created_time",
                            models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time"),
                        ),
                        ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                        (
                            "description",
                            models.CharField(blank=True, max_length=256, null=True, verbose_name="Description"),
                        ),
                        ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ("version", models.IntegerField(verbose_name="Version")),
                        ("snapshot", models.JSONField(default=dict, verbose_name="Snapshot")),
                        ("remark", models.CharField(blank=True, default="", max_length=128, verbose_name="Remark")),
                        (
                            "creator",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="creator_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Creator",
                            ),
                        ),
                        (
                            "dept_belong",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="dept_belong_query",
                                to="system.deptinfo",
                                verbose_name="Data ownership department",
                            ),
                        ),
                        (
                            "flow",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="versions",
                                to="approval.approvalflow",
                                verbose_name="Flow",
                            ),
                        ),
                        (
                            "modifier",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="modifier_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Modifier",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Approval flow version",
                        "verbose_name_plural": "Approval flow version",
                        "db_table": "system_approvalflowversion",
                        "ordering": ["-version"],
                    },
                ),
                migrations.CreateModel(
                    name="ApprovalInstance",
                    fields=[
                        (
                            "created_time",
                            models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time"),
                        ),
                        ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                        (
                            "description",
                            models.CharField(blank=True, max_length=256, null=True, verbose_name="Description"),
                        ),
                        ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ("flow_name", models.CharField(max_length=64, verbose_name="Flow name")),
                        ("title", models.CharField(max_length=128, verbose_name="Title")),
                        ("form_data", models.JSONField(blank=True, default=dict, verbose_name="Form data")),
                        (
                            "biz_type",
                            models.CharField(
                                blank=True, db_index=True, default="", max_length=64, verbose_name="Business type"
                            ),
                        ),
                        ("biz_id", models.CharField(blank=True, default="", max_length=64, verbose_name="Business id")),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("PENDING", "Pending"),
                                    ("APPROVED", "Approved"),
                                    ("REJECTED", "Rejected"),
                                    ("CANCELLED", "Cancelled"),
                                ],
                                db_index=True,
                                default="PENDING",
                                max_length=16,
                                verbose_name="Status",
                            ),
                        ),
                        ("flow_version", models.IntegerField(blank=True, null=True, verbose_name="Flow version")),
                        ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="Finished at")),
                        ("reason", models.CharField(blank=True, max_length=255, null=True, verbose_name="Reason")),
                        (
                            "cc_users",
                            models.ManyToManyField(
                                blank=True,
                                related_name="approval_cc_instances",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="CC users",
                            ),
                        ),
                        (
                            "creator",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="creator_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Creator",
                            ),
                        ),
                        (
                            "current_node",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                to="approval.approvalflownode",
                                verbose_name="Current node",
                            ),
                        ),
                        (
                            "dept_belong",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="dept_belong_query",
                                to="system.deptinfo",
                                verbose_name="Data ownership department",
                            ),
                        ),
                        (
                            "flow",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="instances",
                                to="approval.approvalflow",
                                verbose_name="Flow",
                            ),
                        ),
                        (
                            "modifier",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="modifier_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Modifier",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Approval instance",
                        "verbose_name_plural": "Approval instance",
                        "db_table": "system_approvalinstance",
                        "ordering": ["-created_time"],
                    },
                ),
                migrations.CreateModel(
                    name="ApprovalInstanceComment",
                    fields=[
                        (
                            "created_time",
                            models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time"),
                        ),
                        ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                        (
                            "description",
                            models.CharField(blank=True, max_length=256, null=True, verbose_name="Description"),
                        ),
                        ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ("content", models.TextField(max_length=2000, verbose_name="Content")),
                        (
                            "author_display",
                            models.CharField(blank=True, default="", max_length=128, verbose_name="Author display"),
                        ),
                        ("mentions", models.JSONField(blank=True, default=list, verbose_name="Mentions")),
                        (
                            "creator",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="creator_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Creator",
                            ),
                        ),
                        (
                            "dept_belong",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="dept_belong_query",
                                to="system.deptinfo",
                                verbose_name="Data ownership department",
                            ),
                        ),
                        (
                            "instance",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="comments",
                                to="approval.approvalinstance",
                                verbose_name="Instance",
                            ),
                        ),
                        (
                            "modifier",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="modifier_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Modifier",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Approval instance comment",
                        "verbose_name_plural": "Approval instance comment",
                        "db_table": "system_approvalinstancecomment",
                        "ordering": ["created_time"],
                    },
                ),
                migrations.CreateModel(
                    name="ApprovalNodeTask",
                    fields=[
                        (
                            "created_time",
                            models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time"),
                        ),
                        ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                        (
                            "description",
                            models.CharField(blank=True, max_length=256, null=True, verbose_name="Description"),
                        ),
                        ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ("node_name", models.CharField(max_length=64, verbose_name="Node name")),
                        ("node_order", models.IntegerField(default=1, verbose_name="Node order")),
                        (
                            "assignee_display",
                            models.CharField(blank=True, default="", max_length=128, verbose_name="Assignee display"),
                        ),
                        (
                            "actor_display",
                            models.CharField(blank=True, default="", max_length=128, verbose_name="Actor display"),
                        ),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("PENDING", "Pending"),
                                    ("APPROVED", "Approved"),
                                    ("REJECTED", "Rejected"),
                                    ("CANCELLED", "Cancelled"),
                                ],
                                db_index=True,
                                default="PENDING",
                                max_length=16,
                                verbose_name="Status",
                            ),
                        ),
                        ("comment", models.CharField(blank=True, max_length=255, null=True, verbose_name="Comment")),
                        ("acted_at", models.DateTimeField(blank=True, null=True, verbose_name="Acted at")),
                        ("is_added", models.BooleanField(default=False, verbose_name="Added by counter-sign")),
                        (
                            "actor",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="approval_node_acted_tasks",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Actor",
                            ),
                        ),
                        (
                            "assignee",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="approval_node_tasks",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Assignee",
                            ),
                        ),
                        (
                            "creator",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="creator_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Creator",
                            ),
                        ),
                        (
                            "delegate_from",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="approval_node_delegated_tasks",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Delegate from",
                            ),
                        ),
                        (
                            "dept_belong",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="dept_belong_query",
                                to="system.deptinfo",
                                verbose_name="Data ownership department",
                            ),
                        ),
                        (
                            "instance",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="tasks",
                                to="approval.approvalinstance",
                                verbose_name="Instance",
                            ),
                        ),
                        (
                            "modifier",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="modifier_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Modifier",
                            ),
                        ),
                        (
                            "node",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                to="approval.approvalflownode",
                                verbose_name="Node",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Approval node task",
                        "verbose_name_plural": "Approval node task",
                        "db_table": "system_approvalnodetask",
                        "ordering": ["node_order", "created_time"],
                    },
                ),
                migrations.CreateModel(
                    name="ApprovalRequest",
                    fields=[
                        (
                            "created_time",
                            models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time"),
                        ),
                        ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                        (
                            "description",
                            models.CharField(blank=True, max_length=256, null=True, verbose_name="Description"),
                        ),
                        ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ("module", models.CharField(blank=True, max_length=64, null=True, verbose_name="Module")),
                        ("method", models.CharField(max_length=8, verbose_name="Method")),
                        ("path", models.CharField(max_length=400, verbose_name="URL path")),
                        ("object_pk", models.CharField(blank=True, max_length=64, null=True, verbose_name="Object pk")),
                        ("params", models.JSONField(blank=True, default=dict, verbose_name="Request params")),
                        ("payload", models.JSONField(blank=True, default=dict, verbose_name="Request payload")),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("PENDING", "Pending"),
                                    ("APPROVED", "Approved"),
                                    ("REJECTED", "Rejected"),
                                    ("EXPIRED", "Expired"),
                                    ("CANCELLED", "Cancelled"),
                                    ("FAILED", "Failed"),
                                ],
                                db_index=True,
                                default="PENDING",
                                max_length=16,
                                verbose_name="Status",
                            ),
                        ),
                        ("approved_at", models.DateTimeField(blank=True, null=True, verbose_name="Approved at")),
                        ("expired_at", models.DateTimeField(blank=True, null=True, verbose_name="Token expired at")),
                        ("consume_time", models.DateTimeField(blank=True, null=True, verbose_name="Consume time")),
                        ("auto_completed", models.BooleanField(default=False, verbose_name="Auto completed")),
                        ("reason", models.CharField(blank=True, max_length=255, null=True, verbose_name="Reason")),
                        (
                            "approver_display",
                            models.CharField(blank=True, default="", max_length=128, verbose_name="Approver display"),
                        ),
                        ("target_snapshot", models.JSONField(blank=True, default=dict, verbose_name="Target snapshot")),
                        ("current_level", models.PositiveSmallIntegerField(default=0, verbose_name="Current level")),
                        (
                            "approver",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="approved_requests",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Approver",
                            ),
                        ),
                        (
                            "creator",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="creator_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Creator",
                            ),
                        ),
                        (
                            "current_assignees",
                            models.ManyToManyField(
                                blank=True,
                                related_name="approval_current_assignments",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Current approvers",
                            ),
                        ),
                        (
                            "dept_belong",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="dept_belong_query",
                                to="system.deptinfo",
                                verbose_name="Data ownership department",
                            ),
                        ),
                        (
                            "modifier",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="modifier_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Modifier",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Approval request",
                        "verbose_name_plural": "Approval request",
                        "db_table": "system_approvalrequest",
                        "ordering": ["-created_time"],
                    },
                ),
                migrations.CreateModel(
                    name="ApprovalRequestStep",
                    fields=[
                        (
                            "created_time",
                            models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time"),
                        ),
                        ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                        (
                            "description",
                            models.CharField(blank=True, max_length=256, null=True, verbose_name="Description"),
                        ),
                        ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ("name", models.CharField(blank=True, default="", max_length=64, verbose_name="Level name")),
                        ("order", models.PositiveSmallIntegerField(default=1, verbose_name="Level order")),
                        (
                            "assignee_type",
                            models.CharField(blank=True, default="", max_length=8, verbose_name="Assignee type"),
                        ),
                        (
                            "assignee_value",
                            models.CharField(blank=True, default="", max_length=255, verbose_name="Assignee value"),
                        ),
                        (
                            "approve_type",
                            models.CharField(
                                choices=[("OR", "Any one approves"), ("AND", "All must approve")],
                                default="OR",
                                max_length=8,
                                verbose_name="Approve type",
                            ),
                        ),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("PENDING", "Pending"),
                                    ("APPROVED", "Approved"),
                                    ("REJECTED", "Rejected"),
                                    ("CANCELLED", "Cancelled"),
                                ],
                                db_index=True,
                                default="PENDING",
                                max_length=16,
                                verbose_name="Status",
                            ),
                        ),
                        (
                            "approver_display",
                            models.CharField(blank=True, default="", max_length=128, verbose_name="Approver display"),
                        ),
                        ("comment", models.CharField(blank=True, max_length=255, null=True, verbose_name="Comment")),
                        ("acted_at", models.DateTimeField(blank=True, null=True, verbose_name="Acted at")),
                        (
                            "approver",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="acted_approval_steps",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Approver",
                            ),
                        ),
                        (
                            "assignees",
                            models.ManyToManyField(
                                blank=True,
                                related_name="approval_step_assignments",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Assignees",
                            ),
                        ),
                        (
                            "creator",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="creator_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Creator",
                            ),
                        ),
                        (
                            "dept_belong",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="dept_belong_query",
                                to="system.deptinfo",
                                verbose_name="Data ownership department",
                            ),
                        ),
                        (
                            "modifier",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="modifier_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Modifier",
                            ),
                        ),
                        (
                            "request",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="steps",
                                to="approval.approvalrequest",
                                verbose_name="Approval request",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Approval request step",
                        "verbose_name_plural": "Approval request step",
                        "db_table": "system_approvalrequeststep",
                        "ordering": ["order", "created_time"],
                    },
                ),
                migrations.CreateModel(
                    name="ApprovalRequestStepAction",
                    fields=[
                        (
                            "created_time",
                            models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time"),
                        ),
                        ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                        (
                            "description",
                            models.CharField(blank=True, max_length=256, null=True, verbose_name="Description"),
                        ),
                        ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        (
                            "approver_display",
                            models.CharField(blank=True, default="", max_length=128, verbose_name="Approver display"),
                        ),
                        (
                            "status",
                            models.CharField(
                                choices=[("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                                default="APPROVED",
                                max_length=16,
                                verbose_name="Status",
                            ),
                        ),
                        ("comment", models.CharField(blank=True, max_length=255, null=True, verbose_name="Comment")),
                        (
                            "approver",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="approval_step_actions",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Approver",
                            ),
                        ),
                        (
                            "creator",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="creator_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Creator",
                            ),
                        ),
                        (
                            "dept_belong",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="dept_belong_query",
                                to="system.deptinfo",
                                verbose_name="Data ownership department",
                            ),
                        ),
                        (
                            "modifier",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="modifier_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Modifier",
                            ),
                        ),
                        (
                            "step",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="actions",
                                to="approval.approvalrequeststep",
                                verbose_name="Approval step",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Approval step action",
                        "verbose_name_plural": "Approval step action",
                        "db_table": "system_approvalrequeststepaction",
                        "ordering": ["created_time"],
                    },
                ),
                migrations.CreateModel(
                    name="ApprovalRule",
                    fields=[
                        (
                            "created_time",
                            models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time"),
                        ),
                        ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                        (
                            "description",
                            models.CharField(blank=True, max_length=256, null=True, verbose_name="Description"),
                        ),
                        ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ("name", models.CharField(max_length=64, verbose_name="Rule name")),
                        ("path_patterns", models.JSONField(blank=True, default=list, verbose_name="Path patterns")),
                        ("priority", models.IntegerField(default=0, verbose_name="Priority")),
                        ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Is active")),
                        ("remark", models.CharField(blank=True, max_length=255, null=True, verbose_name="Remark")),
                        (
                            "creator",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="creator_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Creator",
                            ),
                        ),
                        (
                            "dept_belong",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="dept_belong_query",
                                to="system.deptinfo",
                                verbose_name="Data ownership department",
                            ),
                        ),
                        (
                            "modifier",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="modifier_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Modifier",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Approval rule",
                        "verbose_name_plural": "Approval rule",
                        "db_table": "system_approvalrule",
                        "ordering": ["-priority", "-created_time"],
                    },
                ),
                migrations.CreateModel(
                    name="ApprovalRuleLevel",
                    fields=[
                        (
                            "created_time",
                            models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time"),
                        ),
                        ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                        (
                            "description",
                            models.CharField(blank=True, max_length=256, null=True, verbose_name="Description"),
                        ),
                        ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ("name", models.CharField(blank=True, default="", max_length=64, verbose_name="Level name")),
                        ("order", models.PositiveSmallIntegerField(default=1, verbose_name="Level order")),
                        (
                            "approve_type",
                            models.CharField(
                                choices=[("OR", "Any one approves"), ("AND", "All must approve")],
                                default="OR",
                                max_length=8,
                                verbose_name="Approve type",
                            ),
                        ),
                        (
                            "assignee_type",
                            models.CharField(
                                choices=[("user", "User"), ("role", "Role")],
                                default="user",
                                max_length=8,
                                verbose_name="Assignee type",
                            ),
                        ),
                        (
                            "assignee_value",
                            models.CharField(blank=True, default="", max_length=255, verbose_name="Assignee value"),
                        ),
                        (
                            "creator",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="creator_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Creator",
                            ),
                        ),
                        (
                            "dept_belong",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="dept_belong_query",
                                to="system.deptinfo",
                                verbose_name="Data ownership department",
                            ),
                        ),
                        (
                            "modifier",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="modifier_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Modifier",
                            ),
                        ),
                        (
                            "rule",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="levels",
                                to="approval.approvalrule",
                                verbose_name="Rule",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Approval rule level",
                        "verbose_name_plural": "Approval rule level",
                        "db_table": "system_approvalrulelevel",
                        "ordering": ["order", "created_time"],
                    },
                ),
                migrations.CreateModel(
                    name="Leave",
                    fields=[
                        (
                            "id",
                            models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID"),
                        ),
                        (
                            "created_time",
                            models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time"),
                        ),
                        ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                        (
                            "description",
                            models.CharField(blank=True, max_length=256, null=True, verbose_name="Description"),
                        ),
                        (
                            "leave_type",
                            models.CharField(
                                choices=[
                                    ("annual", "Annual leave"),
                                    ("sick", "Sick leave"),
                                    ("personal", "Personal leave"),
                                    ("comp_time", "Compensatory leave"),
                                    ("marriage", "Marriage leave"),
                                    ("other", "Other"),
                                ],
                                default="annual",
                                max_length=32,
                                verbose_name="Leave type",
                            ),
                        ),
                        ("start_date", models.DateField(verbose_name="Start date")),
                        ("end_date", models.DateField(verbose_name="End date")),
                        ("days", models.DecimalField(decimal_places=1, max_digits=5, verbose_name="Days")),
                        ("reason", models.CharField(max_length=500, verbose_name="Reason")),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("DRAFT", "Draft"),
                                    ("PENDING", "Pending"),
                                    ("APPROVED", "Approved"),
                                    ("REJECTED", "Rejected"),
                                    ("CANCELLED", "Cancelled"),
                                ],
                                db_index=True,
                                default="DRAFT",
                                max_length=16,
                                verbose_name="Status",
                            ),
                        ),
                        (
                            "creator",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="creator_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Creator",
                            ),
                        ),
                        (
                            "dept_belong",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="dept_belong_query",
                                to="system.deptinfo",
                                verbose_name="Data ownership department",
                            ),
                        ),
                        (
                            "instance",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="leaves",
                                to="approval.approvalinstance",
                                verbose_name="Approval instance",
                            ),
                        ),
                        (
                            "modifier",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="modifier_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Modifier",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Leave request",
                        "verbose_name_plural": "Leave request",
                        "db_table": "system_leave",
                        "ordering": ["-created_time"],
                    },
                ),
                migrations.CreateModel(
                    name="ApprovalDelegation",
                    fields=[
                        (
                            "created_time",
                            models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time"),
                        ),
                        ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                        (
                            "description",
                            models.CharField(blank=True, max_length=256, null=True, verbose_name="Description"),
                        ),
                        ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ("start_time", models.DateTimeField(verbose_name="Start time")),
                        ("end_time", models.DateTimeField(verbose_name="End time")),
                        ("flow_codes", models.JSONField(blank=True, default=list, verbose_name="Flow codes")),
                        ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                        ("remark", models.CharField(blank=True, max_length=255, null=True, verbose_name="Remark")),
                        (
                            "creator",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="creator_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Creator",
                            ),
                        ),
                        (
                            "delegate",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="approval_delegations_as_delegate",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Delegate",
                            ),
                        ),
                        (
                            "delegator",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="approval_delegations",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Delegator",
                            ),
                        ),
                        (
                            "dept_belong",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="dept_belong_query",
                                to="system.deptinfo",
                                verbose_name="Data ownership department",
                            ),
                        ),
                        (
                            "modifier",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="modifier_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Modifier",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Approval delegation",
                        "verbose_name_plural": "Approval delegation",
                        "db_table": "system_approvaldelegation",
                        "ordering": ["-created_time"],
                        "indexes": [
                            models.Index(fields=["delegator", "is_active"], name="idx_appr_deleg_delegator"),
                            models.Index(fields=["delegate", "is_active"], name="idx_appr_deleg_delegate"),
                        ],
                    },
                ),
                migrations.AddConstraint(
                    model_name="approvalflownode",
                    constraint=models.UniqueConstraint(fields=("flow", "order"), name="uniq_approval_flow_node_order"),
                ),
                migrations.AddConstraint(
                    model_name="approvalflowversion",
                    constraint=models.UniqueConstraint(fields=("flow", "version"), name="uniq_approval_flow_version"),
                ),
                migrations.AddIndex(
                    model_name="approvalinstance",
                    index=models.Index(fields=["status", "created_time"], name="idx_appr_inst_status_created"),
                ),
                migrations.AddIndex(
                    model_name="approvalinstance",
                    index=models.Index(fields=["creator", "created_time"], name="idx_appr_inst_creator_created"),
                ),
                migrations.AddIndex(
                    model_name="approvalinstance",
                    index=models.Index(fields=["biz_type", "biz_id"], name="idx_appr_inst_biz"),
                ),
                migrations.AddIndex(
                    model_name="approvalinstancecomment",
                    index=models.Index(fields=["instance", "created_time"], name="idx_appr_comment_inst_created"),
                ),
                migrations.AddIndex(
                    model_name="approvalnodetask",
                    index=models.Index(fields=["assignee", "status"], name="idx_appr_task_assignee_status"),
                ),
                migrations.AddIndex(
                    model_name="approvalnodetask",
                    index=models.Index(fields=["instance", "node_order"], name="idx_appr_task_inst_order"),
                ),
                migrations.AddIndex(
                    model_name="approvalrequest",
                    index=models.Index(fields=["status", "created_time"], name="idx_approval_status_created"),
                ),
                migrations.AddIndex(
                    model_name="approvalrequest",
                    index=models.Index(fields=["creator", "created_time"], name="idx_approval_creator_created"),
                ),
                migrations.AddIndex(
                    model_name="approvalrequest",
                    index=django.contrib.postgres.indexes.GinIndex(
                        fields=["path"], name="idx_approvalrequest_path_trgm", opclasses=["gin_trgm_ops"]
                    ),
                ),
                migrations.AddIndex(
                    model_name="approvalrequest",
                    index=django.contrib.postgres.indexes.GinIndex(
                        fields=["module"], name="idx_approval_module_trgm", opclasses=["gin_trgm_ops"]
                    ),
                ),
                migrations.AddIndex(
                    model_name="approvalrequest",
                    index=django.contrib.postgres.indexes.GinIndex(
                        fields=["object_pk"], name="idx_approval_object_pk_trgm", opclasses=["gin_trgm_ops"]
                    ),
                ),
                migrations.AddIndex(
                    model_name="approvalrequeststep",
                    index=models.Index(fields=["request", "status"], name="idx_appr_step_req_status"),
                ),
                migrations.AddConstraint(
                    model_name="approvalrequeststep",
                    constraint=models.UniqueConstraint(
                        fields=("request", "order"), name="uniq_approval_request_step_order"
                    ),
                ),
                migrations.AddConstraint(
                    model_name="approvalrequeststepaction",
                    constraint=models.UniqueConstraint(
                        fields=("step", "approver"), name="uniq_approval_step_action_user"
                    ),
                ),
                migrations.AddConstraint(
                    model_name="approvalrulelevel",
                    constraint=models.UniqueConstraint(fields=("rule", "order"), name="uniq_approval_rule_level_order"),
                ),
                migrations.AddIndex(
                    model_name="leave",
                    index=models.Index(fields=["status", "created_time"], name="idx_leave_status_created"),
                ),
                migrations.AddIndex(
                    model_name="leave",
                    index=models.Index(fields=["creator", "start_date"], name="idx_leave_creator_start"),
                ),
                migrations.AddIndex(
                    model_name="leave",
                    index=django.contrib.postgres.indexes.GinIndex(
                        fields=["reason"], name="idx_leave_reason_trgm", opclasses=["gin_trgm_ops"]
                    ),
                ),
            ],
        ),
    ]
