# Generated by Django 6.0.8 on 2026-10-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approval", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrule",
            name="methods",
            field=models.JSONField(blank=True, default=list, verbose_name="Methods"),
        ),
    ]
