# Generated by Django 6.0.8 on 2026-09-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approval", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalflownode",
            name="assignee_type",
            field=models.CharField(
                choices=[
                    ("role", "Role"),
                    ("user", "User"),
                    ("leader", "Leader"),
                    ("field", "Form field"),
                    ("post", "Post"),
                ],
                default="role",
                max_length=8,
                verbose_name="Assignee type",
            ),
        ),
        migrations.AlterField(
            model_name="approvalrulelevel",
            name="assignee_type",
            field=models.CharField(
                choices=[("user", "User"), ("role", "Role"), ("post", "Post")],
                default="user",
                max_length=8,
                verbose_name="Assignee type",
            ),
        ),
    ]
