# Generated by Django 6.0.8 on 2026-09-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approval", "0003_flow_node_version_range"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalflownode",
            name="timeout_action",
            field=models.CharField(
                choices=[
                    ("none", "No action"),
                    ("approve", "Auto approve"),
                    ("reject", "Auto reject"),
                    ("transfer_up", "Escalate to leader"),
                ],
                default="none",
                max_length=16,
                verbose_name="Timeout action",
            ),
        ),
    ]
