# Generated by Django 6.0.8 on 2026-10-03 00:44
"""TG-3（ADR-080）：物理表名归域——去掉拆分期冻结的 ``system_`` 前缀。

ADR-057 拆分时「表名不变」的兼容冻结到此解除：13 个模型的显式 ``db_table``
全部移除，表名回落 Django 默认命名（``approval_<模型名小写>``），
``AlterModelTable(table=None)`` 逐表 ``ALTER TABLE ... RENAME TO``（PG 元数据级、
单迁移单事务；自动 m2m 中间表由该操作连带重命名，见 Django
``AlterModelTable.database_forwards``）。trgm 检索索引随表自动跟随、无需 DDL，
其迁移内历史快照到当前表名的折算登记见 ``TRGM_TABLE_RENAMES``。
"""

from django.db import migrations

#: trgm 索引快照折算（ADR-058 冻结于 approval/0001 的历史表名 → 当前表名）。
#: 索引本体随 ``ALTER TABLE RENAME`` 自动跟随、名字不变，此登记仅供
#: tests/unit/system/test_search_indexes.py 做快照 ↔ 运行期清单的名实对账；
#: 遗漏登记会让漂移守护红灯（旧表名对不上运行期清单）。
TRGM_TABLE_RENAMES = {
    "system_approvalrequest": "approval_approvalrequest",
    "system_leave": "approval_leave",
}


class Migration(migrations.Migration):
    dependencies = [
        ("approval", "0004_approvalflownode_timeout_action"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="approvaldelegation",
            table=None,
        ),
        migrations.AlterModelTable(
            name="approvalflow",
            table=None,
        ),
        migrations.AlterModelTable(
            name="approvalflownode",
            table=None,
        ),
        migrations.AlterModelTable(
            name="approvalflowversion",
            table=None,
        ),
        migrations.AlterModelTable(
            name="approvalinstance",
            table=None,
        ),
        migrations.AlterModelTable(
            name="approvalinstancecomment",
            table=None,
        ),
        migrations.AlterModelTable(
            name="approvalnodetask",
            table=None,
        ),
        migrations.AlterModelTable(
            name="approvalrequest",
            table=None,
        ),
        migrations.AlterModelTable(
            name="approvalrequeststep",
            table=None,
        ),
        migrations.AlterModelTable(
            name="approvalrequeststepaction",
            table=None,
        ),
        migrations.AlterModelTable(
            name="approvalrule",
            table=None,
        ),
        migrations.AlterModelTable(
            name="approvalrulelevel",
            table=None,
        ),
        migrations.AlterModelTable(
            name="leave",
            table=None,
        ),
    ]
