"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os

from django.core.exceptions import ImproperlyConfigured

from ..const import CONFIG, PROJECT_DIR

BASE_DIR = PROJECT_DIR
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = CONFIG.SECRET_KEY

DEBUG = CONFIG.DEBUG

# SECRET_KEY 同时作为 JWT 签名密钥（SIMPLE_JWT.SIGNING_KEY），
# 生产环境为空会导致任意伪造 token，直接拒绝启动；DEBUG 模式允许为空便于本地调试。
# 注：无配置文件回落 config_example.yml、DEBUG=true 或显式 SECRET_KEY_AUTO_GENERATE=true
# 三种场景会在 server/conf/manager.py 自动生成并持久化密钥（data/.secret_key），一般不会走到本分支。
if not SECRET_KEY and not DEBUG:
    raise ImproperlyConfigured(
        "SECRET_KEY is required when DEBUG is disabled. Fix it with one of:\n"
        "  1. Set SECRET_KEY in config.yml (recommended for production);\n"
        "  2. Export the SECRET_KEY environment variable before startup;\n"
        "  3. Set SECRET_KEY_AUTO_GENERATE=true to auto-generate and persist data/.secret_key."
    )

# SECURITY WARNING: If you run with debug turned on, more debug msg with be log
DEBUG_DEV = CONFIG.DEBUG_DEV

LOG_LEVEL = CONFIG.LOG_LEVEL

# 如果前端是代理，则可以通过该配置，在系统构建url的时候，获取正确的 scheme
# 需要在 前端加入该配置  proxy_set_header X-Forwarded-Proto $scheme;
# https://docs.djangoproject.com/zh-hans/4.2/ref/settings/#std-setting-SECURE_PROXY_SSL_HEADER
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# 为了兼容前端NGINX代理，并且使用非80，443端口访问，详细查看源码：django.http.request.HttpRequest._get_raw_host
# https://docs.djangoproject.com/zh-hans/4.2/ref/settings/#use-x-forwarded-host
USE_X_FORWARDED_HOST = True

# DEBUG 模式默认放行所有 Host；生产环境必须通过 config.yml 配置域名白名单
ALLOWED_HOSTS = CONFIG.ALLOWED_HOSTS or (["*"] if DEBUG else [])

# 反向代理信任清单（防 XFF 伪造，语义见 conf.py）：默认空 = 不信任任何 X-Forwarded-For
TRUSTED_PROXY_IPS = CONFIG.TRUSTED_PROXY_IPS

# ---------------------------------------------------------------------------
# HTTPS 部署安全头（S3，语义见 conf.py；默认关闭 = HTTP 直连部署零影响）
# 开启 SECURITY_HTTPS_ENABLED 后：HSTS 一年（含子域/preload）+ Secure Cookie。
# 其余安全头（X-Content-Type-Options 等）Django 已默认下发，无需随开关变化。
# HTTP→HTTPS 跳转是独立开关：需要代理层正确传递 X-Forwarded-Proto，
# 纯 TCP stream 代理下开启会造成重定向循环（保持关闭，由网关侧做跳转）。
# ---------------------------------------------------------------------------
SECURITY_HTTPS_ENABLED = CONFIG.SECURITY_HTTPS_ENABLED
SECURE_HSTS_SECONDS = 31536000 if SECURITY_HTTPS_ENABLED else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURITY_HTTPS_ENABLED
SECURE_HSTS_PRELOAD = SECURITY_HTTPS_ENABLED
SESSION_COOKIE_SECURE = SECURITY_HTTPS_ENABLED
CSRF_COOKIE_SECURE = SECURITY_HTTPS_ENABLED
SECURE_SSL_REDIRECT = CONFIG.SECURITY_HTTPS_REDIRECT_ENABLED

# Application definition
XADMIN_APPS = CONFIG.XADMIN_APPS

# 功能模块裁剪（软裁剪）：MODULE_PRESET 选基线（core/standard/full），
# MODULE_ENABLE / MODULE_DISABLE 做显式增删。模块清单、依赖校验与裁剪动作
# 见 common/core/modules.py（默认 full = 全部开启，行为与改造前一致）
MODULE_PRESET = CONFIG.MODULE_PRESET
MODULE_ENABLE = CONFIG.MODULE_ENABLE
MODULE_DISABLE = CONFIG.MODULE_DISABLE

# 表前缀设置
# 1.指定配置
# DB_PREFIX={
# 'system': 'abc_', # system app所有的表都加前缀 abc_
# 'system.config':'xxa_', # 仅system.config添加前缀 xxa_
# '': '', # 默认前缀
# }
#
# 2.全局配置
# DB_PREFIX='abc_'  : 所有表都添加 abc_
DB_PREFIX = CONFIG.DB_PREFIX

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "system.apps.SystemConfig",  # 系统管理
    "settings.apps.SettingsConfig",  # 设置相关
    "mfa.apps.MfaConfig",  # MFA / 敏感操作二次验证
    "notifications.apps.NotificationsConfig",  # 消息通知相关
    "captcha.apps.CaptchaConfig",  # 图片验证码
    "message.apps.MessageConfig",  # websocket 消息
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "rest_framework",
    "django_filters",
    "django_celery_results",
    "django_celery_beat",
    "imagekit",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    *XADMIN_APPS,
    "common.apps.CommonConfig",  # 这个放到最后, django ready
]

# PostgreSQL 专有索引（GinIndex / pg_trgm）静态存在于模型 Meta，该 app 必须参与模型
# 检查（postgres.E005），否则 `check --database` 失败会卡死服务启动（2026-09-18 部署事故根因）。
# 无条件注册：非 PG 后端下 app 仅注册检查与 lookups、不产生任何 DDL（建索引迁移 0010 有
# vendor 守卫）；若条件化，显式使用 mysql/sqlite3 的部署会踩同样的 E005。
INSTALLED_APPS.append("django.contrib.postgres")

if DEBUG or DEBUG_DEV:
    INSTALLED_APPS.insert(0, "daphne")  # 支持websocket

MIDDLEWARE = [
    "server.middleware.StartMiddleware",
    "server.middleware.RequestMiddleware",
    # 功能模块裁剪：停用模块的请求直接 404（无停用模块时零开销）
    "server.middleware.ModuleGateMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    # /admin/ 站点已启用且依赖 Session+CSRF，必须恢复该中间件；
    # DRF API 视图自带 csrf_exempt，Bearer 接口不受影响
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "server.middleware.RefererCheckMiddleware",
    "server.middleware.SQLCountMiddleware",
    # CSP（S3）：CSPModeMiddleware 必须排在 csp 中间件之前——响应阶段自内向外执行，
    # 它需要在 django-csp 生成策略头之后按系统配置改写/移除（disabled/report-only/enforce）
    "common.core.middleware.CSPModeMiddleware",
    "csp.middleware.CSPMiddleware",
    "common.core.middleware.ApiLoggingMiddleware",
    "server.middleware.EndMiddleware",
]

# CSP 策略（S3 落地，独立于 Office 预览）：django-csp 生成，运行期模式由
# CSPModeMiddleware + SysConfig.CSP_MODE 决定（默认 report-only 观察，再切 enforce）。
# 策略本体见 server/settings/csp.py（三层同源守护：本模块再导出 ↔ 页面层 nginx ↔ 隔离验证服务）。
from server.settings.csp import (  # noqa: E402,F401
    _CSP_DIRECTIVES,
    CONTENT_SECURITY_POLICY,
    CONTENT_SECURITY_POLICY_REPORT_ONLY,
)

# Prometheus 指标采集（默认关闭）：仅在显式启用时挂载，避免无谓开销与端点暴露。
# 开关与令牌**无条件导出**：读取方（common/api/metrics.py）走 getattr(settings, ...)，
# 漏导出会让端点永远 404（2026-09-16 实测踩中，与 SECURITY_AES_V1_DECRYPT_ENABLED 同类缺陷）
METRICS_ENABLED = CONFIG.METRICS_ENABLED
METRICS_TOKEN = CONFIG.METRICS_TOKEN
if METRICS_ENABLED:
    MIDDLEWARE.append("common.core.middleware.MetricsMiddleware")

# django-silk 性能剖析（性能基线）：config.yml 中 `SILK_ENABLED: true` 显式开启，
# 仅限 DEBUG/DEBUG_DEV 环境；剖析开销较大，k6 基线测定必须在关闭 silk 的状态下执行，
# silk 仅用于低并发下的单接口 SQL/profiling 剖析。开启后需 `python manage.py migrate` 创建 silk 表
if CONFIG.SILK_ENABLED:
    if not (DEBUG or DEBUG_DEV):
        raise ImproperlyConfigured("SILK_ENABLED 仅允许在 DEBUG/DEBUG_DEV 环境开启（性能剖析工具不可用于生产）")
    if "silk" not in INSTALLED_APPS:
        INSTALLED_APPS.append("silk")
        MIDDLEWARE.insert(0, "silk.middleware.SilkyMiddleware")
    SILKY_AUTHENTICATION = True  # /silk 面板要求登录
    SILKY_AUTHORISATION = True  # 且要求员工/超级管理员权限
    SILKY_MAX_RECORDED_REQUESTS = 10_000
    SILKY_MAX_RECORDED_REQUESTS_CHECK_PERCENT = 5  # 降低落库概率检查频率，减少剖析自身开销
    SILKY_PYTHON_PROFILER = True  # 请求级 Python profiling；压测排查时如干扰明显可关闭
    SILKY_PYTHON_PROFILER_RESULT_PATH = os.path.join(PROJECT_DIR, "tmp", "silk_profiles")
    SILKY_IGNORE_PATHS = ("/api/health", "/api/static", "^/media", "^/api/system/auth/captcha")

ROOT_URLCONF = "server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(PROJECT_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI_APPLICATION = 'server.wsgi.application'
ASGI_APPLICATION = "server.asgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Redis 配置
REDIS_HOST = CONFIG.REDIS_HOST
REDIS_PORT = CONFIG.REDIS_PORT
REDIS_PASSWORD = CONFIG.REDIS_PASSWORD

DEFAULT_CACHE_ID = CONFIG.DEFAULT_CACHE_ID
CHANNEL_LAYERS_CACHE_ID = CONFIG.CHANNEL_LAYERS_CACHE_ID
CELERY_BROKER_CACHE_ID = CONFIG.CELERY_BROKER_CACHE_ID
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/{DEFAULT_CACHE_ID}",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # 故障演练 2029-10 复测修复：Redis 冻结（容器 stop，连接挂起而非拒绝）时
            # socket 无超时会让请求挂在中间件/配置读取阶段（实测 10s+ 被 worker
            # timeout 打断、health 端点被拖挂）。局域网 redis 操作 <5ms，1s 超时充裕，
            # 冻结时快速失败（配合 ConfigCache 回落读库，见 common/core/config.py）。
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 8000,
                # 连接超时 0.2s：局域网建连正常 <1ms；冻结（连接挂起）时每个调用
                # 0.2s 快速失败（实测 1s 时多个串行调用累积到 10s，0.2s 收敛到秒级）
                "socket_connect_timeout": 0.2,
                # 读写超时 0.5s：正常操作 <10ms（大 pattern SCAN 留余量），仅兜底
                "socket_timeout": 0.5,
                "retry_on_timeout": False,
            },
            "PASSWORD": REDIS_PASSWORD,
            "DECODE_RESPONSES": True,
            "REDIS_CLIENT_KWARGS": {"health_check_interval": 30},
            # 故障演练 2029-10 复测（第二轮）：Redis 冻结时 TimeoutError 被
            # django_redis 转换为 ConnectionInterrupted，但默认继续向上抛——
            # DRF 限流器等框架层调用点不兜异常 → 请求 500（实测 health 返回
            # 500）。开启 IGNORE_EXCEPTIONS：读返回 None、写静默失败（标准降级
            # 语义：缓存不可用时 fail-open，业务回落数据源/重算）。
            "IGNORE_EXCEPTIONS": True,
        },
        "TIMEOUT": 60 * 15,
        "KEY_FUNCTION": "common.base.utils.redis_key_func",
        "REVERSE_KEY_FUNCTION": "common.base.utils.redis_reverse_key_func",
    },
}

# create database xadmin default character set utf8 COLLATE utf8_general_ci;
# grant all on xadmin.* to server@'127.0.0.1' identified by 'KGzKjZpWBp4R4RSa';
# python manage.py makemigrations
# python manage.py migrate


def _resolve_db_engine(value: str) -> str:
    """数据库后端解析：短名 → Django 后端路径，其余按完整路径原样使用（第三方后端）。

    短名清单与 config_example.yml 的注释一致（sqlite3 / mysql / oracle / postgresql / vastbase）。
    """
    name = value.lower()
    if name in ("mysql", "oracle", "postgresql", "sqlite3"):
        return f"django.db.backends.{name}"
    if name == "vastbase":
        return "django_vastbase_backend"
    return value


DB_OPTIONS = {}
DB_ENGINE = CONFIG.DB_ENGINE.lower()
ENGINE = _resolve_db_engine(CONFIG.DB_ENGINE)

if DB_ENGINE == "postgresql":
    # 连接建立超时（演练第五轮·网络分区修复，2026-09-16）：PG 断网时 TCP 无响应，
    # 无该超时会让 DB 操作挂到 TCP 默认超时（实测 health 20s+ 完全无响应）；
    # 局域网建连 <10ms，3s 充裕且保证故障时快速失败（池/非池模式均透传 psycopg）
    DB_OPTIONS["connect_timeout"] = 3
    # 半开连接快速失败（第十七轮·真丢包演练修复，2026-09-18）：TCP 丢包时已建立连接
    # 进入半开态（对端收不到包、本端不知情），查询/SELECT 1 判活阻塞在 recv，无 socket 级
    # 超时则要等 TCP 重传耗竭（Linux 默认 ~15 分钟）——期间 worker 同步处理线程被逐个占死
    # （实测 health 亦排队无响应，~1 分钟自愈依赖 TCP 重传成功）。tcp_user_timeout 让内核在
    # 未确认数据超时后强制断开连接（recv 立即报错 → 池淘汰重建）；keepalives 三件套用于
    # 空闲连接的探活。注：tcp_user_timeout 仅 Linux 生效（libpq 在其它平台忽略该参数）。
    DB_OPTIONS["tcp_user_timeout"] = 30000  # ms；未确认数据 30s 即断开
    DB_OPTIONS["keepalives"] = 1
    DB_OPTIONS["keepalives_idle"] = 30  # 空闲 30s 开始探测
    DB_OPTIONS["keepalives_interval"] = 10  # 探测间隔 10s
    DB_OPTIONS["keepalives_count"] = 3  # 3 次未应答判定连接死亡

# ASGI 形态下 ASGIHandler 为每请求创建独立线程（ThreadSensitiveContext），
# 线程随请求结束消亡，持久连接机制（CONN_MAX_AGE）在此形态下无效，等效每请求新建 DB
# 连接——压测 ~600rps 时临时端口耗尽致 13-27% 500。postgresql 引擎默认启用 Django 5.1+
# server 端连接池（psycopg3 + psycopg_pool）；池模式下 CONN_MAX_AGE 必须为 0，
# CONN_HEALTH_CHECKS 使池在取用连接前做轻量存活校验
DB_POOL_ENABLED = DB_ENGINE == "postgresql" and bool(CONFIG.DB_POOL)
if DB_POOL_ENABLED:
    # 池判活回调替换（真实 SELECT 1）：psycopg_pool 默认 check_connection 用空查询，
    # 检测不到「PG 重启后半开连接」（2030-03 演练实测坏连接反复被取出、服务不自愈，
    # 直到进程重启）。Django 硬编码读取 ConnectionPool.check_connection 且不允许
    # OPTIONS["pool"] 重复传 check（实测 duplicate keyword 启动失败），故在配置期
    # 替换该静态方法——settings 加载早于任何池创建，对全部池生效。
    from psycopg_pool import ConnectionPool

    from common.db import check_db_connection

    ConnectionPool.check_connection = staticmethod(check_db_connection)

    DB_OPTIONS["pool"] = {
        "min_size": int(CONFIG.DB_POOL_MIN_SIZE),
        "max_size": max(int(CONFIG.DB_POOL_MIN_SIZE), int(CONFIG.DB_POOL_MAX_SIZE)),
        # 取用连接的最长等待（psycopg_pool 默认 30s）：故障（半开/丢包）时池重建期间
        # 请求快速失败（≤5s），而不是每个请求排队等满 30s（第十七轮演练复演实测）。
        # 正常负载取用 <10ms，5s 余量充足；容量由 min/max_size 控制不受影响。
        "timeout": 5,
        # 失败连接的重连调度间隔（psycopg_pool 默认 300s）：DB 恢复后健康指示 10s 级回正，
        # 而不是最长等 5 分钟（第十七轮复演观察：删规则后 db 指示恢复慢且抖动）。
        "reconnect_timeout": 10,
    }

DATABASES = {
    "default": {
        "ENGINE": ENGINE,
        "NAME": CONFIG.DB_DATABASE,
        "HOST": CONFIG.DB_HOST,
        "PORT": CONFIG.DB_PORT,
        "USER": CONFIG.DB_USER,
        "PASSWORD": CONFIG.DB_PASSWORD,
        "ATOMIC_REQUESTS": True,
        "CONN_MAX_AGE": 0 if DB_POOL_ENABLED else 600,
        "CONN_HEALTH_CHECKS": DB_POOL_ENABLED,
        "OPTIONS": DB_OPTIONS,
    }
}

if DB_ENGINE == "mysql":
    DB_OPTIONS["init_command"] = "SET sql_mode='STRICT_TRANS_TABLES'"
    DB_OPTIONS["charset"] = "utf8mb4"
    DB_OPTIONS["collation"] = "utf8mb4_bin"

# https://docs.djangoproject.com/zh-hans/5.0/topics/db/multi-db/#automatic-database-routing
# 读写分离 可能会出现 the current database router prevents this relation.
# 1.项目设置了router读写分离，且在ORM create()方法中，使用了前边filter()方法得到的数据，
# 2.由于django是惰性查询，前边的filter()并没有立即查询，而是在create()中引用了filter()的数据时，执行了filter()，
# 3.此时写操作的db指针指向write_db，filter()的db指针指向read_db，两者发生冲突，导致服务禁止了此次与mysql的交互
# 解决办法：
# 在前边filter()方法中，使用using()方法，使filter()方法立即与数据库交互，查出数据。
# Author.objects.using("default")
# >>> p = Person(name="Fred")
# >>> p.save(using="second")  # (statement 2)

DATABASE_ROUTERS = ["common.core.db.router.DBRouter"]

# websocket 消息需要用到redis的消息发布订阅
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "common.cache.channel.RedisChannelLayer",
        # "BACKEND": "channels_redis.pubsub.RedisPubSubChannelLayer",
        "CONFIG": {
            # 注意：这里必须用 dict 形式的 host，channels_redis 会把额外 kwargs
            # 透传给 redis-py ConnectionPool。redis-py 8.x 起默认 socket_timeout
            # 从 None 改为 5s，而 channels_redis 的 receive() 使用 BZPOPMIN
            # 服务端阻塞 5s 长轮询，两个 5s 竞速会导致偶发
            # "Timeout reading from redis" 并杀死整个 websocket consumer。
            # 显式关闭 socket_timeout 以恢复无限阻塞等待。
            "hosts": [
                {
                    "address": f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{CHANNEL_LAYERS_CACHE_ID}",
                    "socket_timeout": None,
                }
            ],
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
# http://www.i18nguy.com/unicode/language-identifiers.html
# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = CONFIG.LANGUAGE_CODE

TIME_ZONE = CONFIG.TIME_ZONE

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = "system.UserInfo"

# 认证 backend 链：LDAP bind 在前。LdapBindBackend 内部按
# LDAP_AUTH_ENABLED / LDAP_AUTH_PRIORITY 动态让位 ModelBackend，
# 关闭/降级时行为与纯本地账密完全一致
AUTHENTICATION_BACKENDS = [
    "system.ldap.auth.LdapBindBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "api/static/"
DATA_DIR = os.path.join(PROJECT_DIR, "data")
STATIC_ROOT = os.path.join(DATA_DIR, "static")

# STATICFILES_FINDERS = (
#     "django.contrib.staticfiles.finders.FileSystemFinder",
#     "django.contrib.staticfiles.finders.AppDirectoriesFinder"
# )
# 收集静态文件
# python manage.py collectstatic


# Media配置
MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(DATA_DIR, "upload")
from server.settings.storage import STORAGES  # noqa: E402,F401  可插拔存储后端装配（P-4，本体见该模块）

# 审计日志冷归档目录（P-5）：默认 DATA_DIR/log_archive；环境变量 LOG_ARCHIVE_DIR 可覆盖
# （如指向异地同步目录。注意不要直接放备份卷根目录——db_backup.sh 的 prune_local 会按
#  *.sql.gz / *.media.tar.gz / *.sha256 后缀清理存量文件，见 docs/ops/pitr.md「审计冷归档」）
LOG_ARCHIVE_DIR = os.environ.get("LOG_ARCHIVE_DIR") or os.path.join(DATA_DIR, "log_archive")
FILE_UPLOAD_SIZE = CONFIG.FILE_UPLOAD_SIZE
PICTURE_UPLOAD_SIZE = CONFIG.PICTURE_UPLOAD_SIZE
FILE_UPLOAD_HANDLERS = [
    "django.core.files.uploadhandler.MemoryFileUploadHandler",
    "django.core.files.uploadhandler.TemporaryFileUploadHandler",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# I18N translation
LOCALE_PATHS = [
    os.path.join(PROJECT_DIR, "locale"),
]

CACHE_KEY_TEMPLATE = {
    "config_key": "config",
    "make_token_key": "make_token",
    "download_url_key": "download_url",
    "pending_state_key": "pending_state",
    "websocket_group_key": "websocket_group",
    "upload_part_info_key": "upload_part_info",
    "black_access_token_key": "black_access_token",
    "common_resource_ids_key": "common_resource_ids",
    "websocket_message_result_key": "websocket_message_result",
    "mfa_confirm_state_key": "mfa_confirm_state",
    "mfa_otp_bind_key": "mfa_otp_bind",
    "mfa_otp_used_key": "mfa_otp_used",
    "user_token_revoked_key": "user_token_revoked",
    "session_token_revoked_key": "session_token_revoked",
}

APPEND_SLASH = False

HTTP_BIND_HOST = CONFIG.HTTP_BIND_HOST
HTTP_LISTEN_PORT = CONFIG.HTTP_LISTEN_PORT
GUNICORN_MAX_WORKER = CONFIG.GUNICORN_MAX_WORKER
CELERY_WORKER_COUNT = CONFIG.CELERY_WORKER_COUNT
# heavy 队列 worker 配置（见 conf.py 说明）
CELERY_HEAVY_POOL = CONFIG.CELERY_HEAVY_POOL
CELERY_HEAVY_CONCURRENCY = CONFIG.CELERY_HEAVY_CONCURRENCY
# celery flower 任务监控配置
CELERY_FLOWER_PORT = CONFIG.CELERY_FLOWER_PORT
CELERY_FLOWER_HOST = CONFIG.CELERY_FLOWER_HOST
CELERY_FLOWER_AUTH = CONFIG.CELERY_FLOWER_AUTH

# 错误聚合（SENTRY_DSN 为空时零开销），在 settings 加载期尽早初始化
from ..monitoring import init_monitoring  # noqa: E402

init_monitoring()
