#!/usr/bin/env python
# -*- coding:utf-8 -*-
# project : xadmin-server
# filename : setting
# author : ly_13
# date : 10/18/2024
import os

from ..const import CONFIG, PROJECT_DIR

# 密码安全配置
SECURITY_PASSWORD_MIN_LENGTH = CONFIG.SECURITY_PASSWORD_MIN_LENGTH
SECURITY_ADMIN_USER_PASSWORD_MIN_LENGTH = CONFIG.SECURITY_ADMIN_USER_PASSWORD_MIN_LENGTH
SECURITY_PASSWORD_UPPER_CASE = CONFIG.SECURITY_PASSWORD_UPPER_CASE
SECURITY_PASSWORD_LOWER_CASE = CONFIG.SECURITY_PASSWORD_LOWER_CASE
SECURITY_PASSWORD_NUMBER = CONFIG.SECURITY_PASSWORD_NUMBER
SECURITY_PASSWORD_SPECIAL_CHAR = CONFIG.SECURITY_PASSWORD_SPECIAL_CHAR
SECURITY_PASSWORD_RULES = [
    "SECURITY_PASSWORD_MIN_LENGTH",
    "SECURITY_PASSWORD_UPPER_CASE",
    "SECURITY_PASSWORD_LOWER_CASE",
    "SECURITY_PASSWORD_NUMBER",
    "SECURITY_PASSWORD_SPECIAL_CHAR",
]
# 泄露密码库校验开关（内置离线弱口令清单，默认关闭渐进启用）
SECURITY_PASSWORD_LEAK_CHECK_ENABLED = CONFIG.SECURITY_PASSWORD_LEAK_CHECK_ENABLED
# 密码历史：最近 N 次不可复用（0 = 关闭）
SECURITY_PASSWORD_HISTORY_COUNT = CONFIG.SECURITY_PASSWORD_HISTORY_COUNT
# 密码有效期（天数，0 = 永不过期；date_password_updated 为空的存量用户 = 宽限期）
SECURITY_PASSWORD_EXPIRATION_DAYS = CONFIG.SECURITY_PASSWORD_EXPIRATION_DAYS
# AES 旧格式（Salted__）解密灰度开关：默认开启保持存量前端兼容，全量升级 v2 后关闭，
# 关闭后旧格式一律按非法输入拒绝（返回空串）。读取方 common/base/utils.py 走
# getattr(settings, ...) —— 必须同步转发，漏转发会让开关永远落默认值（形同虚设）。
SECURITY_AES_V1_DECRYPT_ENABLED = CONFIG.SECURITY_AES_V1_DECRYPT_ENABLED

# 用户登录限制的规则
SECURITY_LOGIN_LIMIT_COUNT = CONFIG.SECURITY_LOGIN_LIMIT_COUNT
SECURITY_LOGIN_LIMIT_TIME = CONFIG.SECURITY_LOGIN_LIMIT_TIME  # Unit: minute
SECURITY_CHECK_DIFFERENT_CITY_LOGIN = CONFIG.SECURITY_CHECK_DIFFERENT_CITY_LOGIN
# 新设备/新 IP 登录提醒（异常登录提醒第二维度）
SECURITY_ABNORMAL_LOGIN_ALERT_ENABLED = CONFIG.SECURITY_ABNORMAL_LOGIN_ALERT_ENABLED
SECURITY_LOGIN_BASELINE_DAYS = CONFIG.SECURITY_LOGIN_BASELINE_DAYS
# 登录IP限制的规则
SECURITY_LOGIN_IP_BLACK_LIST = CONFIG.SECURITY_LOGIN_IP_BLACK_LIST
SECURITY_LOGIN_IP_WHITE_LIST = CONFIG.SECURITY_LOGIN_IP_WHITE_LIST
SECURITY_LOGIN_IP_LIMIT_COUNT = CONFIG.SECURITY_LOGIN_IP_LIMIT_COUNT
SECURITY_LOGIN_IP_LIMIT_TIME = CONFIG.SECURITY_LOGIN_IP_LIMIT_TIME

# 登陆规则
SECURITY_LOGIN_ACCESS_ENABLED = CONFIG.SECURITY_LOGIN_ACCESS_ENABLED
SECURITY_LOGIN_CAPTCHA_ENABLED = CONFIG.SECURITY_LOGIN_CAPTCHA_ENABLED
SECURITY_LOGIN_ENCRYPTED_ENABLED = CONFIG.SECURITY_LOGIN_ENCRYPTED_ENABLED
SECURITY_LOGIN_TEMP_TOKEN_ENABLED = CONFIG.SECURITY_LOGIN_TEMP_TOKEN_ENABLED
SECURITY_LOGIN_BY_EMAIL_ENABLED = CONFIG.SECURITY_LOGIN_BY_EMAIL_ENABLED
SECURITY_LOGIN_BY_SMS_ENABLED = CONFIG.SECURITY_LOGIN_BY_SMS_ENABLED
SECURITY_LOGIN_BY_BASIC_ENABLED = CONFIG.SECURITY_LOGIN_BY_BASIC_ENABLED

# 注册规则
SECURITY_REGISTER_ACCESS_ENABLED = CONFIG.SECURITY_REGISTER_ACCESS_ENABLED
SECURITY_REGISTER_CAPTCHA_ENABLED = CONFIG.SECURITY_REGISTER_CAPTCHA_ENABLED
SECURITY_REGISTER_ENCRYPTED_ENABLED = CONFIG.SECURITY_REGISTER_ENCRYPTED_ENABLED
SECURITY_REGISTER_TEMP_TOKEN_ENABLED = CONFIG.SECURITY_REGISTER_TEMP_TOKEN_ENABLED
SECURITY_REGISTER_BY_EMAIL_ENABLED = CONFIG.SECURITY_REGISTER_BY_EMAIL_ENABLED
SECURITY_REGISTER_BY_SMS_ENABLED = CONFIG.SECURITY_REGISTER_BY_SMS_ENABLED
SECURITY_REGISTER_BY_BASIC_ENABLED = CONFIG.SECURITY_REGISTER_BY_BASIC_ENABLED
# 忘记密码规则
SECURITY_RESET_PASSWORD_ACCESS_ENABLED = CONFIG.SECURITY_RESET_PASSWORD_ACCESS_ENABLED
SECURITY_RESET_PASSWORD_CAPTCHA_ENABLED = CONFIG.SECURITY_RESET_PASSWORD_CAPTCHA_ENABLED
SECURITY_RESET_PASSWORD_TEMP_TOKEN_ENABLED = CONFIG.SECURITY_RESET_PASSWORD_TEMP_TOKEN_ENABLED
SECURITY_RESET_PASSWORD_ENCRYPTED_ENABLED = CONFIG.SECURITY_RESET_PASSWORD_ENCRYPTED_ENABLED
SECURITY_RESET_PASSWORD_BY_EMAIL_ENABLED = CONFIG.SECURITY_RESET_PASSWORD_BY_EMAIL_ENABLED
SECURITY_RESET_PASSWORD_BY_SMS_ENABLED = CONFIG.SECURITY_RESET_PASSWORD_BY_SMS_ENABLED

# 绑定邮箱
SECURITY_BIND_EMAIL_ACCESS_ENABLED = CONFIG.SECURITY_BIND_EMAIL_ACCESS_ENABLED
SECURITY_BIND_EMAIL_CAPTCHA_ENABLED = CONFIG.SECURITY_BIND_EMAIL_CAPTCHA_ENABLED
SECURITY_BIND_EMAIL_TEMP_TOKEN_ENABLED = CONFIG.SECURITY_BIND_EMAIL_TEMP_TOKEN_ENABLED
SECURITY_BIND_EMAIL_ENCRYPTED_ENABLED = CONFIG.SECURITY_BIND_EMAIL_ENCRYPTED_ENABLED

# 绑定手机
SECURITY_BIND_PHONE_ACCESS_ENABLED = CONFIG.SECURITY_BIND_PHONE_ACCESS_ENABLED
SECURITY_BIND_PHONE_CAPTCHA_ENABLED = CONFIG.SECURITY_BIND_PHONE_CAPTCHA_ENABLED
SECURITY_BIND_PHONE_TEMP_TOKEN_ENABLED = CONFIG.SECURITY_BIND_PHONE_TEMP_TOKEN_ENABLED
SECURITY_BIND_PHONE_ENCRYPTED_ENABLED = CONFIG.SECURITY_BIND_PHONE_ENCRYPTED_ENABLED

# 临时令牌（tmp_token）有效期（秒）：登录/注册/重置/绑定加密握手共用
SECURITY_TEMP_TOKEN_EXPIRE = CONFIG.SECURITY_TEMP_TOKEN_EXPIRE

# MFA / 敏感操作二次验证
SECURITY_MFA_CONFIRM_ENABLED = CONFIG.SECURITY_MFA_CONFIRM_ENABLED
SECURITY_MFA_CONFIRM_BACKENDS = CONFIG.SECURITY_MFA_CONFIRM_BACKENDS
SECURITY_MFA_VERIFY_TTL = CONFIG.SECURITY_MFA_VERIFY_TTL  # Unit: second
SECURITY_MFA_PASSWORD_CONFIRM_TTL = CONFIG.SECURITY_MFA_PASSWORD_CONFIRM_TTL  # Unit: second
SECURITY_MFA_LOGIN_PROTECT_ENABLED = CONFIG.SECURITY_MFA_LOGIN_PROTECT_ENABLED
SECURITY_MFA_LOGIN_TOKEN_TTL = CONFIG.SECURITY_MFA_LOGIN_TOKEN_TTL  # Unit: second
SECURITY_MFA_OTP_VALID_WINDOW = CONFIG.SECURITY_MFA_OTP_VALID_WINDOW
SECURITY_MFA_OTP_ISSUER = CONFIG.SECURITY_MFA_OTP_ISSUER
# 认证方式策略（F-9）：全局允许方式白名单（空 = 全部后端）
SECURITY_MFA_METHODS = CONFIG.SECURITY_MFA_METHODS
# 账号安全风险巡检（F-6）
SECURITY_PASSWORD_STALE_DAYS = CONFIG.SECURITY_PASSWORD_STALE_DAYS
SECURITY_ACCOUNT_IDLE_DAYS = CONFIG.SECURITY_ACCOUNT_IDLE_DAYS
SECURITY_SUPERUSER_MAX_COUNT = CONFIG.SECURITY_SUPERUSER_MAX_COUNT
# 登录访问策略（F-7）：并发会话上限（0 = 不限）
SECURITY_LOGIN_MAX_SESSIONS = CONFIG.SECURITY_LOGIN_MAX_SESSIONS
# 上传安全策略（F-8）与文件访问日志保留期
SECURITY_UPLOAD_BLOCK_EXTENSIONS = CONFIG.SECURITY_UPLOAD_BLOCK_EXTENSIONS
SECURITY_UPLOAD_ALLOW_EXTENSIONS = CONFIG.SECURITY_UPLOAD_ALLOW_EXTENSIONS
FILE_ACCESS_LOG_KEEP_DAYS = CONFIG.FILE_ACCESS_LOG_KEEP_DAYS

# 资源告警阈值
SECURITY_MONITOR_DISK_USED_MAX = CONFIG.SECURITY_MONITOR_DISK_USED_MAX
SECURITY_MONITOR_MEMORY_USED_MAX = CONFIG.SECURITY_MONITOR_MEMORY_USED_MAX
SECURITY_MONITOR_CPU_PERCENT_MAX = CONFIG.SECURITY_MONITOR_CPU_PERCENT_MAX
SECURITY_MONITOR_CPU_LOAD_MAX = CONFIG.SECURITY_MONITOR_CPU_LOAD_MAX

# 基本配置
SITE_URL = CONFIG.SITE_URL
FRONT_END_WEB_WATERMARK_ENABLED = CONFIG.FRONT_END_WEB_WATERMARK_ENABLED  # 前端水印展示
FRONT_END_WEB_WATERMARK_TEXT = CONFIG.FRONT_END_WEB_WATERMARK_TEXT  # 前端水印文案（留空 = 用户名-昵称-时间）
FRONT_END_WEB_WATERMARK_PATHS = CONFIG.FRONT_END_WEB_WATERMARK_PATHS  # 前端水印生效页面（逗号分隔路由前缀）
PERMISSION_FIELD_ENABLED = CONFIG.PERMISSION_FIELD_ENABLED  # 字段权限控制
PERMISSION_DATA_ENABLED = CONFIG.PERMISSION_DATA_ENABLED  # 数据权限控制
REFERER_CHECK_ENABLED = CONFIG.REFERER_CHECK_ENABLED  # referer 校验
EXPORT_MAX_LIMIT = CONFIG.EXPORT_MAX_LIMIT  # 限制导出数据数量
# 软删除回收站保留天数（purge 周期任务按此物理清除）
RECYCLE_BIN_RETENTION_DAYS = CONFIG.RECYCLE_BIN_RETENTION_DAYS
# 字段级审计 diff 白名单（模型 _meta.label 列表，空=关闭）
AUDIT_DIFF_MODELS = CONFIG.AUDIT_DIFF_MODELS

# 验证码配置
VERIFY_CODE_TTL = CONFIG.VERIFY_CODE_TTL  # Unit: second
VERIFY_CODE_LIMIT = CONFIG.VERIFY_CODE_LIMIT
VERIFY_CODE_LENGTH = CONFIG.VERIFY_CODE_LENGTH
VERIFY_CODE_LOWER_CASE = CONFIG.VERIFY_CODE_LOWER_CASE
VERIFY_CODE_UPPER_CASE = CONFIG.VERIFY_CODE_UPPER_CASE
VERIFY_CODE_DIGIT_CASE = CONFIG.VERIFY_CODE_DIGIT_CASE

# LDAP/AD 目录同步：默认值在 server/conf.py；运行期经 Setting 体系热更新覆盖
LDAP_AUTH_ENABLED = CONFIG.LDAP_AUTH_ENABLED
LDAP_AUTH_PRIORITY = CONFIG.LDAP_AUTH_PRIORITY
LDAP_AUTH_AUTO_CREATE = CONFIG.LDAP_AUTH_AUTO_CREATE
LDAP_SERVER_URI = CONFIG.LDAP_SERVER_URI
LDAP_START_TLS = CONFIG.LDAP_START_TLS
LDAP_BIND_DN = CONFIG.LDAP_BIND_DN
LDAP_BIND_PASSWORD = CONFIG.LDAP_BIND_PASSWORD
LDAP_CONNECT_TIMEOUT = CONFIG.LDAP_CONNECT_TIMEOUT
LDAP_USER_SEARCH_BASE = CONFIG.LDAP_USER_SEARCH_BASE
LDAP_USER_FILTER = CONFIG.LDAP_USER_FILTER
LDAP_ATTR_USERNAME = CONFIG.LDAP_ATTR_USERNAME
LDAP_ATTR_NICKNAME = CONFIG.LDAP_ATTR_NICKNAME
LDAP_ATTR_EMAIL = CONFIG.LDAP_ATTR_EMAIL
LDAP_ATTR_PHONE = CONFIG.LDAP_ATTR_PHONE
LDAP_DEPT_ENABLED = CONFIG.LDAP_DEPT_ENABLED
LDAP_DEPT_SEARCH_BASE = CONFIG.LDAP_DEPT_SEARCH_BASE
LDAP_SYNC_ENABLED = CONFIG.LDAP_SYNC_ENABLED
LDAP_SYNC_AUTO_CREATE = CONFIG.LDAP_SYNC_AUTO_CREATE
LDAP_SYNC_MISSING_POLICY = CONFIG.LDAP_SYNC_MISSING_POLICY
LDAP_ATTR_GROUPS = CONFIG.LDAP_ATTR_GROUPS
LDAP_GROUP_ROLE_MAP = CONFIG.LDAP_GROUP_ROLE_MAP
LDAP_SYNC_PAGE_SIZE = CONFIG.LDAP_SYNC_PAGE_SIZE

# 企业 IM 通知渠道
DINGTALK_ENABLED = CONFIG.DINGTALK_ENABLED
DINGTALK_APP_KEY = CONFIG.DINGTALK_APP_KEY
DINGTALK_APP_SECRET = CONFIG.DINGTALK_APP_SECRET
DINGTALK_AGENT_ID = CONFIG.DINGTALK_AGENT_ID
WECOM_ENABLED = CONFIG.WECOM_ENABLED
WECOM_CORP_ID = CONFIG.WECOM_CORP_ID
WECOM_CORP_SECRET = CONFIG.WECOM_CORP_SECRET
WECOM_AGENT_ID = CONFIG.WECOM_AGENT_ID
FEISHU_ENABLED = CONFIG.FEISHU_ENABLED
FEISHU_APP_ID = CONFIG.FEISHU_APP_ID
FEISHU_APP_SECRET = CONFIG.FEISHU_APP_SECRET

# AI 助手
AI_ASSISTANT_ENABLED = CONFIG.AI_ASSISTANT_ENABLED
AI_BASE_URL = CONFIG.AI_BASE_URL
AI_API_KEY = CONFIG.AI_API_KEY
AI_MODEL = CONFIG.AI_MODEL
AI_TIMEOUT = CONFIG.AI_TIMEOUT
AI_NL_QUERY_ENABLED = CONFIG.AI_NL_QUERY_ENABLED
# 灰度开关：不映射则 config.yml 里配置不生效（只能靠 Setting 表热更新注入）
AI_ACTION_ENABLED = CONFIG.AI_ACTION_ENABLED
# AI 采样/行为参数（多档案回落通路）
AI_TEMPERATURE = CONFIG.AI_TEMPERATURE
AI_MAX_TOKENS = CONFIG.AI_MAX_TOKENS
AI_STRUCTURED_MAX_TOKENS = CONFIG.AI_STRUCTURED_MAX_TOKENS
# AI-6 安全护栏（引用数据隔离 / 注入标记 / 输出脱敏，默认开）
AI_GUARD_ENABLED = CONFIG.AI_GUARD_ENABLED
AI_OUTPUT_MASK_ENABLED = CONFIG.AI_OUTPUT_MASK_ENABLED
# AI-2 原生 function calling 双轨（默认关，能力探测通过后可开启）
AI_NATIVE_TOOLS_ENABLED = CONFIG.AI_NATIVE_TOOLS_ENABLED
# AI-5 用量配额（0 = 不限）
AI_QUOTA_USER_DAILY_CALLS = CONFIG.AI_QUOTA_USER_DAILY_CALLS
AI_QUOTA_USER_DAILY_TOKENS = CONFIG.AI_QUOTA_USER_DAILY_TOKENS
AI_QUOTA_MAX_CONCURRENT_STREAMS = CONFIG.AI_QUOTA_MAX_CONCURRENT_STREAMS
AI_TOP_P = CONFIG.AI_TOP_P
AI_FREQUENCY_PENALTY = CONFIG.AI_FREQUENCY_PENALTY
AI_PRESENCE_PENALTY = CONFIG.AI_PRESENCE_PENALTY
AI_STOP = CONFIG.AI_STOP
AI_SEED = CONFIG.AI_SEED
AI_MAX_RETRIES = CONFIG.AI_MAX_RETRIES
AI_CONTEXT_LIMIT = CONFIG.AI_CONTEXT_LIMIT
AI_PERSONA = CONFIG.AI_PERSONA

# 邮件配置
EMAIL_ENABLED = CONFIG.EMAIL_ENABLED
EMAIL_HOST = CONFIG.EMAIL_HOST
EMAIL_PORT = CONFIG.EMAIL_PORT
EMAIL_HOST_USER = CONFIG.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = CONFIG.EMAIL_HOST_PASSWORD
EMAIL_FROM = CONFIG.EMAIL_FROM
EMAIL_RECIPIENT = CONFIG.EMAIL_RECIPIENT
EMAIL_SUBJECT_PREFIX = CONFIG.EMAIL_SUBJECT_PREFIX
EMAIL_USE_SSL = CONFIG.EMAIL_USE_SSL
EMAIL_USE_TLS = CONFIG.EMAIL_USE_TLS

# 短信配置
SMS_ENABLED = CONFIG.SMS_ENABLED
SMS_BACKEND = CONFIG.SMS_BACKEND
SMS_TEST_PHONE = CONFIG.SMS_TEST_PHONE
# 短信通知模板（通知渠道用；未配置时渠道自动降级为不可用）
SMS_NOTIFY_SIGN_NAME = CONFIG.SMS_NOTIFY_SIGN_NAME
SMS_NOTIFY_TEMPLATE_CODE = CONFIG.SMS_NOTIFY_TEMPLATE_CODE
SMS_NOTIFY_TEMPLATE_PARAM_KEY = CONFIG.SMS_NOTIFY_TEMPLATE_PARAM_KEY

# 阿里云短信配置
ALIBABA_ACCESS_KEY_ID = CONFIG.ALIBABA_ACCESS_KEY_ID
ALIBABA_ACCESS_KEY_SECRET = CONFIG.ALIBABA_ACCESS_KEY_SECRET
ALIBABA_VERIFY_SIGN_NAME = CONFIG.ALIBABA_VERIFY_SIGN_NAME
ALIBABA_VERIFY_TEMPLATE_CODE = CONFIG.ALIBABA_VERIFY_TEMPLATE_CODE

# 图片验证码
CAPTCHA_IMAGE_SIZE = CONFIG.CAPTCHA_IMAGE_SIZE  # 设置 captcha 图片大小
CAPTCHA_CHALLENGE_FUNCT = CONFIG.CAPTCHA_CHALLENGE_FUNCT
CAPTCHA_LENGTH = CONFIG.CAPTCHA_LENGTH  # 字符个数,仅针对随机字符串生效
CAPTCHA_TIMEOUT = CONFIG.CAPTCHA_TIMEOUT  # 超时(minutes)
CAPTCHA_FONT_SIZE = CONFIG.CAPTCHA_FONT_SIZE
CAPTCHA_BACKGROUND_COLOR = CONFIG.CAPTCHA_BACKGROUND_COLOR
CAPTCHA_FOREGROUND_COLOR = CONFIG.CAPTCHA_FOREGROUND_COLOR
CAPTCHA_NOISE_FUNCTIONS = CONFIG.CAPTCHA_NOISE_FUNCTIONS

# 下面图片验证码 默认配置
CAPTCHA_OUTPUT_FORMAT = "%(image)s %(text_field)s %(hidden_field)s "
# CAPTCHA_NOISE_FUNCTIONS = ("captcha.helpers.noise_arcs", "captcha.helpers.noise_dots")
# CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge'
CAPTCHA_FONT_PATH = os.path.join(PROJECT_DIR, "captcha", "fonts", "Vera.ttf")
CAPTCHA_LETTER_ROTATION = (-35, 35)
CAPTCHA_FILTER_FUNCTIONS = ("captcha.helpers.post_smooth",)
CAPTCHA_PUNCTUATION = """_"',.;:-"""
CAPTCHA_FLITE_PATH = None
CAPTCHA_SOX_PATH = None
CAPTCHA_MATH_CHALLENGE_OPERATOR = "*"
CAPTCHA_GET_FROM_POOL = False
CAPTCHA_GET_FROM_POOL_TIMEOUT = 5
CAPTCHA_2X_IMAGE = True
