# Generated by Django 6.0.8 on 2026-10-05 05:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataMaskRule",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                (
                    "model",
                    models.CharField(
                        help_text="Model label like system.userinfo", max_length=128, verbose_name="Model"
                    ),
                ),
                ("field", models.CharField(max_length=64, verbose_name="Field")),
                (
                    "mask_type",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("idcard", "ID card"),
                            ("email", "Email"),
                            ("name", "Name"),
                            ("bankcard", "Bank card"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=16,
                        verbose_name="Mask type",
                    ),
                ),
                ("keep_head", models.PositiveSmallIntegerField(default=3, verbose_name="Keep head")),
                ("keep_tail", models.PositiveSmallIntegerField(default=2, verbose_name="Keep tail")),
                ("mask_char", models.CharField(default="*", max_length=4, verbose_name="Mask char")),
                ("pattern", models.CharField(blank=True, max_length=255, null=True, verbose_name="Custom pattern")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                ("sort", models.IntegerField(default=0, verbose_name="Sort")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True, help_text="Empty = all non-superuser", to="identity.userrole", verbose_name="Roles"
                    ),
                ),
            ],
            options={
                "verbose_name": "Data mask rule",
                "ordering": ("sort", "created_time"),
                "indexes": [models.Index(fields=["model", "field"], name="idx_datamask_model_field")],
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("module", models.CharField(blank=True, max_length=64, null=True, verbose_name="Module")),
                ("path", models.CharField(blank=True, max_length=400, null=True, verbose_name="URL path")),
                ("object_pk", models.CharField(blank=True, max_length=64, null=True, verbose_name="Object pk")),
                ("body", models.TextField(blank=True, null=True, verbose_name="Request body")),
                ("method", models.CharField(blank=True, max_length=8, null=True, verbose_name="Request method")),
                ("ipaddress", models.GenericIPAddressField(blank=True, null=True, verbose_name="IpAddress")),
                ("browser", models.CharField(blank=True, max_length=64, null=True, verbose_name="Browser")),
                ("system", models.CharField(blank=True, max_length=64, null=True, verbose_name="System")),
                ("response_code", models.IntegerField(blank=True, null=True, verbose_name="Response code")),
                ("response_result", models.TextField(blank=True, null=True, verbose_name="Response result")),
                ("status_code", models.IntegerField(blank=True, null=True, verbose_name="Status code")),
                ("request_uuid", models.UUIDField(blank=True, null=True, verbose_name="Request ID")),
                ("exec_time", models.FloatField(blank=True, null=True, verbose_name="Execution time")),
                ("changes", models.TextField(blank=True, null=True, verbose_name="Changed fields")),
                (
                    "auth_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("jwt", "JWT"),
                            ("pat", "Personal access token"),
                            ("scim", "SCIM directory sync"),
                            ("ldap", "LDAP directory sync"),
                            ("ai", "AI assistant"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="Auth type",
                    ),
                ),
                ("token_pk", models.BigIntegerField(blank=True, null=True, verbose_name="Token pk")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation log",
                "verbose_name_plural": "Operation log",
                "ordering": ("-created_time",),
                "indexes": [
                    models.Index(fields=["created_time"], name="idx_oplog_created"),
                    models.Index(fields=["module", "created_time"], name="idx_oplog_module_created"),
                    models.Index(fields=["request_uuid"], name="idx_oplog_request_uuid"),
                    models.Index(fields=["exec_time"], name="idx_oplog_exec_time"),
                    models.Index(fields=["module", "object_pk"], name="idx_oplog_module_objectpk"),
                    models.Index(fields=["path"], name="idx_oplog_path"),
                    models.Index(fields=["token_pk", "created_time"], name="idx_oplog_token_created"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserLoginLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("status", models.BooleanField(default=True, verbose_name="Login status")),
                ("ipaddress", models.GenericIPAddressField(blank=True, null=True, verbose_name="IpAddress")),
                ("city", models.CharField(blank=True, max_length=254, null=True, verbose_name="Login city")),
                ("browser", models.CharField(blank=True, max_length=64, null=True, verbose_name="Browser")),
                ("system", models.CharField(blank=True, max_length=64, null=True, verbose_name="System")),
                ("agent", models.CharField(blank=True, max_length=128, null=True, verbose_name="Agent")),
                ("channel_name", models.CharField(blank=True, max_length=128, null=True, verbose_name="Channel name")),
                (
                    "login_type",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Username and password"),
                            (1, "SMS verification code"),
                            (2, "Email verification code"),
                            (4, "Wechat scan code"),
                            (5, "Third-party OAuth"),
                            (3, "LDAP directory account"),
                            (8, "Websocket"),
                            (9, "Unknown"),
                            (6, "Impersonation"),
                        ],
                        default=0,
                        verbose_name="Login type",
                    ),
                ),
                (
                    "policy_result",
                    models.CharField(blank=True, default="", max_length=128, verbose_name="Policy result"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "User login log",
                "verbose_name_plural": "User login log",
                "ordering": ("-created_time",),
                "indexes": [models.Index(fields=["created_time"], name="idx_loginlog_created")],
            },
        ),
    ]
