# Generated by Django 6.0.8 on 2026-10-05 05:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("file", "0001_initial"),
        ("identity", "0002_deptinfo_rules_userinfo_rules_userrole_menu"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskExecution",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=255, verbose_name="Task Name")),
                ("args", models.JSONField(blank=True, default=list, verbose_name="Positional Args")),
                ("kwargs", models.JSONField(blank=True, default=dict, verbose_name="Keyword Args")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Waiting"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("REVOKED", "Revoked"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("date_start", models.DateTimeField(blank=True, null=True, verbose_name="Start Time")),
                ("date_finished", models.DateTimeField(blank=True, null=True, verbose_name="Finish Time")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "periodic_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_celery_beat.periodictask",
                        verbose_name="Periodic Task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Execution",
                "verbose_name_plural": "Task Execution",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="WebhookSubscription",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("name", models.CharField(max_length=128, unique=True, verbose_name="Name")),
                ("url", models.CharField(max_length=512, verbose_name="URL")),
                ("secret", models.CharField(max_length=512, verbose_name="Secret")),
                (
                    "events",
                    models.JSONField(default=list, help_text="Event keys from EVENT_CATALOG", verbose_name="Events"),
                ),
                ("description", models.CharField(blank=True, default="", max_length=512, verbose_name="Description")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                ("last_failure", models.CharField(blank=True, default="", max_length=512, verbose_name="Last failure")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook subscription",
                "verbose_name_plural": "Webhook subscriptions",
                "ordering": ("-created_time",),
            },
        ),
        migrations.CreateModel(
            name="ExportRecord",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="File name")),
                ("module", models.CharField(blank=True, max_length=128, null=True, verbose_name="Source module")),
                ("path", models.CharField(blank=True, max_length=255, null=True, verbose_name="Source path")),
                (
                    "file_format",
                    models.CharField(db_index=True, default="xlsx", max_length=16, verbose_name="File format"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Waiting"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("REVOKED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("rows", models.IntegerField(blank=True, null=True, verbose_name="Row count")),
                ("progress", models.PositiveSmallIntegerField(default=0, verbose_name="Progress")),
                ("stage", models.CharField(blank=True, default="", max_length=64, verbose_name="Progress stage")),
                ("error", models.TextField(blank=True, null=True, verbose_name="Error message")),
                ("params", models.JSONField(blank=True, default=dict, verbose_name="Export params")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="file.uploadfile",
                        verbose_name="Export file",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export record",
                "ordering": ["-created_time"],
                "indexes": [models.Index(fields=["status", "created_time"], name="idx_export_status_created")],
            },
        ),
        migrations.CreateModel(
            name="ImportRecord",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="File name")),
                ("module", models.CharField(blank=True, max_length=128, null=True, verbose_name="Target module")),
                ("path", models.CharField(blank=True, max_length=255, null=True, verbose_name="Source path")),
                (
                    "action",
                    models.CharField(
                        choices=[("create", "Create"), ("update", "Update")],
                        db_index=True,
                        default="create",
                        max_length=16,
                        verbose_name="Import action",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Waiting"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("REVOKED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("total", models.IntegerField(blank=True, null=True, verbose_name="Total rows")),
                ("success_rows", models.IntegerField(default=0, verbose_name="Success rows")),
                ("failed_rows", models.IntegerField(default=0, verbose_name="Failed rows")),
                ("progress", models.PositiveSmallIntegerField(default=0, verbose_name="Progress")),
                ("stage", models.CharField(blank=True, default="", max_length=64, verbose_name="Progress stage")),
                ("error", models.TextField(blank=True, null=True, verbose_name="Error message")),
                ("params", models.JSONField(blank=True, default=dict, verbose_name="Import params")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "error_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_error_reports",
                        to="file.uploadfile",
                        verbose_name="Error report",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_sources",
                        to="file.uploadfile",
                        verbose_name="Source file",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import record",
                "ordering": ["-created_time"],
                "indexes": [models.Index(fields=["status", "created_time"], name="idx_import_status_created")],
            },
        ),
        migrations.CreateModel(
            name="ImportTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                (
                    "model",
                    models.CharField(
                        db_index=True,
                        help_text="Model label like system.userinfo",
                        max_length=128,
                        verbose_name="Target model",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Template name")),
                ("mapping", models.JSONField(blank=True, default=dict, verbose_name="Column mapping")),
                ("options", models.JSONField(blank=True, default=dict, verbose_name="Import options")),
                ("is_shared", models.BooleanField(db_index=True, default=False, verbose_name="Shared")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import template",
                "ordering": ["-created_time"],
                "indexes": [models.Index(fields=["model", "is_shared"], name="idx_import_tpl_model_shared")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("model", "name", "creator"), name="uniq_import_template_model_name_creator"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("event", models.CharField(db_index=True, max_length=64, verbose_name="Event")),
                ("payload", models.JSONField(default=dict, verbose_name="Payload")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed (retrying)"),
                            ("exhausted", "Exhausted"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("attempt", models.IntegerField(default=0, verbose_name="Attempt")),
                ("response_code", models.IntegerField(blank=True, null=True, verbose_name="Response code")),
                (
                    "response_body",
                    models.CharField(blank=True, default="", max_length=500, verbose_name="Response body"),
                ),
                ("duration", models.FloatField(blank=True, help_text="Seconds", null=True, verbose_name="Duration")),
                ("next_retry_at", models.DateTimeField(blank=True, null=True, verbose_name="Next retry at")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="task.webhooksubscription",
                        verbose_name="Subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook delivery",
                "verbose_name_plural": "Webhook deliveries",
                "ordering": ("-created_time",),
                "indexes": [models.Index(fields=["subscription", "created_time"], name="idx_webhook_sub_created")],
            },
        ),
    ]
