# Generated by Django 6.0.8 on 2026-10-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookdelivery",
            name="generation",
            field=models.IntegerField(default=0, verbose_name="Generation"),
        ),
    ]
