# Generated by Django 6.0.8 on 2026-10-07 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("identity", "0002_deptinfo_rules_userinfo_rules_userrole_menu"),
        ("task", "0002_webhookdelivery_generation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodicTaskOwner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "periodic_task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_owner",
                        to="django_celery_beat.periodictask",
                        verbose_name="Periodic Task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Periodic task owner",
                "verbose_name_plural": "Periodic task owner",
                "ordering": ["-created_time"],
            },
        ),
    ]
