#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""文档事实门禁的事实清单（受保护事实与取值来源声明，自 check_doc_facts.py 拆分）。"""

FACTS = [
    {
        "doc": "docs/architecture/overview.md",
        "label": "技术栈表 Django 版本",
        "pattern": r"Django (\d+\.\d+\.\d+) \+ DRF",
        "source": "requirements:django",
    },
    {
        "doc": "docs/architecture/overview.md",
        "label": "技术栈表 DRF 版本",
        "pattern": r"\+ DRF (\d+\.\d+\.\d+)",
        "source": "requirements:djangorestframework",
    },
    {
        "doc": "docs/architecture/overview.md",
        "label": "ADR-004 摘要「当前运行 Django」",
        "pattern": r"当前运行 Django (\d+\.\d+\.\d+)",
        "source": "requirements:django",
    },
    {
        "doc": "docs/adr/README.md",
        "label": "ADR 索引 ADR-004 行「当前运行」",
        "pattern": r"当前运行 (\d+\.\d+\.\d+)；",
        "source": "requirements:django",
    },
    {
        "doc": "docs/ops/deployment.md",
        "label": "「适用于 xadmin-server X.Y.Z+」",
        "pattern": r"适用于 xadmin-server (\d+\.\d+\.\d+)\+",
        "source": "const:VERSION",
    },
    {
        "doc": "docs/architecture/overview.md",
        "label": "工程门禁「覆盖率门禁 N%」",
        "pattern": r"覆盖率门禁 (\d+)%",
        "source": "workflow:cov_fail_under",
    },
    {
        "doc": "docs/architecture/component-handbook.md",
        "label": "工程化设施表覆盖率门禁",
        "pattern": r"--cov-fail-under=(\d+)",
        "source": "workflow:cov_fail_under",
    },
    {
        "doc": "CONTRIBUTING.md",
        "label": "贡献指南覆盖率门禁",
        "pattern": r"--cov-fail-under=(\d+)",
        "source": "workflow:cov_fail_under",
    },
    {
        "doc": "docs/ops/release-checklist.md",
        "label": "发布全量门禁覆盖率要求",
        "pattern": r"覆盖率 ≥(\d+)%",
        "source": "workflow:cov_fail_under",
    },
    {
        "doc": "docs/README.md",
        "label": "文档索引 ADR 篇数",
        "pattern": r"架构决策记录索引（(\d+) 篇",
        "source": "adr:count",
    },
    # —— 跨仓：对外文档站（xadmin-docs）中的"当前状态"事实 ——
    {
        "doc": "guide/index.md",
        "external": True,
        "label": "文档站首页 Python 徽章",
        "pattern": r"python->=(\d+\.\d+)-green",
        "source": "workflow:python",
    },
    {
        "doc": "guide/index.md",
        "external": True,
        "label": "文档站首页 Django 徽章",
        "pattern": r"django:versions-(\d+\.\d+\.\d+)-blue",
        "source": "requirements:django",
    },
    {
        "doc": "guide/index.md",
        "external": True,
        "label": "文档站首页 Node 徽章",
        "pattern": r"node->=([\d.]+)-brightgreen",
        "source": "client_engine:node",
    },
    {
        "doc": "guide/index.md",
        "external": True,
        "label": "文档站首页描述「Django X.Y + Vue」",
        "pattern": r"Django (\d+\.\d+) \+ Vue",
        "source": "requirements_minor:django",
    },
    {
        "doc": "index.md",
        "external": True,
        "label": "文档站首页 tagline「Django X.Y + Vue」",
        "pattern": r"Django (\d+\.\d+) \+ Vue",
        "source": "requirements_minor:django",
    },
    {
        "doc": "guide/demo.md",
        "external": True,
        "label": "一键部署脚本版本号（VERSION=）",
        "pattern": r"VERSION=v(\d+\.\d+\.\d+)",
        "source": "const:VERSION",
    },
    {
        "doc": "README.md",
        "external": True,
        "label": "文档站仓库首页 Python 徽章",
        "pattern": r"python->=(\d+\.\d+)-green",
        "source": "workflow:python",
    },
    {
        "doc": "README.md",
        "external": True,
        "label": "文档站仓库首页 Django 徽章",
        "pattern": r"django:versions-(\d+\.\d+\.\d+)-blue",
        "source": "requirements:django",
    },
    {
        "doc": "README.md",
        "external": True,
        "label": "文档站仓库首页 Node 徽章",
        "pattern": r"node->=([\d.]+)-brightgreen",
        "source": "client_engine:node",
    },
    {
        "doc": "README.md",
        "external": True,
        "label": "文档站仓库首页描述「Django X.Y + Vue」",
        "pattern": r"Django (\d+\.\d+) \+ Vue",
        "source": "requirements_minor:django",
    },
    {
        "doc": "devguidelines/client.md",
        "external": True,
        "label": "文档站客户端开发 Node 要求",
        "pattern": r"Node \*\*≥ ([\d.]+)\*\*",
        "source": "client_engine:node",
    },
    {
        "doc": "devguidelines/client.md",
        "external": True,
        "label": "文档站客户端开发 pnpm 要求",
        "pattern": r"pnpm \*\*≥ (\d+)\*\*",
        "source": "client_engine:pnpm",
    },
    {
        "doc": "example/new-app-test.md",
        "external": True,
        "label": "文档站测试教程覆盖率门禁",
        "pattern": r"--cov-fail-under=(\d+)",
        "source": "workflow:cov_fail_under",
    },
    {
        "doc": "guide/installation-local.md",
        "external": True,
        "label": "本地安装文档 Python 建议版本",
        "pattern": r"建议使用 Python (\d+\.\d+)\+ 进行安装部署",
        "source": "workflow:python",
    },
    {
        "doc": "guide/installation-local.md",
        "external": True,
        "label": "本地安装文档依赖表 Python 版本",
        "pattern": r"python >=(\d+\.\d+)",
        "source": "workflow:python",
    },
    {
        "doc": "guide/installation-docker.md",
        "external": True,
        "label": "容器化安装文档依赖表 Python 版本",
        "pattern": r"python >=(\d+\.\d+)",
        "source": "workflow:python",
    },
    # —— 跨仓：客户端仓库（xadmin-client）中的"当前状态"事实 ——
    {
        "doc": "README.md",
        "external": "client",
        "label": "客户端 README Node 要求",
        "pattern": r"Node\.js \| >= ([\d.]+)",
        "source": "client_engine:node",
    },
    {
        "doc": "README.md",
        "external": "client",
        "label": "客户端 README pnpm 要求",
        "pattern": r"pnpm\s+\|\s+>=\s+(\d+)",
        "source": "client_engine:pnpm",
    },
    {
        "doc": "docs/development-guide.md",
        "external": "client",
        "label": "前端开发指引 Node 要求",
        "pattern": r"Node ≥ ([\d.]+)",
        "source": "client_engine:node",
    },
    {
        "doc": "docs/development-guide.md",
        "external": "client",
        "label": "前端开发指引 pnpm 要求",
        "pattern": r"pnpm ≥ (\d+)",
        "source": "client_engine:pnpm",
    },
]
