# Generated by Django 5.2.9 on 2026-09-04 03:12

import common.core.models
import common.fields.image
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0003_userloginlog_channel_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated time')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('category', models.SmallIntegerField(choices=[(0, '小说'), (1, '文学'), (2, '哲学')], default=0, verbose_name='书籍类型')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='', verbose_name='书籍封面原图')),
                ('avatar', common.fields.image.ProcessedImageField(blank=True, null=True, upload_to=common.core.models.upload_directory_path, verbose_name='书籍封面缩略图')),
                ('book_file', models.FileField(blank=True, null=True, upload_to=common.core.models.upload_directory_path, verbose_name='书籍存储')),
                ('name', models.CharField(help_text='书籍名称啊，随便填', max_length=100, verbose_name='书籍名称')),
                ('isbn', models.CharField(max_length=20, verbose_name='标准书号')),
                ('author', models.CharField(help_text='坐着大啊啊士大夫', max_length=20, verbose_name='书籍作者')),
                ('publisher', models.CharField(default='大宇出版社', max_length=20, verbose_name='出版社')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='出版日期')),
                ('price', models.FloatField(default=999.99, verbose_name='书籍售价')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否启用')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='管理员1')),
                ('admin2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_admin2', to=settings.AUTH_USER_MODEL, verbose_name='管理员2')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('dept_belong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='dept_belong_query', to='system.deptinfo', verbose_name='Data ownership department')),
                ('file', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_file', to='system.uploadfile', verbose_name='书籍单个附件')),
                ('files', models.ManyToManyField(blank=True, related_name='book_files', to='system.uploadfile', verbose_name='书籍多附件')),
                ('managers', models.ManyToManyField(blank=True, related_name='book_managers', to=settings.AUTH_USER_MODEL, verbose_name='操作人员1')),
                ('managers2', models.ManyToManyField(blank=True, related_name='book_managers2', to=settings.AUTH_USER_MODEL, verbose_name='操作人员2')),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='modifier_query', to=settings.AUTH_USER_MODEL, verbose_name='Modifier')),
            ],
            options={
                'verbose_name': '书籍名称',
                'verbose_name_plural': '书籍名称',
            },
            bases=(common.core.models.AutoCleanFileMixin, models.Model),
        ),
    ]
