# Generated by Django 5.2.9 on 2026-09-04 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('pk',), 'verbose_name': '书籍名称', 'verbose_name_plural': '书籍名称'},
        ),
    ]
