# Generated by Django 6.0.8 on 2026-10-05 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("approval", "0001_initial"),
        ("demo", "0001_initial"),
        ("system", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_file",
                to="system.uploadfile",
                verbose_name="书籍单个附件",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="files",
            field=models.ManyToManyField(
                blank=True, related_name="book_files", to="system.uploadfile", verbose_name="书籍多附件"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="demo_books",
                to="approval.approvalinstance",
                verbose_name="审批实例",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="managers",
            field=models.ManyToManyField(
                blank=True, related_name="book_managers", to=settings.AUTH_USER_MODEL, verbose_name="操作人员1"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="managers2",
            field=models.ManyToManyField(
                blank=True, related_name="book_managers2", to=settings.AUTH_USER_MODEL, verbose_name="操作人员2"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
    ]
