# Generated by Django 6.0.8 on 2026-09-26 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approval", "0001_initial"),
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="book",
                    name="instance",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demo_books",
                        to="approval.approvalinstance",
                        verbose_name="审批实例",
                    ),
                ),
            ],
        ),
    ]
