# Generated by Django 6.0.8 on 2026-09-26 12:54

import uuid

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("system", "0015_approvals_split_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # 3.1 拆分批次3：模型自 system 迁入，表已在库中（system_* 表名保持），
            # 全部为纯状态操作，不做任何 DDL
            state_operations=[
                migrations.CreateModel(
                    name="AiKnowledgeDocument",
                    fields=[
                        (
                            "id",
                            models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID"),
                        ),
                        (
                            "created_time",
                            models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time"),
                        ),
                        ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                        (
                            "description",
                            models.CharField(blank=True, max_length=256, null=True, verbose_name="Description"),
                        ),
                        (
                            "source_type",
                            models.CharField(
                                choices=[("repo", "Repository docs"), ("upload", "Uploaded document")],
                                db_index=True,
                                default="repo",
                                max_length=16,
                                verbose_name="Source type",
                            ),
                        ),
                        ("path", models.CharField(max_length=255, unique=True, verbose_name="Storage path")),
                        ("title", models.CharField(blank=True, default="", max_length=255, verbose_name="Title")),
                        ("content", models.TextField(blank=True, default="", verbose_name="Content")),
                        (
                            "content_hash",
                            models.CharField(blank=True, default="", max_length=64, verbose_name="Content hash"),
                        ),
                        ("chunk_count", models.IntegerField(default=0, verbose_name="Chunk count")),
                        ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Active")),
                        ("synced_at", models.DateTimeField(auto_now=True, verbose_name="Synced at")),
                        (
                            "creator",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="creator_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Creator",
                            ),
                        ),
                        (
                            "dept_belong",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="dept_belong_query",
                                to="system.deptinfo",
                                verbose_name="Data ownership department",
                            ),
                        ),
                        (
                            "modifier",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="modifier_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Modifier",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "AI knowledge document",
                        "verbose_name_plural": "AI knowledge documents",
                        "db_table": "system_aiknowledgedocument",
                        "ordering": ("-synced_at",),
                    },
                ),
                migrations.CreateModel(
                    name="AiChatMessage",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        (
                            "created_time",
                            models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time"),
                        ),
                        ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                        (
                            "description",
                            models.CharField(blank=True, max_length=256, null=True, verbose_name="Description"),
                        ),
                        (
                            "feature",
                            models.CharField(
                                choices=[("docs", "Document Q&A"), ("nl", "NL query"), ("action", "Action execution")],
                                db_index=True,
                                max_length=16,
                                verbose_name="Feature",
                            ),
                        ),
                        (
                            "role",
                            models.CharField(
                                choices=[("user", "User"), ("assistant", "Assistant"), ("system", "System")],
                                max_length=16,
                                verbose_name="Role",
                            ),
                        ),
                        ("content", models.TextField(blank=True, default="", verbose_name="Content")),
                        ("reasoning", models.TextField(blank=True, default="", verbose_name="Reasoning")),
                        (
                            "extra",
                            models.JSONField(
                                blank=True,
                                default=dict,
                                encoder=django.core.serializers.json.DjangoJSONEncoder,
                                verbose_name="Extra",
                            ),
                        ),
                        (
                            "creator",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="creator_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Creator",
                            ),
                        ),
                        (
                            "dept_belong",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="dept_belong_query",
                                to="system.deptinfo",
                                verbose_name="Data ownership department",
                            ),
                        ),
                        (
                            "modifier",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="modifier_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Modifier",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "AI chat message",
                        "verbose_name_plural": "AI chat messages",
                        "db_table": "system_aichatmessage",
                        "ordering": ("-id",),
                        "indexes": [
                            models.Index(fields=["creator", "feature", "-id"], name="ai_chat_msg_user_feat_idx")
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="AiKnowledgeChunk",
                    fields=[
                        (
                            "id",
                            models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID"),
                        ),
                        (
                            "created_time",
                            models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time"),
                        ),
                        ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                        (
                            "description",
                            models.CharField(blank=True, max_length=256, null=True, verbose_name="Description"),
                        ),
                        ("source_path", models.CharField(db_index=True, max_length=255, verbose_name="Source path")),
                        ("title", models.CharField(blank=True, default="", max_length=255, verbose_name="Title")),
                        ("chunk_index", models.IntegerField(default=0, verbose_name="Chunk index")),
                        ("content", models.TextField(verbose_name="Content")),
                        ("content_hash", models.CharField(max_length=64, verbose_name="Content hash")),
                        ("synced_at", models.DateTimeField(auto_now=True, verbose_name="Synced at")),
                        (
                            "creator",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="creator_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Creator",
                            ),
                        ),
                        (
                            "dept_belong",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="dept_belong_query",
                                to="system.deptinfo",
                                verbose_name="Data ownership department",
                            ),
                        ),
                        (
                            "modifier",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="modifier_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Modifier",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "AI knowledge chunk",
                        "verbose_name_plural": "AI knowledge chunks",
                        "db_table": "system_aiknowledgechunk",
                        "ordering": ("source_path", "chunk_index"),
                        "constraints": [
                            models.UniqueConstraint(
                                fields=("source_path", "chunk_index"), name="uniq_ai_chunk_path_index"
                            )
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="AiProfile",
                    fields=[
                        (
                            "id",
                            models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID"),
                        ),
                        (
                            "created_time",
                            models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time"),
                        ),
                        ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                        (
                            "description",
                            models.CharField(blank=True, max_length=256, null=True, verbose_name="Description"),
                        ),
                        ("name", models.CharField(max_length=64, unique=True, verbose_name="Profile name")),
                        ("base_url", models.CharField(max_length=256, verbose_name="Base URL")),
                        ("api_key", models.TextField(blank=True, default="", verbose_name="API Key")),
                        ("model", models.CharField(max_length=128, verbose_name="Model")),
                        ("temperature", models.FloatField(blank=True, null=True, verbose_name="Temperature")),
                        ("max_tokens", models.IntegerField(blank=True, null=True, verbose_name="Max tokens")),
                        ("top_p", models.FloatField(blank=True, null=True, verbose_name="Top P")),
                        (
                            "frequency_penalty",
                            models.FloatField(blank=True, null=True, verbose_name="Frequency penalty"),
                        ),
                        ("presence_penalty", models.FloatField(blank=True, null=True, verbose_name="Presence penalty")),
                        (
                            "stop",
                            models.CharField(blank=True, default="", max_length=255, verbose_name="Stop sequences"),
                        ),
                        ("seed", models.IntegerField(blank=True, null=True, verbose_name="Seed")),
                        ("timeout", models.IntegerField(default=60, verbose_name="Timeout (seconds)")),
                        ("max_retries", models.IntegerField(default=0, verbose_name="Max retries")),
                        ("context_limit", models.IntegerField(default=20, verbose_name="Context messages")),
                        ("persona", models.TextField(blank=True, default="", verbose_name="Persona")),
                        (
                            "purpose",
                            models.CharField(
                                choices=[("chat", "Chat / Q&A"), ("structured", "Structured output")],
                                db_index=True,
                                default="chat",
                                max_length=16,
                                verbose_name="Purpose",
                            ),
                        ),
                        ("capabilities", models.JSONField(blank=True, default=dict, verbose_name="Capabilities")),
                        ("probed_at", models.DateTimeField(blank=True, null=True, verbose_name="Probed at")),
                        ("is_active", models.BooleanField(db_index=True, default=False, verbose_name="Is active")),
                        ("remark", models.CharField(blank=True, default="", max_length=255, verbose_name="Remark")),
                        (
                            "creator",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="creator_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Creator",
                            ),
                        ),
                        (
                            "dept_belong",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="dept_belong_query",
                                to="system.deptinfo",
                                verbose_name="Data ownership department",
                            ),
                        ),
                        (
                            "modifier",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="modifier_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Modifier",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "AI profile",
                        "verbose_name_plural": "AI profiles",
                        "db_table": "system_aiprofile",
                        "ordering": ("-is_active", "name"),
                        "constraints": [
                            models.UniqueConstraint(
                                condition=models.Q(("is_active", True)),
                                fields=("purpose", "is_active"),
                                name="uniq_ai_profile_purpose_active",
                            )
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="AiUsageRecord",
                    fields=[
                        (
                            "id",
                            models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID"),
                        ),
                        (
                            "created_time",
                            models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time"),
                        ),
                        ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                        (
                            "description",
                            models.CharField(blank=True, max_length=256, null=True, verbose_name="Description"),
                        ),
                        (
                            "feature",
                            models.CharField(
                                choices=[
                                    ("docs", "Document Q&A"),
                                    ("chat", "Chat"),
                                    ("nl", "NL query"),
                                    ("action", "Action execution"),
                                ],
                                db_index=True,
                                max_length=16,
                                verbose_name="Feature",
                            ),
                        ),
                        ("track", models.CharField(blank=True, default="", max_length=16, verbose_name="Track")),
                        (
                            "profile_name",
                            models.CharField(blank=True, default="", max_length=64, verbose_name="Profile"),
                        ),
                        ("model", models.CharField(blank=True, default="", max_length=128, verbose_name="Model")),
                        ("tokens_in", models.IntegerField(default=0, verbose_name="Tokens in")),
                        ("tokens_out", models.IntegerField(default=0, verbose_name="Tokens out")),
                        ("tokens_total", models.IntegerField(default=0, verbose_name="Tokens total")),
                        ("duration_ms", models.IntegerField(default=0, verbose_name="Duration (ms)")),
                        ("ok", models.BooleanField(db_index=True, default=True, verbose_name="Success")),
                        ("detail", models.CharField(blank=True, default="", max_length=255, verbose_name="Detail")),
                        (
                            "creator",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="creator_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Creator",
                            ),
                        ),
                        (
                            "dept_belong",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="dept_belong_query",
                                to="system.deptinfo",
                                verbose_name="Data ownership department",
                            ),
                        ),
                        (
                            "modifier",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                related_query_name="modifier_query",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Modifier",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "AI usage record",
                        "verbose_name_plural": "AI usage records",
                        "db_table": "system_aiusagerecord",
                        "ordering": ("-created_time",),
                        "indexes": [
                            models.Index(fields=["creator", "-created_time"], name="ai_usage_user_time_idx"),
                            models.Index(fields=["feature", "-created_time"], name="ai_usage_feat_time_idx"),
                        ],
                    },
                ),
            ],
        ),
    ]
