# Generated by Django 6.0.8 on 2026-09-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiknowledgechunk",
            name="embedding",
            field=models.BinaryField(blank=True, null=True, verbose_name="Embedding"),
        ),
        migrations.AddField(
            model_name="aiknowledgechunk",
            name="embedding_dim",
            field=models.IntegerField(default=0, verbose_name="Embedding dimension"),
        ),
        migrations.AddField(
            model_name="aiknowledgechunk",
            name="embedding_hash",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="Embedding source hash"),
        ),
        migrations.AddField(
            model_name="aiknowledgechunk",
            name="embedding_model",
            field=models.CharField(blank=True, default="", max_length=128, verbose_name="Embedding model"),
        ),
        migrations.AlterField(
            model_name="aiprofile",
            name="purpose",
            field=models.CharField(
                choices=[("chat", "Chat / Q&A"), ("structured", "Structured output"), ("embedding", "Text embedding")],
                db_index=True,
                default="chat",
                max_length=16,
                verbose_name="Purpose",
            ),
        ),
        migrations.AlterField(
            model_name="aiusagerecord",
            name="feature",
            field=models.CharField(
                choices=[
                    ("docs", "Document Q&A"),
                    ("chat", "Chat"),
                    ("nl", "NL query"),
                    ("action", "Action execution"),
                    ("embedding", "Knowledge embedding"),
                ],
                db_index=True,
                max_length=16,
                verbose_name="Feature",
            ),
        ),
    ]
