# Generated by Django 6.0.8 on 2026-09-30 13:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0002_knowledge_embeddings"),
        ("system", "0008_upload_chunk_session"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="McpServer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("name", models.CharField(max_length=64, unique=True, verbose_name="Server name")),
                (
                    "url",
                    models.CharField(help_text="Streamable HTTP endpoint", max_length=512, verbose_name="Server URL"),
                ),
                (
                    "auth_header",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. Authorization",
                        max_length=64,
                        verbose_name="Auth header",
                    ),
                ),
                ("auth_token", models.TextField(blank=True, default="", verbose_name="Auth token")),
                ("timeout", models.IntegerField(default=30, verbose_name="Timeout (seconds)")),
                ("allowed_tools", models.JSONField(blank=True, default=list, verbose_name="Allowed tools")),
                ("enabled", models.BooleanField(db_index=True, default=True, verbose_name="Enabled")),
                ("tools_snapshot", models.JSONField(blank=True, default=list, verbose_name="Tools snapshot")),
                ("last_synced_time", models.DateTimeField(blank=True, null=True, verbose_name="Last synced time")),
                (
                    "last_sync_error",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Last sync error"),
                ),
                ("remark", models.CharField(blank=True, default="", max_length=255, verbose_name="Remark")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "External MCP server",
                "verbose_name_plural": "External MCP servers",
                "db_table": "system_mcpserver",
                "ordering": ("name",),
            },
        ),
    ]
