# Generated by Django 6.0.8 on 2026-10-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0003_mcpserver"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcpserver",
            name="expose_to_ai",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Expose to AI actions"),
        ),
    ]
