# Generated by Django 6.0.8 on 2026-10-03 00:44
"""TG-3（ADR-080）：物理表名归域——6 个模型的显式 ``db_table``（``system_*`` 冻结名）
全部移除，表名回落 Django 默认命名（``ai_<模型名小写>``）；语义见 approval/0005 同批迁移。
"""

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0005_aiknowledgechunk_embedding_vector"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="aichatmessage",
            table=None,
        ),
        migrations.AlterModelTable(
            name="aiknowledgechunk",
            table=None,
        ),
        migrations.AlterModelTable(
            name="aiknowledgedocument",
            table=None,
        ),
        migrations.AlterModelTable(
            name="aiprofile",
            table=None,
        ),
        migrations.AlterModelTable(
            name="aiusagerecord",
            table=None,
        ),
        migrations.AlterModelTable(
            name="mcpserver",
            table=None,
        ),
    ]
