# Generated by Django 4.2.7 on 2023-12-08 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.base.daobase
import system.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述信息')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='演员名字')),
                ('foreign_name', models.CharField(max_length=64, verbose_name='外文')),
                ('avatar', models.FileField(blank=True, null=True, upload_to=system.models.upload_directory_path,
                                            verbose_name='头像')),
                ('sex', models.SmallIntegerField(default=0, help_text='0：男 1：女 2：保密', verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('enable', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '演员',
                'verbose_name_plural': '演员',
            },
        ),
        migrations.CreateModel(
            name='AliyunDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述信息')),
                ('user_name', models.CharField(max_length=128, verbose_name='用户名')),
                ('nick_name', models.CharField(max_length=128, verbose_name='昵称')),
                ('user_id', models.CharField(max_length=32, verbose_name='用户ID')),
                ('default_drive_id', models.CharField(max_length=16, verbose_name='存储ID')),
                ('default_sbox_drive_id', models.CharField(max_length=16, verbose_name='保险箱ID')),
                ('access_token', common.base.daobase.AESCharField(max_length=1536, verbose_name='访问token')),
                ('refresh_token', common.base.daobase.AESCharField(max_length=512, verbose_name='刷新token')),
                ('avatar', models.CharField(max_length=512, verbose_name='头像地址')),
                ('expire_time', models.DateTimeField(auto_now_add=True, verbose_name='过期信息')),
                ('x_device_id', models.CharField(max_length=128, verbose_name='设备ID')),
                ('used_size', models.BigIntegerField(default=0, verbose_name='已经使用空间')),
                ('total_size', models.BigIntegerField(default=0, verbose_name='总空间大小')),
                ('enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('private', models.BooleanField(default=True,
                                                verbose_name='是否私有，若设置为否，则该网盘可被其他用户进行上传下载')),
                ('active', models.BooleanField(default=True, verbose_name='密钥是否可用')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                            verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '阿里云网盘认证信息',
                'verbose_name_plural': '阿里云网盘认证信息',
                'unique_together': {('owner', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='AliyunFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述信息')),
                ('name', models.CharField(max_length=256, verbose_name='文件名字')),
                ('file_id', models.CharField(max_length=64, verbose_name='文件id')),
                ('drive_id', models.CharField(max_length=64, verbose_name='drive_id')),
                ('size', models.BigIntegerField(verbose_name='文件大小')),
                ('content_type', models.CharField(max_length=64, verbose_name='文件类型')),
                ('category', models.CharField(max_length=64, verbose_name='类别')),
                ('content_hash', models.CharField(max_length=64, verbose_name='content_hash')),
                ('crc64_hash', models.CharField(max_length=64, verbose_name='crc64_hash')),
                ('downloads', models.BigIntegerField(default=0, verbose_name='下载次数')),
                ('duration', models.FloatField(default=0, verbose_name='视频长度')),
                ('is_upload', models.BooleanField(default=True, verbose_name='是否是上传的文件数据')),
                ('aliyun_drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.aliyundrive',
                                                   verbose_name='所属阿里云盘')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                            verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '文件信息',
                'verbose_name_plural': '文件信息',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述信息')),
                ('name', models.CharField(max_length=64, verbose_name='类别')),
                ('category_type', models.SmallIntegerField(
                    choices=[(1, '视频渠道'), (2, '地区国家'), (3, '视频类型'), (4, '视频语言'), (5, '视频字幕')],
                    default=1, verbose_name='类型')),
                ('enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('rank', models.IntegerField(default=999, verbose_name='展示顺序')),
            ],
            options={
                'verbose_name': '类型',
                'verbose_name_plural': '类型',
                'ordering': ['rank'],
                'unique_together': {('category_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FilmInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述信息')),
                ('name', models.CharField(max_length=64, verbose_name='电影片名')),
                ('title', models.CharField(max_length=64, verbose_name='电影译名')),
                ('poster', models.FileField(blank=True, null=True, upload_to=system.models.upload_directory_path,
                                            verbose_name='海报')),
                ('times', models.IntegerField(default=90, verbose_name='片长，分钟')),
                ('rate', models.DecimalField(decimal_places=1, default=5, max_digits=5, verbose_name='评分')),
                ('enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('views', models.BigIntegerField(default=0, verbose_name='观看次数')),
                ('release_date', models.DateField(verbose_name='上映时间')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='剧情')),
                ('category', models.ManyToManyField(related_name='film_category', to='movies.category',
                                                    verbose_name='类别，科幻，灾难，武侠等分类')),
                ('channel', models.ManyToManyField(related_name='channel_category', to='movies.category',
                                                   verbose_name='频道，电影，电视，综艺等分类')),
                ('director',
                 models.ManyToManyField(related_name='director_actor', to='movies.actorinfo', verbose_name='导演')),
                ('language', models.ManyToManyField(related_name='language_category', to='movies.category',
                                                    verbose_name='语言，中文，英语，韩语等')),
                ('region', models.ManyToManyField(related_name='region_category', to='movies.category',
                                                  verbose_name='地区，内地，中国台湾，中国香港，欧洲等分类')),
                ('starring',
                 models.ManyToManyField(related_name='starring_actor', to='movies.actorinfo', verbose_name='演员')),
                ('subtitle', models.ManyToManyField(related_name='subtitle_category', to='movies.category',
                                                    verbose_name='字幕，中英对照')),
            ],
            options={
                'verbose_name': '影片信息',
                'verbose_name_plural': '影片信息',
            },
        ),
        migrations.CreateModel(
            name='SwipeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述信息')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='轮播名称')),
                ('picture', models.FileField(blank=True, null=True, upload_to=system.models.upload_directory_path,
                                             verbose_name='轮播图片')),
                ('route', models.CharField(blank=True, max_length=128, null=True, verbose_name='前端路由地址')),
                ('rank', models.IntegerField(default=999, verbose_name='轮播图片顺序')),
                ('enable', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '轮播图片',
                'verbose_name_plural': '轮播图片',
            },
        ),
        migrations.CreateModel(
            name='EpisodeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述信息')),
                ('rank', models.IntegerField(default=999, verbose_name='多级电影顺序')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='电影单集名称')),
                ('extra_info', models.JSONField(blank=True, null=True, verbose_name='额外信息')),
                ('enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('views', models.BigIntegerField(default=0, verbose_name='观看次数')),
                ('files', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.aliyunfile',
                                               verbose_name='视频文件')),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           to='movies.filminfo', verbose_name='视频文件列表')),
            ],
            options={
                'verbose_name': '单集影片信息',
                'verbose_name_plural': '单集影片信息',
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述信息')),
                ('times', models.FloatField(verbose_name='播放的时间')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.episodeinfo',
                                              verbose_name='单集视频')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.filminfo',
                                           verbose_name='视频')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            related_query_name='history_query', to=settings.AUTH_USER_MODEL,
                                            verbose_name='创建人')),
            ],
            options={
                'verbose_name': '播放历史',
                'verbose_name_plural': '播放历史',
                'unique_together': {('owner', 'film')},
            },
        ),
    ]
