# Generated by Django 4.2.9 on 2024-01-19 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='watchhistory',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='history_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='filminfo',
            name='category',
            field=models.ManyToManyField(related_name='film_category', to='movies.category', verbose_name='类别，科幻，灾难，武侠等分类'),
        ),
        migrations.AddField(
            model_name='filminfo',
            name='channel',
            field=models.ManyToManyField(related_name='channel_category', to='movies.category', verbose_name='频道，电影，电视，综艺等分类'),
        ),
        migrations.AddField(
            model_name='filminfo',
            name='language',
            field=models.ManyToManyField(related_name='language_category', to='movies.category', verbose_name='语言，中文，英语，韩语等'),
        ),
        migrations.AddField(
            model_name='filminfo',
            name='region',
            field=models.ManyToManyField(related_name='region_category', to='movies.category', verbose_name='地区，内地，中国台湾，中国香港，欧洲等分类'),
        ),
        migrations.AddField(
            model_name='filminfo',
            name='starring',
            field=models.ManyToManyField(related_name='starring_actor', through='movies.ActorShip', to='movies.actorinfo', verbose_name='演员'),
        ),
        migrations.AddField(
            model_name='episodeinfo',
            name='files',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.aliyunfile', verbose_name='视频文件'),
        ),
        migrations.AddField(
            model_name='episodeinfo',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.filminfo', verbose_name='视频文件列表'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('category_type', 'name')},
        ),
        migrations.AddField(
            model_name='aliyunfile',
            name='aliyun_drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.aliyundrive', verbose_name='所属阿里云盘'),
        ),
        migrations.AddField(
            model_name='aliyunfile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='aliyundrive',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='actorship',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.actorinfo'),
        ),
        migrations.AddField(
            model_name='actorship',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.filminfo'),
        ),
        migrations.AlterUniqueTogether(
            name='watchhistory',
            unique_together={('owner', 'film')},
        ),
        migrations.AlterUniqueTogether(
            name='aliyundrive',
            unique_together={('owner', 'user_id')},
        ),
    ]
