# Generated by Django 6.0.8 on 2026-10-05 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("message_type", models.CharField(max_length=128, unique=True, verbose_name="Message type")),
                ("subject_template", models.TextField(blank=True, default="", verbose_name="Subject template")),
                ("body_template", models.TextField(blank=True, default="", verbose_name="Body template")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                ("remark", models.CharField(blank=True, default="", max_length=255, verbose_name="Remark")),
            ],
            options={
                "verbose_name": "Message template",
                "verbose_name_plural": "Message template",
                "ordering": ["message_type"],
            },
        ),
        migrations.CreateModel(
            name="MessageUserRead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("unread", models.BooleanField(default=True, verbose_name="Unread")),
            ],
            options={
                "verbose_name": "User read message",
                "verbose_name_plural": "User read message",
                "ordering": ("-created_time",),
            },
        ),
        migrations.CreateModel(
            name="SystemMsgSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("message_type", models.CharField(max_length=128, unique=True, verbose_name="message type")),
                ("receive_backends", models.JSONField(default=list, verbose_name="receive backend")),
            ],
            options={
                "verbose_name": "System message subscription",
            },
        ),
        migrations.CreateModel(
            name="UserMsgSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("message_type", models.CharField(max_length=128, verbose_name="message type")),
                ("receive_backends", models.JSONField(default=list, verbose_name="receive backend")),
            ],
            options={
                "verbose_name": "User message subscription",
            },
        ),
        migrations.CreateModel(
            name="MessageContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted at")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Ordinary notices"),
                            ("primary", "General notices"),
                            ("success", "Success notices"),
                            ("danger", "Important notices"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="Notice level",
                    ),
                ),
                (
                    "notice_type",
                    models.SmallIntegerField(
                        choices=[
                            (0, "System notification"),
                            (1, "System announcement"),
                            (2, "User notification"),
                            (3, "Department notification"),
                            (4, "Role notification"),
                            (5, "Post notification"),
                        ],
                        default=2,
                        verbose_name="Notice type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Notice title")),
                ("message", models.TextField(blank=True, null=True, verbose_name="Notice message")),
                ("extra_json", models.JSONField(blank=True, null=True, verbose_name="Additional json data")),
                ("publish", models.BooleanField(default=True, verbose_name="Publish")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="identity.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message content",
                "verbose_name_plural": "Message content",
                "ordering": ("-created_time",),
            },
            bases=(common.core.models.AutoCleanFileMixin, models.Model),
        ),
    ]
