# Generated by Django 5.1.1 on 2024-09-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated time')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('level', models.CharField(choices=[('info', 'Ordinary notices'), ('primary', 'General notices'),
                                                    ('success', 'Success notices'), ('danger', 'Important notices')],
                                           default='info', max_length=20, verbose_name='Notice level')),
                ('notice_type', models.SmallIntegerField(
                    choices=[(0, 'System notification'), (1, 'System announcement'), (2, 'User notification'),
                             (3, 'Department notification'), (4, 'Role notification')], default=2,
                    verbose_name='Notice type')),
                ('title', models.CharField(max_length=255, verbose_name='Notice title')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Notice message')),
                ('extra_json', models.JSONField(blank=True, null=True, verbose_name='Additional json data')),
                ('publish', models.BooleanField(default=True, verbose_name='Publish')),
            ],
            options={
                'verbose_name': 'Message content',
                'verbose_name_plural': 'Message content',
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='MessageUserRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated time')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('unread', models.BooleanField(db_index=True, default=True, verbose_name='Unread')),
            ],
            options={
                'verbose_name': 'User read message',
                'verbose_name_plural': 'User read message',
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='SystemMsgSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated time')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('message_type', models.CharField(max_length=128, unique=True, verbose_name='message type')),
                ('receive_backends', models.JSONField(default=list, verbose_name='receive backend')),
            ],
            options={
                'verbose_name': 'System message subscription',
            },
        ),
        migrations.CreateModel(
            name='UserMsgSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated time')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('message_type', models.CharField(max_length=128, verbose_name='message type')),
                ('receive_backends', models.JSONField(default=list, verbose_name='receive backend')),
            ],
            options={
                'verbose_name': 'User message subscription',
            },
        ),
    ]
