# Generated by Django 6.0.8 on 2026-10-05 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0001_initial"),
        ("notifications", "0001_initial"),
        ("system", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="messagecontent",
            name="file",
            field=models.ManyToManyField(to="system.uploadfile", verbose_name="Uploaded attachments"),
        ),
        migrations.AddField(
            model_name="messagecontent",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddField(
            model_name="messagecontent",
            name="notice_dept",
            field=models.ManyToManyField(blank=True, to="identity.deptinfo", verbose_name="The notified department"),
        ),
        migrations.AddField(
            model_name="messagecontent",
            name="notice_post",
            field=models.ManyToManyField(blank=True, to="identity.post", verbose_name="The notified post"),
        ),
        migrations.AddField(
            model_name="messagecontent",
            name="notice_role",
            field=models.ManyToManyField(blank=True, to="identity.userrole", verbose_name="The notified role"),
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="identity.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddField(
            model_name="messageuserread",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="messageuserread",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="identity.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="messageuserread",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddField(
            model_name="messageuserread",
            name="notice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="notifications.messagecontent", verbose_name="Notice"
            ),
        ),
        migrations.AddField(
            model_name="messageuserread",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="User"
            ),
        ),
        migrations.AddField(
            model_name="messagecontent",
            name="notice_user",
            field=models.ManyToManyField(
                blank=True,
                through="notifications.MessageUserRead",
                through_fields=("notice", "owner"),
                to=settings.AUTH_USER_MODEL,
                verbose_name="The notified user",
            ),
        ),
        migrations.AddField(
            model_name="systemmsgsubscription",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="systemmsgsubscription",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="identity.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="systemmsgsubscription",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddField(
            model_name="systemmsgsubscription",
            name="users",
            field=models.ManyToManyField(
                related_name="system_msg_subscriptions", to=settings.AUTH_USER_MODEL, verbose_name="User"
            ),
        ),
        migrations.AddField(
            model_name="usermsgsubscription",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="usermsgsubscription",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="identity.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="usermsgsubscription",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddField(
            model_name="usermsgsubscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_msg_subscription",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddIndex(
            model_name="messageuserread",
            index=models.Index(fields=["owner", "unread"], name="notificatio_owner_i_fd088f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="messageuserread",
            unique_together={("owner", "notice")},
        ),
        migrations.AddIndex(
            model_name="messagecontent",
            index=models.Index(fields=["created_time"], name="idx_msg_created"),
        ),
        migrations.AddIndex(
            model_name="messagecontent",
            index=models.Index(fields=["notice_type"], name="idx_msg_notice_type"),
        ),
        migrations.AlterUniqueTogether(
            name="usermsgsubscription",
            unique_together={("user", "message_type")},
        ),
    ]
