# Generated by Django 5.2.9 on 2026-09-04 23:42
#
# PERF-04：MessageContent 补建 created_time 索引（列表默认排序 + 时间范围过滤）；
# MessageUserRead.unread 的单列索引与 (owner, unread) 复合索引左前缀重复，属冗余索引，予以移除。

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        ('system', '0004_operationlog_idx_oplog_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageuserread',
            name='unread',
            field=models.BooleanField(default=True, verbose_name='Unread'),
        ),
        migrations.AddIndex(
            model_name='messagecontent',
            index=models.Index(fields=['created_time'], name='idx_msg_created'),
        ),
    ]
