# Generated by Django 6.0.8 on 2026-09-26 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_initial"),
        ("system", "0003_userloginlog_channel_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created time")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="Updated time")),
                ("description", models.CharField(blank=True, max_length=256, null=True, verbose_name="Description")),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("message_type", models.CharField(max_length=128, unique=True, verbose_name="Message type")),
                ("subject_template", models.TextField(blank=True, default="", verbose_name="Subject template")),
                ("body_template", models.TextField(blank=True, default="", verbose_name="Body template")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                ("remark", models.CharField(blank=True, default="", max_length=255, verbose_name="Remark")),
            ],
            options={
                "verbose_name": "Message template",
                "verbose_name_plural": "Message template",
                "ordering": ["message_type"],
            },
        ),
        migrations.AddField(
            model_name="messagecontent",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted at"),
        ),
        migrations.AlterField(
            model_name="messageuserread",
            name="unread",
            field=models.BooleanField(default=True, verbose_name="Unread"),
        ),
        migrations.AddIndex(
            model_name="messagecontent",
            index=models.Index(fields=["created_time"], name="idx_msg_created"),
        ),
        migrations.AddIndex(
            model_name="messagecontent",
            index=models.Index(fields=["notice_type"], name="idx_msg_notice_type"),
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
    ]
