# Generated by Django 6.0.8 on 2026-09-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_messagetemplate_messagecontent_deleted_at_and_more"),
        ("system", "0005_post_userinfo_posts_post_uniq_post_name_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagecontent",
            name="notice_post",
            field=models.ManyToManyField(blank=True, to="system.post", verbose_name="The notified post"),
        ),
        migrations.AlterField(
            model_name="messagecontent",
            name="notice_type",
            field=models.SmallIntegerField(
                choices=[
                    (0, "System notification"),
                    (1, "System announcement"),
                    (2, "User notification"),
                    (3, "Department notification"),
                    (4, "Role notification"),
                    (5, "Post notification"),
                ],
                default=2,
                verbose_name="Notice type",
            ),
        ),
    ]
