# Generated by Django 6.0.8 on 2026-09-14 05:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_messagecontent_deleted_at_and_more"),
        ("system", "0005_aiprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="messagecontent",
            index=models.Index(fields=["notice_type"], name="idx_msg_notice_type"),
        ),
    ]
